### ISSUE TITLE
Offline channels no hide on live tab when disable option

### ISSUE THREAD

**Issue by AkumaNervoso** [night/betterttv#6839] opened 2024-05-31 22:52 UTC
### Describe the bug

Offline channels no hide on live tab when disable option

### Steps to reproduce

disable show offline channels option, refresh the page and no effects

### Expected behavior

hide the channels offline

### Screenshots

![Captura de tela 2024-05-31 195225](https://github.com/night/betterttv/assets/165907003/1e8a6ac3-3b0a-4e7c-9634-0485e0ce10d0)

### Device information

Pc desktop chrome

**Comment by night** [comment] 2024-06-01 04:01
duplicate of #6837

**Closed by night** 2024-06-01 04:01 UTC
Labels: bug
