### ISSUE TITLE
Disable Host Mode — Disables hosted channels on Twitch

### ISSUE THREAD

**Issue by Smeagol001** [night/betterttv#4099] opened 2020-08-17 22:09 UTC
seems to not work with the chrome extension atleast  i have it "on" but i allways see me joining streams of ppl i not initially watched when the streamer i watched ends their stream

**Comment by Nareese** [comment] 2020-08-17 23:38
duplicate of #3933 

specifically, see this comment from night: https://github.com/night/betterttv/issues/3933#issuecomment-653938325

Also, this feature doesn't do anything to disable raids, which is the far more common way of moving people to a different channel after a stream ends these days.

**Closed** 2020-08-30 02:43 UTC
Labels: duplicate
