### ISSUE TITLE
Profile images way too big when clicking username in chat

### ISSUE THREAD

**Issue by Ciraxe** [night/BetterTTV#1800] opened 2016-11-29 23:13 UTC
![bttv-bug](https://cloud.githubusercontent.com/assets/450648/20733039/863b428a-b65f-11e6-9670-be0d5e64fd16.png)

**Comment by EhsanKia** [comment] 2016-11-29 23:25
Duplicate of #1799

**Closed by EhsanKia** 2016-11-29 23:25 UTC
