### ISSUE TITLE
[Feature Request] Option to save settings in a way that prevents the settings from being reset after the browser cache is cleared

### ISSUE THREAD

**Issue by 32423d** [night/betterttv#5549] opened 2022-08-02 02:38 UTC
Some other browser extensions such as Ublock Origin, Sponsorblock, and Augmented Steam save their settings you have set in a way that prevents the settings from being reset after clearing the cache of the browser (ex. clearing the cache of the browser, closing the browser, and then reopening the browser doesn't reset the settings you have set for Ublock Origin before you cleared the cache of the browser). If I was to clear the cache of my browser, close my browser, and then reopen my browser the settings for betterttv would be reset and the only way to set all my settings back to the way they were before I cleared the cache is to either remember how I set my settings before or save a backup file of my settings. It would be more convenient for betterttv users if betterttv was to save the settings users have set in a way that can't be reset just by clearing the cache of the browser.

**Comment by night** [comment] 2022-08-04 22:50
duplicate of #766

**Closed by night** 2022-08-04 22:50 UTC
Labels: duplicate
