### ISSUE TITLE
Highlights aren't working anymore

### ISSUE THREAD

**Issue by Rbcca** [night/BetterTTV#3205] opened 2018-08-17 22:49 UTC
Out of the blue my highlights weren't working anymore since yesterday. I checked my highlights and blacklist settings, deleted my cache and cookies, reinstalled BTTV countless times, disabled all other extensions on Firefox and even switched to Chrome and it isn't working.

**Comment by Nareese** [comment] 2018-08-18 16:03
duplicate of #3204

**Closed** 2018-08-19 00:58 UTC
Labels: duplicate
