### ISSUE TITLE
Title Bar Color?

### ISSUE THREAD

**Issue by SaiyanOfDarkness** [night/BetterTTV#2261] opened 2017-04-12 04:06 UTC
**Edit:** This is a Request

Recently Twitch updated it's layout.. and now there's a purple bar at the top.. is it possible to get a way to set it to a desired color?  It should be split in 3 different sections.  I was able to edit the color via Inspect Mode and changing the Hex to whatever color I wanted.  So I thought this should be doable.

**Comment by endPCE** [comment] 2017-04-12 04:12
Wait until they can actually work and release an update. For now you can use a CSS extension and add *.twitch.tv/ with this 

`.top-nav__drawer-anchor,.top-nav__logo {
background: none;
}

.top-nav__menu {
background: #333;
border-bottom: 1px solid #000;
}

.top-nav__nav-link {
color: #f9f9f9;
}`

**Comment by SaiyanOfDarkness** [comment] 2017-04-12 04:17
What extension do you recommend?

**Comment by jaaneh** [comment] 2017-04-12 06:46
Stylebot can do that for you. 

With it installed, go to Options -> Styles (left side) -> Add new style. And follow the comment above.

**Comment by SaiyanOfDarkness** [comment] 2017-04-12 06:48
Is it possible with Tamper/GreaseMonkey ?

**Comment by EhsanKia** [comment] 2017-04-12 06:53
Probably, but Stylish is made specifically for applying custom css to pages and makes it much easier. 

Never used Stylebot, but I'm guessing it's similar to Stylish.

**Comment by night** [comment] 2017-04-16 21:22
duplicate of #2260

**Closed by night** 2017-04-16 21:22 UTC
Labels: duplicate
