### ISSUE TITLE
Can't Dismiss Top Cheer

### ISSUE THREAD

**Issue by SaiyanOfDarkness** [night/BetterTTV#2398] opened 2017-05-01 08:34 UTC
Not sure if this is Twitch itself or BTTV related, but there is a link or "word" that says dismiss, but clicking on it does nothing.  Only thing I can do is inspect element and remove it currently.

**Comment by night** [comment] 2017-05-01 08:55
duplicate of #2255

**Closed by night** 2017-05-01 08:55 UTC
Labels: duplicate
