### ISSUE TITLE
New Emotes Not Working

### ISSUE THREAD

**Issue by sorceressofthefake** [night/BetterTTV#3633] opened 2019-10-29 05:48 UTC
I've been using BTTV for about a year and a half, and have had no issues until now. Recently, however, as streamers I watch have been adding new emotes to their streams, I've noticed that they aren't showing up in chat. I've tried uninstalling and reinstalling, but that hasn't seemed to help.

**Comment by night** [comment] 2019-10-29 06:46
duplicate of #3629

**Closed by night** 2019-10-29 06:46 UTC
Labels: invalid
