### ISSUE TITLE
Feature Suggestion: External Subs

### ISSUE THREAD

**Issue by Howla** [night/BetterTTV#872] opened 2015-12-24 21:51 UTC
There are several websites/services outside of Twitches own 'subscriber' program that enable smaller channels who are not partnered to give features/perks to their community for 'subscribing'. Like Gamewisp/Patrion , and i was thinking that a cool feature would be to upload a personal 'sub badge' and be able to manually assign that badge next to selected users name, of course this would only work in the Users channel (like the BTTV emotes). 
I think it would be a great feature for smaller channels to use to further benefit their supporters

**Comment by night** [comment] 2015-12-24 21:59
Duplicate of #857

**Closed by night** 2015-12-24 21:59 UTC
Labels: duplicate
