### ISSUE TITLE
Auto-theatre mode

### ISSUE THREAD

**Issue by fgsfdss** [night/BetterTTV#905] opened 2016-01-15 03:00 UTC
Edit: Auto-theatre mode is still there, it just doesn't work for me. Any help?

**Comment by voloshink** [comment] 2016-01-15 03:02
works for me, can't reproduce

**Comment by fgsfdss** [comment] 2016-01-15 03:15
Probably should have specified. I'm using Firefox 43.0.4, and I did try disabling other potentially conflicting addons.

**Comment by x003** [comment] 2016-01-15 07:23
Can confirm, it's not working for me either (I'm on Chrome)

**Comment by EsDeKa** [comment] 2016-01-15 14:12
I found a way to reproduce it, if go to a channel through a game directory (ex http://www.twitch.tv/directory/game/Dota%202 ) it doesn't activate. When I refresh the stream afterwards, theatre mode gets activated.

**Comment by EhsanKia** [comment] 2016-01-15 17:28
I'm not entirely sure it's the same bug, I could be wrong.

My understanding is that when you first load a page, `initialFuncs()` in `main.js` gets called, which calls `autoTheatreMode`.

Whereas when you switch pages, the Ember render callback is called, and if the template is `channel/index'`, we again call `AutoThreateMode`.

The latter is definitely broken in Chrome, and after some debugging, it's called too soon (even if it's wrapped in a ready callback).

`App.__container__.lookup('controller:channel').get('theatreMode')` is undefined, and the if statement fails.

The former is probably a similar issue where the controller is not fully loaded, but I can't debug because I can't get certificate exception working in FF.

**Comment by EhsanKia** [comment] 2016-01-15 17:52
Found the issue, `.get('theatreMode')` needs to be changed to `.get('isTheatreMode')`

This fixes the directory -> channel but, but I'm not sure if it fixes the Firefox issue.

**Comment by night** [comment] 2016-01-15 19:08
Fixed in e82fb21c02fb5d942573c258f35d852a7c5c0a44

**Closed by night** 2016-01-15 19:08 UTC
Labels: bug, channel
