### ISSUE TITLE
Cannot view my own emotes in chat

### ISSUE THREAD

**Issue by reck1essSOUL** [night/BetterTTV#2988] opened 2018-02-23 20:33 UTC
I have noticed recently that my BTTV emotes do not show up in chat. I see all the emotes in the menu fine buy when I press "Chat" button to send to the stream chat it does not show up. Furthermore, if I have an emote like PepePls in the "send a message" text box it deletes the text after a few seconds. I tried clearing cookies and cache but to no avail.

**Comment by Nareese** [comment] 2018-02-23 20:43
The emote text disappearing from the text box is a previously reported bug (#2987) that unfortunately the reporter closed before night had a chance to look into it.  Not sure yet if it's a twitch bug or a BTTV bug.  If you cannot see the emotes, make sure that you have the `BetterTTV Emotes` and `BetterTTV GIF Emotes` settings turned on.  If you still can't see them, and you are using any other twitch modifying extensions, please disable those other extensions and test again, as other extensions have been known to interfere with BTTV in the past.

**Comment by reck1essSOUL** [comment] 2018-02-23 20:52
I have everything to see the emotes on. I can see the menu and all the emotes and the only other extension is FrankerFacez. I tried and disable FrankerFacez but the issue is still there. I put an emote in the text box press "Chat" button but ny name and the emote does not appear in chat.

**Comment by Nareese** [comment] 2018-02-23 20:59
Ahhh... thanks for the additional info.  It's not that the emotes are not appearing in chat, it's that text input that consists solely of clicked emotes is never sent at all.   It would appear that issue might be related to the text disappearing issue, because from the textbox and "Chat" button's perspective, it probably thinks that the text box is still empty, so there's nothing to send.  Hitting enter also doesn't work for text that contains nothing but emote menu clicked emotes (does not affect tab completed emotes).  Thanks for the report and the additional information.

**Comment by reck1essSOUL** [comment] 2018-02-23 21:04
No problem, glad to provide info. I noticed if I type out the emotes they work and accessing them from the menu will cause to not appear.

**Comment by night** [comment] 2018-02-25 06:05
duplicate of #2987

**Closed by night** 2018-02-25 06:05 UTC
Labels: duplicate
