### ISSUE TITLE
"Swap to Live tab on the Following page automatically" not working

### ISSUE THREAD

**Issue by AeiouAiueo** [night/betterttv#6524] opened 2023-12-15 04:51 UTC
### Describe the bug

While having the "Swap to Live tab on the Following page automatically" option enabled, going to the Following page does not automatically open the Live tab

### Steps to reproduce

1: Make sure option is enabled
2: Go to Following page from other page on Twitch

### Expected behavior

The Following page immediately gets switched to Live tab

### Screenshots

Not applicable, I think.

### Device information

Windows 10 22H2 build 19045.3693
Firefox 120.0.1

**Comment by night** [comment] 2023-12-22 16:47
duplicate of #6478

**Closed by night** 2023-12-22 16:47 UTC
Labels: bug
