### ISSUE TITLE
BTTV chat error, only displaying emotes and unable to send messages with "Enter" on my computer

### ISSUE THREAD

**Issue by tyler29674** [night/BetterTTV#2008] opened 2017-01-28 01:19 UTC
<img width="1271" alt="screen shot 2017-01-27 at 8 17 41 pm" src="https://cloud.githubusercontent.com/assets/25396725/22393007/c018b04a-e4cd-11e6-9996-5747e4cc2f33.png">

**Comment by dapeton** [comment] 2017-01-28 01:53
Having the exact same problem, bump

**Comment by tonteasy** [comment] 2017-01-28 03:34
I am also having this problem.

**Comment by night** [comment] 2017-01-28 07:22
duplicate of #2005

**Closed by night** 2017-01-28 07:22 UTC
Labels: duplicate
