### ISSUE TITLE
Chat broken

### ISSUE THREAD

**Issue by aule10** [night/BetterTTV#1808] opened 2016-12-02 08:26 UTC
The chat is really broken. first i had problem getting the stream to get bigger, disabled BTTV clicked the chat away, enabled it, the stream is now big, Now i cant get the chat back.

**Comment by aule10** [comment] 2016-12-02 08:49
Even more problems have come up. When i try go fullscreen the window is the same size with a big black box around it.

**Comment by EhsanKia** [comment] 2016-12-03 20:24
Should be fixed now.

**Closed by EhsanKia** 2016-12-03 20:24 UTC

**Comment by night** [comment] 2016-12-03 23:23
duplicate of #1808
