### ISSUE TITLE
disable host mode

### ISSUE THREAD

**Issue by martking26** [night/BetterTTV#3275] opened 2018-09-23 20:46 UTC
its STILL broken for me, its now hosting AND disabling host mode at the same time. its like watching twitch, having a damn seizure!!!! PLS FIX THIS SHIT. i already completely reset my Chrome and such so its not that

**Comment by night** [comment] 2018-09-29 20:53
duplicate of #3247

**Closed by night** 2018-09-29 20:53 UTC
Labels: duplicate
