### ISSUE TITLE
new bttv suggestion 

### ISSUE THREAD

**Issue by simmonsandrew00** [night/BetterTTV#1807] opened 2016-12-02 07:06 UTC
I suggest a way to disable the pinned bit messages, without disabling all bits. me and my friends enjoy using bits but the pinned bit messaged are annoying to have to dismiss everytime and sometimes it doesnt even work. Just a thought though.

**Comment by nassimm** [comment] 2016-12-02 10:18
small tip for this one, you can just right click it and block it with your adblocker.

**Comment by night** [comment] 2016-12-03 23:21
duplicate of #1746

**Closed by night** 2016-12-03 23:22 UTC
Labels: duplicate
