### ISSUE TITLE
Auto Expand Followed Channels List/Hide Recommended Channels

### ISSUE THREAD

**Issue by Antonymity** [night/betterttv#4028] opened 2020-07-10 01:04 UTC
I recently cleared browser cache and cookies on Twitch (Chrome Version 84.0.4147.85). I saw some BTTV options were thus reset, and began setting them as I had them. Many came back fine - alternate chat line colors and host button being a couple - but the Auto Expand Followed Channels List and Hide Recommended Channels options no longer seem to be working. I recall the followed channels list functioned by expanding the followed channels list upon a mouseover of the left side, and it auto closing on mouseout. It doesn't do that now. Recommended channels still show as well.

What I did was:
Click my profile picture
Select 'BetterTTV Settings'
Turn the respective options On

I even removed and re-added the extension but the behavior remains broken.

**Comment by fortez** [comment] 2020-07-10 13:12
Faced this issue too. I've done the same thing before, clear my cache and cookies and now auto expand don't work anymore. same goes to hide offline followed channel feature.

**Comment by night** [comment] 2020-07-12 19:24
duplicate of #4023

**Closed by night** 2020-07-12 19:24 UTC
Labels: duplicate
