### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by istdaslol** [night/BetterTTV#628] opened 2015-08-05 18:41 UTC
show the stream uptime under the chanel. Show the first 5 live following channels when yoou move your mouse to the "follow" Button.

**Comment by night** [comment] 2015-08-05 19:36
> show the stream uptime under the chanel.

Channel pages are too cluttered as is. Type "/uptime" in chat to see stream uptime instead.

> Show the first 5 live following channels when yoou move your mouse to the "follow" Button.

Duplicate of #62

**Closed by night** 2015-08-05 19:36 UTC
Labels: invalid
