### ISSUE TITLE
Feature request: "Event: XYZ" at running streams

### ISSUE THREAD

**Issue by Daisenki** [night/BetterTTV#3278] opened 2018-09-25 22:44 UTC
Some Streams think it seems to be a good idea to display at running stream on top of the stream a blue bar with a calendar icon and "Event: XYZ" (current game). 

The top bar is only visible at normal mode, it's not visible at theatre mode or fullscreen mode. 

Is here a way to block that annoying top bar at the running stream? At my example here from the Streamer GGGabLive the "Event: Dino Crisis 2" linked to https://www.twitch.tv/events/SE-F2NBOSmeh0P-nEHsA9w

I ask the Streamer about the annoying top bar, but my question was ignored. 

![stream event](https://user-images.githubusercontent.com/22057956/46047376-79192d80-c114-11e8-8354-f4f5b5dcae33.JPG)

![stream event2](https://user-images.githubusercontent.com/22057956/46047472-c7c6c780-c114-11e8-8ef3-73d8b381060f.JPG)

**Comment by night** [comment] 2018-09-30 18:40
duplicate of #3251

**Closed by night** 2018-09-30 18:40 UTC
Labels: duplicate
