### ISSUE TITLE
Disable Host Mode  doesn't work

### ISSUE THREAD

**Issue by allkom** [night/BetterTTV#1666] opened 2016-10-18 09:47 UTC
Since the new Twitch Design update, the Disable Host Mode - option doesn't work anymore.
Also tried to turn it off and on in the BTTV Settings Menu, but the Host Mode is still activated.

Really annoying because a lot of Twitch Streamers are posting the Host command and the Broadcast stops immediately, instead of streaming the stuff that happened between 'Users Live' and 'Streamers Live' (the delay thing)

**Comment by night** [comment] 2016-10-21 02:55
duplicate of #1621

**Closed by night** 2016-10-21 02:55 UTC
Labels: duplicate
