### ISSUE TITLE
i cant see the bttv emotes tab

### ISSUE THREAD

**Issue by TheMink** [night/BetterTTV#1589] opened 2016-10-01 17:07 UTC
i recently have not been able to see or use my bttv emotes tab in the chat ui. i have tried disabling and reenabling the browser extension and importing a backup of my settings

**Comment by Tester798** [comment] 2016-10-01 17:09
Yes, just opened twitch and I see bttv emotes button is not available anymore.

**Comment by fuwafoowa** [comment] 2016-10-01 17:39
Exactly the same for me.

**Comment by night** [comment] 2016-10-01 18:21
duplicate of #1580

**Closed by night** 2016-10-01 18:21 UTC
Labels: duplicate
