### ISSUE TITLE
BTTV not working with chat in Safari (macOS)

### ISSUE THREAD

**Issue by rmzy** [night/BetterTTV#2136] opened 2017-03-17 19:17 UTC
Seems to be the same problem as the Firefox issue previously posted here: https://github.com/night/BetterTTV/issues/2112

BTTV doesn't work when loading the standalone chat window. It does load the emote menu most of the time, but the emotes themselves aren't rendered in the chat.

The extra options in the cogwheel under the chat field doesn't load at all. I've managed to get it to load after refreshing many, many times. Note, I've disabled all adblockers and the like to no avail.

![screen shot 2017-03-17 at 12 16 22 pm](https://cloud.githubusercontent.com/assets/4682630/24059254/a58083de-0b0b-11e7-886b-20f4c475851d.png)

**Comment by rmzy** [comment] 2017-03-17 21:29
This might be a flook, but I've noticed that when there are many BTTV emotes going on in the chat and I refresh the page, BTTV will load successfully. 

I noticed this when I was in a larger stream and people were spamming LUL. Other smaller chats, when there were one or two emotes in chat didn't help load BTTV for some reason.

**Comment by night** [comment] 2017-03-20 05:43
duplicate of #1898

**Closed by night** 2017-03-20 05:43 UTC
Labels: duplicate

**Comment by isp13** [comment] 2019-05-24 21:08
https://github.com/isp13/Safari_BetterTTV
