### ISSUE TITLE
Can no longer swap the "followed channels" side-nav to the right side of screen.

### ISSUE THREAD

**Issue by SereneSl0th** [night/betterttv#5561] opened 2022-08-05 00:09 UTC
Essentially title, used to be able to swap the chat and the "followed channels" to either side of the screen, the chat portion still works, but the "followed channels" / "recommended channels" nav bar is forever stuck on the left side of the page.

**Comment by night** [comment] 2022-08-05 00:12
duplicate of #5560

**Closed by night** 2022-08-05 00:12 UTC
Labels: duplicate
