### ISSUE TITLE
BTTV Chat error

### ISSUE THREAD

**Issue by otterinaonesie** [night/BetterTTV#2011] opened 2017-01-28 03:53 UTC
whenever I try and join a channel, I get the following error message "BetterTTV encountered an error reading chat. The developer has been sent a log of this action. Please try clearing your cookies and cache." Tried clearing my cache, cookies, browser history and re importing my bttv settings but nothing has worked

**Comment by adamk33n3r** [comment] 2017-01-28 03:58
Getting the same thing. Noticed this error in the dev console.
```
XMLHttpRequest cannot load https://nightdev.com/betterttv/errors/?obj=%7B%22stack%22%3A%22TypeError%3A…2message%22%3A%22Cannot%20read%20property%20%27length%27%20of%20null%22%7D. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.twitch.tv' is therefore not allowed access.
```

**Comment by adamk33n3r** [comment] 2017-01-28 03:58
Going to that URL shows
```
Failed to connect to MySQL: (2002) No such file or directory
```

**Comment by adamk33n3r** [comment] 2017-01-28 04:00
#2010 #2009 #2008 #2007 #2006 #2005 are all related

**Comment by night** [comment] 2017-01-28 07:25
duplicate of #2005

**Closed by night** 2017-01-28 07:25 UTC
Labels: duplicate
