### ISSUE TITLE
Show Deleted Messages 

### ISSUE THREAD

**Issue by LaKvart** [night/BetterTTV#3250] opened 2018-08-31 18:05 UTC
Show Deleted Messages — Turn this on to change <message deleted> back to users' messages.
This function dont work anymore 

![default](https://user-images.githubusercontent.com/42875450/44928781-9a7b3980-ad61-11e8-88af-089930dd7299.png)

**Comment by Nareese** [comment] 2018-08-31 18:53
duplicate of #3233

**Closed** 2018-09-01 18:38 UTC
Labels: duplicate
