### ISSUE TITLE
White bar below the stream screen

### ISSUE THREAD

**Issue by Bacura82** [night/BetterTTV#2371] opened 2017-04-28 22:38 UTC
Im am using the DarkenTTv skin for twitch which worked fine till today. I dont know why but now I have a small white bar beneath the stream which is really distracting with everything else being grey.
![7456107a61924b7d0311e451423625af](https://cloud.githubusercontent.com/assets/28166833/25549765/1c3784d0-2c74-11e7-9d70-b61af43249ac.png)

**Comment by LouieGreen** [comment] 2017-04-28 22:56
Duplicate of #2365, #2366 and #2367 (half of the same issues reported)

**Closed** 2017-04-28 23:37 UTC
