### ISSUE TITLE
Permit Key bind

### ISSUE THREAD

**Issue by Heep123** [night/BetterTTV#450] opened 2015-06-01 19:17 UTC
Would it be possible if there was a key bind for the permit button on the mod cards (maybe L) in a similar way to the [P]urge, [T]imeout and [B]an key binds?

**Comment by thinkpad4** [comment] 2015-06-01 20:39
I second this

**Comment by Maxhype** [comment] 2015-06-01 21:22
+1.

**Comment by night** [comment] 2015-06-01 21:49
Duplicate of https://github.com/night/BetterTTV/issues/74

**Closed by night** 2015-06-01 21:49 UTC
Labels: duplicate
