### ISSUE TITLE
<message deleted> message!

### ISSUE THREAD

**Issue by KsKings** [night/BetterTTV#2634] opened 2017-08-19 14:22 UTC
since a few days i cant see deleted messages it only shows " <message deleted> " and i have the option to show them on and it worked fine in the past! since im moderator in some chanels it would be great to fix the problem or help me with that 

![bttv](https://user-images.githubusercontent.com/31161607/29487498-65b7232a-84fa-11e7-9fff-a8e2a75dfe4d.jpg)

**Comment by night** [comment] 2017-08-23 04:30
duplicate of #2595

**Closed by night** 2017-08-23 04:30 UTC
Labels: duplicate
