### ISSUE TITLE
[Feature Request] - Emote Spam Filter

### ISSUE THREAD

**Issue by Twitch12** [night/BetterTTV#1389] opened 2016-07-20 07:22 UTC
I need a feature that blocks messages that contain only emotes. These messages are usually useless and flood the chat window. I don't want to block emotes if they are accompanied by text, just messages with only emotes. I would also appreciate a way to filter messages on a case sensitive basis, because sometimes copy-pastas exclusively contain a specific case that I want to block while a typical chat message that isn't spam will also contain the word or phrase but in different format.

**Comment by EhsanKia** [comment] 2016-07-20 15:59
I think `/localascii` and `/localasciioff` is what you're looking for.

**Comment by Twitch12** [comment] 2016-07-20 18:40
I'm not sure exactly what that does, but it's not what I'm looking for. The main thing I want to block are messages that contain 1-3 emotes and no text.

**Comment by Twitch12** [comment] 2016-07-21 01:21
For clarification, I've circled what I want to remove in this photo.
![capture](https://cloud.githubusercontent.com/assets/20552837/17008494/1595d580-4eaf-11e6-8aca-077f01190bd4.PNG)

**Comment by night** [comment] 2016-07-22 09:04
duplicate of #144

**Closed by night** 2016-07-22 09:04 UTC
Labels: duplicate
