### ISSUE TITLE
theater mode not changing the color of the chat

### ISSUE THREAD

**Issue by gemcosta** [night/BetterTTV#1221] opened 2016-05-31 20:41 UTC
Hi guys,

Thanks for making BTTV. Recentlty I've come across an issue that's been puzzling me. I like to watch Twitch in Theater Mode - so much so that I made it the default view using your settings.

However recently the chat background is not being changed to the dark theme. Everything else changes are normal. Any idea why this would be? Theater mode works fine in incognito mode without bttv.

**Comment by EhsanKia** [comment] 2016-05-31 21:15
Duplicate of #1220

**Closed** 2016-05-31 21:15 UTC
Labels: duplicate
