### ISSUE TITLE
chat

### ISSUE THREAD

**Issue by JillianMPlayz** [night/betterttv#3865] opened 2020-05-12 21:14 UTC
Hello, I noticed recently that the chat disappears when using the option to have chat on the left side of the player. I found a fix where I just had to disable it but I wanted it back so I changed it to be on the left again and now the only fix is to get rid of the extension. Because I have the left side chat disabled but its acting like is on. I would still love to use the left side chat. so if you could find a fix that would be much appreciative!

**Comment by Nareese** [comment] 2020-05-12 21:26
duplicate of #3852

**Closed** 2020-05-13 07:08 UTC
Labels: duplicate
