### ISSUE TITLE
Can't see BTTV images even on Betterttv.com

### ISSUE THREAD

**Issue by nucularspider** [night/betterttv#5869] opened 2023-01-18 20:13 UTC
**Describe the bug**
Can't see emotes even on Betterttv.com

**To Reproduce**
1. Go to https://betterttv.com/emotes/top
2. Don't see emotes

**Expected behavior**
At least see emotes on Betterttv.com when they stop working on twitch

**Screenshots**
<img width="1095" alt="Screen Shot 2023-01-15 at 10 45 22 PM" src="https://user-images.githubusercontent.com/123021178/213284698-e607ab08-ce2c-4bc2-83d7-c46362504234.png">

**Desktop (please complete the following information):**
- OS: macOS Big Sur
- Browser: Firefox
- Version: BetterTTV 7.5.0, Firefox 109.0

**Additional context**
I've tried turning off all add-ons, turning off all security & privacy settings, clearing cache/cookies, etc. Images/gifs work fine on other websites.

**Comment by nucularspider** [comment] 2023-01-18 20:29
It looks like this: 
<img width="841" alt="Screen Shot 2023-01-18 at 3 29 36 PM" src="https://user-images.githubusercontent.com/123021178/213287974-0e821fc7-f8f0-4799-b077-288db4ddba34.png">

**Comment by nucularspider** [comment] 2023-01-18 20:31
it looks like this: 
<img width="841" alt="Screen Shot 2023-01-18 at 3 29 36 PM" src="https://user-images.githubusercontent.com/123021178/213288292-7971837b-dace-4904-908f-178a51e4c77f.png">

**Comment by nucularspider** [comment] 2023-01-18 21:05
It downloads it to my desktop. I can't get it to open in a browser tab.

**Comment by nucularspider** [comment] 2023-01-18 21:20
Thank you! I have figured it out now since I can't view that file. Somehow Firefox had disabled all .webp

**Comment by night** [comment] 2023-01-18 21:23
ah interesting! will keep that in mind if there are other users that have a similar experience. gonna close this since the issue is resolved.

**Closed by night** 2023-01-18 21:23 UTC
Labels: bug
