### ISSUE TITLE
Twitch Desktop App Implementation

### ISSUE THREAD

**Issue by xIGBClutchIx** [night/BetterTTV#3421] opened 2019-03-26 21:19 UTC
So based on #2613 being locked down a bit and since then Twitch has updated their app. It seems BTTV pretty much works straight up with the desktop app now. 

I did a little modification to the userscript and got it working easily when using webview devtools (F12) with
```
var script = document.createElement('script');
script.type = 'text/javascript';
script.src = 'https://cdn.betterttv.net/betterttv.js';
var head = document.getElementsByTagName('head')[0];
if (head) head.appendChild(script);
```

All that we need is a proper injection into there so that the script runs every time the app is refreshed/updated/reopened. I did a quick look myself and could only get it to inject into the parent which will not work properly.

**Comment by xIGBClutchIx** [comment] 2019-03-27 03:48
Another issue I have come across since trying to figure this out. Twitch likes to force updating pretty aggressively. Tried personally injecting into asar and on webcontent and Twitch just kept updating over it.

**Comment by night** [comment] 2019-04-22 07:58
duplicate of #2613

**Closed by night** 2019-04-22 07:58 UTC
Labels: duplicate

**Comment by Ethos-x** [comment] 2019-07-04 06:29
Kinda sad that almost 2 years later, we still have no word from them about the development of bttv for the desktop app. So many people want this. Guess ill have to go back to using chrome and 90% of my RAM.
