### ISSUE TITLE
show deleted message not working 7.2.38

### ISSUE THREAD

**Issue by Daisenki** [night/BetterTTV#3243] opened 2018-08-30 08:58 UTC
The Version 7.2.38 does not show the deleted messages in chat, it only shows "<message deleted>", Show Deleted Messages is ON

Firefox 61.0.2

**Comment by fh-money** [comment] 2018-08-30 12:17
Tbh i thought it was just me

**Comment by Nareese** [comment] 2018-08-30 13:55
duplicate of #3233

**Closed** 2018-09-01 18:38 UTC
Labels: duplicate
