### ISSUE TITLE
Hide new/re subscribers from being highlighted.

### ISSUE THREAD

**Issue by theundeadcpt** [night/BetterTTV#1343] opened 2016-07-02 23:52 UTC
While I think this is a cool feature if you're streamer. I am not and find it a bit of an annoyance. A simple  toggle is all I ask.

http://imgur.com/CO8N9TU 

Sorry if this was posted already, I looked and didn't see it so here is my request.

**Comment by Slikrick** [comment] 2016-07-04 02:59
Duplicate of #1335 You should use the solution posted there.

**Closed** 2016-07-05 06:34 UTC
Labels: duplicate
