### ISSUE TITLE
BTTV Emotes not working

### ISSUE THREAD

**Issue by Synergii** [night/BetterTTV#1869] opened 2016-12-13 03:00 UTC
Emotes such as LUL or FeelsBadMan are not showing in chat. Only the letters show but not the actual image. 
Does anyone know how to fix this problem?

**Comment by thinkpad4** [comment] 2016-12-13 03:08
Turn off Disable Channel Header temporally. That seems to fix it

**Comment by Synergii** [comment] 2016-12-13 03:12
@thinkpad4 That workerd, never would have thought of that. Thank you so much!

**Comment by thinkpad4** [comment] 2016-12-13 03:12
np, Twitch pushed some changes today that broke things

**Comment by Synergii** [comment] 2016-12-13 03:14
Hopefully they come up with a fix soon

**Comment by thinkpad4** [comment] 2016-12-13 03:17
The Nightdevs are working on it, no worries

**Comment by EhsanKia** [comment] 2016-12-13 03:41
Duplicate of #1866

**Closed by EhsanKia** 2016-12-13 03:41 UTC
Labels: duplicate
