### ISSUE TITLE
Movement issue with mod card

### ISSUE THREAD

**Issue by AlcaDesign** [night/BetterTTV#2323] opened 2017-04-25 00:11 UTC
![](https://i.gyazo.com/586dc6243277e8530e1043fc3bd96c8f.gif) [MP4](https://i.gyazo.com/586dc6243277e8530e1043fc3bd96c8f.mp4)

Moving the mod card gives it a gigantic white border and right-aligns it to the window. It only follows the Y-axis of my mouse relative to where I clicked and then appears on the left of the screen when released at that Y position and always at `left: 80px`.

This has been an issue for a few days and I have yet to see another issue so I don't know if this is happening to anyone else.

**Comment by night** [comment] 2017-04-25 01:16
duplicate of #2299

**Closed by night** 2017-04-25 01:16 UTC
Labels: duplicate
