### ISSUE TITLE
Recommended channels/Featured channels not going away

### ISSUE THREAD

**Issue by MrEdens** [night/betterttv#5233] opened 2022-02-25 13:32 UTC
Basically i unchecked show Recommended and Featured channels, but they still remain on the left sidebar

**Comment by Nareese** [comment] 2022-02-25 14:12
If you are seeing this issue with the left sidebar collapsed, then this is a known issue (#4183) that does not have an easy fix (which is why it hasn't been fixed).  I am not able to reproduce any issues with these components when the sidebar is expanded.

**Comment by blehdadsfa** [comment] 2022-02-25 14:58
I have an easy fix.

Expand the sidebar.  Reload the page.  Recommendations go away.  Minimize the sidebar.

**Comment by Nareese** [comment] 2022-02-25 16:26
That's not really a "fix", since it doesn't stick, it's more of a workaround, but yes, you can do that.

**Comment by blehdadsfa** [comment] 2022-02-25 19:59
yeah that why I wrote "fix" within quotations.

you just gotta expand the bar when you're searching, close it when you're on the page you want.  It's still better than having recommendations you don't want there.

**Closed** 2022-03-27 19:26 UTC
Labels: duplicate
