### ISSUE TITLE
Suggestion: Pronoun Badges

### ISSUE THREAD

**Issue by c00bmaster** [night/betterttv#5649] opened 2022-09-28 16:09 UTC
so there is already an extension for pronoun badges on twitch, however there are a couple of issues

1. it seems like it tends to stop working pretty frequently

2. it's such a niche extension that in the end not many people use it

the second issue would likely be lessened quite significantly if bttv were to add this functionailty to their extension, as the majority of desktop users who use twitch on a regular basis use bttv.

**Comment by night** [comment] 2022-10-01 02:00
duplicate of #4398

**Closed by night** 2022-10-01 02:00 UTC
Labels: duplicate
