### ISSUE TITLE
BTTV settings do not appear in cog menu when certain ads play

### ISSUE THREAD

**Issue by gibbed** [night/betterttv#5697] opened 2022-10-23 06:15 UTC
7.4.40

I am not running any extensions on top of BTTV.

This seems to be ad specific. When certain ads play a third-party JS script gets loaded which breaks BTTV adding settings to the cog menu.

I don't know if this issue is within scope for BTTV or not, but it's annoying when BTTV settings aren't available. 😅

```
betterttv.js:118 12:57:25 AM [ERROR] Uncaught error. TypeError: Cannot read properties of undefined (reading 'activeElement')
    at condition (dv-measurements3094.js:1:429077)
    at e.handleElementEvent (dv-measurements3094.js:1:429731)
    at o (betterttv.js:118:967056)
```

When `dv-measurements3094.js` is loaded, whenever the cog menu is opened, this error is output to the console.

`dv-measurements3094.js` seems to be third-party tracking/ad code: `https://cdn.doubleverify.com/dv-measurements3094.js`

**Comment by night** [comment] 2022-10-24 00:43
Thanks for the report. Does this affect both places we load the settings button? There should be a settings button in the user dropdown and in the chat settings menu. Which menu is it missing from?

**Comment by gibbed** [comment] 2022-10-24 01:44
This was specifically the chat cog, I wasn't aware of an item being added to the user dropdown. I'll see if I can reproduce and check the user dropdown as well.

**Comment by night** [comment] 2022-12-24 05:13
This appears to be a duplicate of #5568, since chat input re-renders are the cause.

**Closed by night** 2022-12-24 05:13 UTC
Labels: duplicate
