### ISSUE TITLE
Twitch showing offline channel, even when option is unchecked

### ISSUE THREAD

**Issue by matt-arena** [night/betterttv#6856] opened 2024-06-03 23:29 UTC
### Describe the bug

I noticed the other day that there were offline channels in my "Followed Channels" list, even though I don't have that option checked. I am on Opera GX version 109.0.5097.108. I tried checking the box, refresh, then unchecking the box, and refreshing. The only thing I haven't tried yet is uninstall and reinstall.

### Steps to reproduce

1. Go to twitch.tv
2. Look at the "followed channels" list
3. Scroll to the bottom
4. There are still offline channels listed even if the option is unchecked in BTTV

### Expected behavior

I expected no offline channels to show since that option isn't checked in BTTV

### Screenshots

![6c30db38ae9e326127e2c1eb4c537dd3](https://github.com/night/betterttv/assets/92208516/7baa0d5e-46ea-4530-8d9e-25fa65b6e652)

### Device information

-Device: Desktop PC
-OS: Windows 11
-Browser: Opera GX
-Version: 109.0.5097.108

**Comment by SaiyanOfDarkness** [comment] 2024-06-04 06:39
Just to add on, this also goes for hiding recommended section too.

Section should be `##div.side-nav-section.dcyYPL.Layout-sc-1xcs6mc-0:nth-of-type(3)`

and (Streamer) Viewers Also Watch section is `##div.side-nav-section.dcyYPL.Layout-sc-1xcs6mc-0:nth-of-type(4)`

**Comment by night** [comment] 2024-06-04 13:28
duplicate of #6837

this is already fixed in 7.6.2

**Closed by night** 2024-06-04 13:28 UTC
Labels: bug
