### ISSUE TITLE
Option for the chat to be on  the left side of the player.

### ISSUE THREAD

**Issue by Fatpala** [night/BetterTTV#418] opened 2015-05-14 23:34 UTC
Would like to have an option where the chat is on the left side of the player, or if there is anyway to make the chat movable the chat to the left side by dragging it.
It's not often i watch a stream on my main monitor and the chat is always far to the right on my second monitor which makes it really hard to see.

I know i could just popout chat but it takes effort Kappa

//Fatpala

**Comment by night** [comment] 2015-05-16 20:12
Duplicate of #202

**Closed by night** 2015-05-16 20:12 UTC
Labels: duplicate
