### ISSUE TITLE
BTTV emotes not showing in chat

### ISSUE THREAD

**Issue by birchtreeleaf** [night/betterttv#6332] opened 2023-08-19 19:30 UTC
Hi, I don't know what any of this means but my bttv hasn't worked in a while. I got it to work for a day about a week ago when I logged out of twitch, couldn't log back in unless I was on my phone wifi, reset my routers IP address, and then relogged back in. Then it worked until the next day where it no longer did. I copied this down from the chrome console. From my untrained eyes, firefox is giving the same message when I try there. Anyone know how I can get it working again? 

Screenshots
![image](https://github.com/night/betterttv/assets/31049663/56e4b187-f5b1-443b-bdf0-33dc7691a0f8)
Emotes such as Copium and ICANT not showing

OS: Windows 10 Home
Browser: Chrome
Version 116.0.5845.97

vendor-4830d531d9d3cd45393f.js:1 Download the Apollo DevTools for a better development experience: https://chrome.google.com/webstore/detail/apollo-client-developer-t/jdkknkkbebbapilgoeccciglkfbmbnfm
amazon-ivs-wasmworker.min-a1df67e7f4158d75ce9d.js:1 Amazon IVS Player SDK 1.21.0-twitch.1-rc.2
amazon-ivs-wasmworker.min-a1df67e7f4158d75ce9d.js:1 Amazon IVS Player SDK 1.21.0-twitch.1-rc.2
amazon-ivs-wasmworker.min-a1df67e7f4158d75ce9d.js:1 MSE in workers enabled
betterttv.js:94 [GraphQL] One or more GraphQL errors were detected on request 01H87JATTRZAZAHSK3BSY7XM9W. ChatRoomBanStatus: service error Array(1)0: request: extensions: persistedQuery: sha256Hash: "319f2a9a3ac7ddecd7925944416c14b818b65676ab69da604460b68938d22bea"version: 1[[Prototype]]: Objectconstructor: ƒ Object()assign: ƒ assign()create: ƒ create()defineProperties: ƒ defineProperties()defineProperty: ƒ defineProperty()entries: ƒ entries()freeze: ƒ freeze()fromEntries: ƒ fromEntries()getOwnPropertyDescriptor: ƒ getOwnPropertyDescriptor()getOwnPropertyDescriptors: ƒ getOwnPropertyDescriptors()getOwnPropertyNames: ƒ getOwnPropertyNames()getOwnPropertySymbols: ƒ getOwnPropertySymbols()getPrototypeOf: ƒ getPrototypeOf()hasOwn: ƒ hasOwn()is: ƒ is()isExtensible: ƒ isExtensible()isFrozen: ƒ isFrozen()isSealed: ƒ isSealed()keys: ƒ keys()length: 1name: "Object"preventExtensions: ƒ preventExtensions()prototype: {constructor: ƒ, __defineGetter__: ƒ, __defineSetter__: ƒ, hasOwnProperty: ƒ, __lookupGetter__: ƒ, …}seal: ƒ seal()setPrototypeOf: ƒ setPrototypeOf()values: ƒ values()arguments: (...)caller: (...)[[Prototype]]: ƒ ()[[Scopes]]: Scopes[0]hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()__proto__: (...)get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()[[Prototype]]: ObjectoperationName: "ChatRoomBanStatus"variables: {targetUserID: '156171208', channelID: ''}[[Prototype]]: Objectresponse: {errors: Array(1), data: {…}, extensions: {…}}data: {chatRoomBanStatus: null, targetUser: {…}}errors: [{…}]extensions: {durationMilliseconds: 23, operationName: 'ChatRoomBanStatus', requestID: '01H87JATTRZAZAHSK3BSY7XM9W'}[[Prototype]]: Object[[Prototype]]: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()__proto__: (...)get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()length: 1[[Prototype]]: Array(0)at: ƒ at()concat: ƒ concat()constructor: ƒ Array()copyWithin: ƒ copyWithin()entries: ƒ entries()every: ƒ every()fill: ƒ fill()filter: ƒ filter()find: ƒ find()findIndex: ƒ findIndex()findLast: ƒ findLast()findLastIndex: ƒ findLastIndex()flat: ƒ flat()flatMap: ƒ flatMap()forEach: ƒ forEach()includes: ƒ includes()indexOf: ƒ indexOf()join: ƒ join()keys: ƒ keys()lastIndexOf: ƒ lastIndexOf()length: 0map: ƒ map()pop: ƒ pop()push: ƒ push()reduce: ƒ reduce()reduceRight: ƒ reduceRight()reverse: ƒ reverse()shift: ƒ shift()slice: ƒ slice()some: ƒ some()sort: ƒ sort()splice: ƒ splice()toLocaleString: ƒ toLocaleString()toReversed: ƒ toReversed()toSorted: ƒ toSorted()toSpliced: ƒ toSpliced()toString: ƒ toString()unshift: ƒ unshift()values: ƒ values()with: ƒ with()Symbol(Symbol.iterator): ƒ values()Symbol(Symbol.unscopables): {at: true, copyWithin: true, entries: true, fill: true, find: true, …}[[Prototype]]: Object
(anonymous) @ betterttv.js:94
DevTools failed to load source map: Could not load content for https://c.amazon-adsystem.com/aax2/publisher-polyfilled.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by DaveYognaught** [comment] 2023-08-28 13:31
Do you use a VPN? 

I'm trying to debug my own issues at the moment and both BTTV and FFZ use CloudFlare and it's fucking shit with VPNs. They've both or CloudFlare has on their own initiative went full nazi on VPNs recently.

**Comment by birchtreeleaf** [comment] 2023-08-29 05:06
As far as I know I am not using a vpn. I just looked and I see no evidence of using one. I wish i was and that that was the problem

**Comment by night** [comment] 2023-09-06 17:22
duplicate of #6305

**Closed by night** 2023-09-06 17:22 UTC
Labels: duplicate
