### ISSUE TITLE
Split Dark Mode

### ISSUE THREAD

**Issue by RichWind** [night/BetterTTV#1912] opened 2016-12-23 08:19 UTC
I want the Dark Mode button in the chatbox to make only the chat black, and the Dark Mode button in BTTV settings to make only the twitch tv background black.

**Comment by Stoupedog** [comment] 2016-12-23 20:45
Duplicate of https://github.com/night/BetterTTV/issues/916

**Closed** 2016-12-23 22:49 UTC
Labels: duplicate
