### ISSUE TITLE
Hide offline channels not working.

### ISSUE THREAD

**Issue by bwamatt** [night/betterttv#3914] opened 2020-05-25 02:33 UTC
![image](https://user-images.githubusercontent.com/65880072/82772859-7cdfe480-9e0e-11ea-95c6-288177a6ece5.png)
Not sure why this happened, it started after the new twitch UI update.

**Comment by night** [comment] 2020-05-26 09:49
duplicate of #3868

**Closed by night** 2020-05-26 09:49 UTC
Labels: duplicate
