### ISSUE TITLE
Option to not add comma after tab-completion of username

### ISSUE THREAD

**Issue by dfoverdx** [night/BetterTTV#1960] opened 2017-01-10 23:09 UTC
Most of the time when I tab-complete a username, I don't want a comma automatically appended.  I can't seem to find an option to disable this.

**Comment by Stoupedog** [comment] 2017-01-11 02:22
Duplicate of https://github.com/night/BetterTTV/issues/499

**Closed** 2017-01-11 08:06 UTC
Labels: duplicate
