### ISSUE TITLE
Clear chat

### ISSUE THREAD

**Issue by PootisPowah** [night/BetterTTV#697] opened 2015-09-09 12:17 UTC
![capture](https://cloud.githubusercontent.com/assets/14198424/9761544/0b79f7c6-5706-11e5-8239-8825a95df185.PNG)
I am a moderator in my friends stream. Sometimes i like to test some things with the emotes. Then i want to clear them/clear chat, but BetterTTV is preventing it. Can you guys make it so it doesn't do that?

Thanks in advance :)

**Comment by night** [comment] 2015-09-09 13:29
Duplicate of #524

**Closed by night** 2015-09-09 13:29 UTC
