### ISSUE TITLE
Hide Offline Followed Channels

### ISSUE THREAD

**Issue by JDouble2001** [night/betterttv#3892] opened 2020-05-15 18:57 UTC
The hide offline followed channels does not work. Its been about 2 weeks  since it has last worked.

**Comment by Darxide23** [comment] 2020-05-17 02:10
Already fixed and waiting to go live. https://github.com/night/betterttv/pull/3842

**Comment by night** [comment] 2020-05-18 22:48
duplicate of #3868

**Closed by night** 2020-05-18 22:48 UTC
Labels: duplicate
