### ISSUE TITLE
Highlight messages from followed streamers in chat

### ISSUE THREAD

**Issue by WeyoX** [night/BetterTTV#240] opened 2015-02-19 21:06 UTC
Hi, I think it would be cool if you can see a "highlighted" message in chat when someone you follow or someone you have marked somehow is writing. Example: If cro_ is writing in summit1g's chat it will light up like when someone writes your name. Not a big deal but would help to find the "friends" message!
Thanks for making BTTV the way it is!

**Comment by night** [comment] 2015-02-24 07:22
You can already set specific users by wrapping their name in parentheses.. ```(night)```

As for followed streamers, I'm not sure we would add this. I'll mark it an enhancement anyways.

**Comment by night** [comment] 2015-04-30 13:12
Duplicate of https://github.com/night/BetterTTV/issues/94

**Closed by night** 2015-04-30 13:12 UTC
Labels: duplicate
