### ISSUE TITLE
Question about a short to long url option

### ISSUE THREAD

**Issue by Outsanity** [night/BetterTTV#509] opened 2015-06-21 11:26 UTC
Is it possible to have an option/setting that would allow any shortened url in the chats to get changed into it's long url via longurl.org?

**Comment by night** [comment] 2015-06-21 18:29
Duplicate of https://github.com/night/BetterTTV/issues/88

In progress with PR #501, but it needs some work.

**Closed by night** 2015-06-21 18:29 UTC
Labels: duplicate
