### ISSUE TITLE
Left chat is broken

### ISSUE THREAD

**Issue by WillLBegin** [night/betterttv#7077] opened 2024-10-07 12:40 UTC
### Describe the bug

Left chat does not swap followed channel to the right

### Steps to reproduce

1. Click left chat.
2. Open your eyes

### Expected behavior

Left chat, right followed channels

### Screenshots

![image](https://github.com/user-attachments/assets/58f3696b-56fc-4b2f-8c92-f65ddfd83760)

### Device information

Firefox

### BetterTTV Version

7.6.6

### Version Check

- [X] I have checked that I'm using the newest version of BetterTTV available.

**Comment by tcoops16** [comment] 2024-10-09 00:10
I'm having the same issue on Chrome. The bug isn't exclusive to the Firefox browser.

A temporary fix until it's resolved in BTTV is to install the 7TV extension and then adjust some settings there.
_Appearance -> Interface -> Sidebar Expand on Hover_
Tick this option On.

The sidebar is hidden and the chat window is now to the complete left of your browser window again.
If you collapse the chat, you can hover on the left side to bring up your sidebar.

Downside: You will not have the sidebar on your display the whole time.

**Comment by night** [comment] 2024-10-09 17:15
I'm not able to reproduce any issues with Left Side Chat. It's likely you have another extension installed that conflicts with BetterTTV's Left Side Chat feature. Try disabling all other browser extensions and see if problems persist. If not, you can turn them on one-by-one until you locate the extension causing problems.

**Closed by night** 2024-10-09 17:15 UTC
Labels: bug

**Comment by SteveEcke** [comment] 2024-10-11 12:38
I have the same issue. It started happening after Twitch's last update. Left chat option just moves the chat next to the followers.
Browser: 131.0.2 (64-Bit)
Addons on the side: ublock origin, 7tv

**Comment by dclstn** [comment] 2024-10-11 13:05
7TV's extension rerenders the entire chat, which can prompt undefined behaviour when interacting with other extensions. @SteveEcke can you confirm this by trying left-side chat with 7TV temporarily disabled?

**Comment by WillLBegin** [comment] 2024-10-11 13:09
I can confirm 7TV is the issue, disabling it fixed it for me. I doubt 7TV will have any fix for this, because they don't have a left chat option. So what, are we gonna have to abandon left chat if we want 7TV?

**Comment by SteveEcke** [comment] 2024-10-11 14:35
> 7TV's extension rerenders the entire chat, which can prompt undefined behaviour when interacting with other extensions. @SteveEcke can you confirm this by trying left-side chat with 7TV temporarily disabled?

Confirmed. After turning off 7TV, the issue disappears.

**Comment by dclstn** [comment] 2024-10-11 14:55
> I can confirm 7TV is the issue, disabling it fixed it for me. I doubt 7TV will have any fix for this, because they don't have a left chat option. So what, are we gonna have to abandon left chat if we want 7TV?

A fix has been comitted https://github.com/night/betterttv/commit/6dce551d71d69dbd86f9ed5cf220f6ff1df080b3, to accomodate 7TV's chat container and will be available next release.

**Comment by WillLBegin** [comment] 2024-10-11 18:18
Thank you so much
