### ISSUE TITLE
"Hide Reruns" feature

### ISSUE THREAD

**Issue by Senpos** [night/BetterTTV#3028] opened 2018-03-09 15:34 UTC
It could be nice to see this feature in **BetterTTV**.

As far as i understand, **Reruns** are just a bit modified realization of **Vodcasts**. 

**Reruns** can be easily hidden both in _sidebar_ and _directory_live_following_ with:
```js
$(".side-nav-card, .live-channel-card").has("svg[class*=rerun]").parent().hide()
```

The only problem I can't handle by myself is hooking in the right way to the _Show More_ button in the sidebar and _Load More_ (or whatever it called) in the _directory_live_following_, so changes could be applied even after adding new elements on the page.

**Comment by Senpos** [comment] 2018-03-09 15:36
I can see @hobbycoder7 was doing some stuff [here](https://github.com/night/BetterTTV/pull/2791), but that was for _Vodcasts_ and not available in BTTV now.

**Comment by TheRayJohnson** [comment] 2018-03-12 21:59
+1 for this, sounds so simple but useful. 

Shame Twitch didn't add a tab for reruns as they aren't really "LIVE" to be on /directory/following/live.

**Comment by night** [comment] 2018-03-17 21:16
duplicate of #2496

**Closed by night** 2018-03-17 21:16 UTC
Labels: duplicate
