### ISSUE TITLE
Channels and Twitch Chat

### ISSUE THREAD

**Issue by Anon7893** [night/betterttv#4044] opened 2020-07-14 14:24 UTC
Not sure if this is a BetterTTV issue or Twitch Issue, but I am having a problem where I am using Left Side Chat in the BetterTTV settings and usually it puts the Channels I am following on the right side and the chat on the left. Both are on the left side, and it bugs out my UI and can't use Theater mode because of it. Images here to show you. https://imgur.com/a/Npj9F4l

**Comment by Nareese** [comment] 2020-07-14 14:33
duplicate of #4029 

A patch to resolve this issue has been merged, but that version has not yet been released.

**Closed** 2020-07-19 23:03 UTC
Labels: invalid
