### ISSUE TITLE
Host Button is Missing

### ISSUE THREAD

**Issue by sassyshelbs** [night/BetterTTV#921] opened 2016-01-22 17:16 UTC
I have had on the host button feature for a while. I went into anonymous mode and it disappeared which makes sense. But now when I have left anonymous mode. The host button won't come back. I have tried turning it on and off again, a classic possible solution. I even restarted my computer. Not sure what to do about it. Pretty sure it is a bug.

**Comment by night** [comment] 2016-01-22 17:22
duplicate of #915

**Closed by night** 2016-01-22 17:22 UTC
Labels: duplicate
