### ISSUE TITLE
Feature request whitelist characters

### ISSUE THREAD

**Issue by MADJIHADx** [night/BetterTTV#502] opened 2015-06-16 07:42 UTC
It would be nice is you could white list a certain chunk of characters like a-z 0-9 so that only those characters are displayed. This would make ASCII trolling less effective.

Also the option to get rid of clickable links, this helps curb accidental click malware where someone posts a shortened url that redirects to malware. Many url shorteners are not removed but are still clickable in chat.

**Comment by night** [comment] 2015-06-18 15:27
Duplicate of #141

**Closed by night** 2015-06-18 15:27 UTC
Labels: duplicate
