### ISSUE TITLE
Autocomplete issue

### ISSUE THREAD

**Issue by Tranquilsong** [night/betterttv#4221] opened 2020-11-05 12:28 UTC
Hello there,

Last night I had to format my main drive because of a Windows update was corrupted. After re-installing Chrome and BTTV I've noticed the auto-complete with the colon feature no longer functioning correctly. I used to be able to auto-complete BTTV emotes and gifs by typing the colon followed by part of the emote and see a list, that's no longer the case (FFZ and twitch emotes work). Now if I have to auto-complete BTTV emotes then I must type the start of the emote and cycle around with the tab button.

Is there a way to go back to the colon search list feature, please? I dislike having to cycle without know if I got the right emote (I don't always remember the right way of typing the emotes myself).

With Best Regards,

Edit: I did try with and without FFZ installed, same thing.

**Comment by Nareese** [comment] 2020-11-05 17:41
The only auto-completion interface that BTTV provides is tab completion.  BTTV has never supported any kind of interaction with the colon prefixed emote interface, does not and has not ever auto-completed in that interface.  That interface is Twitch's, not BTTV's.  If you had auto-completion in that interface, some other extension was providing it.

**Comment by night** [comment] 2020-11-17 08:21
duplicate of #3807

**Closed by night** 2020-11-17 08:21 UTC
Labels: duplicate
