### ISSUE TITLE
"Show Deleted Messages" option is broken

### ISSUE THREAD

**Issue by KiwiJackal** [night/BetterTTV#2199] opened 2017-03-28 08:31 UTC
So when I have it enabled it still says "message deleted", I changed to some beta build or something by accident and it doesnt show the deleted messages anymore. I have deleted and reinstalled BetterTTV and the problem still persists.
![g](https://cloud.githubusercontent.com/assets/20118050/24395906/cec27cd4-13fd-11e7-99fe-529545798cbf.jpg)

**Comment by night** [comment] 2017-03-31 03:02
duplicate of #2177

**Closed by night** 2017-03-31 03:02 UTC
Labels: duplicate
