### ISSUE TITLE
The Case of the Missing Host Button

### ISSUE THREAD

**Issue by Bogkun** [night/BetterTTV#3600] opened 2019-09-29 18:03 UTC
I basically got BTTV because it gave me an extremely easy way to host other channels and I was enjoying it immensely for awhile there and then all of a sudden the Host button disappeared for no reason. I tried turning the button off and on again in the settings, but it didn't help, the button was just gone.

**Comment by Nareese** [comment] 2019-09-29 19:14
duplicate of #3595

**Closed** 2019-09-30 08:13 UTC
Labels: duplicate
