### ISSUE TITLE
The smile menu does not work well

### ISSUE THREAD

**Issue by SilentNewbee** [night/BetterTTV#3002] opened 2018-02-26 14:32 UTC
When you open the menu, only those smiles that were favorites are shown. What should I do to solve this problem? https://gyazo.com/fa28f73768de578906e2b84e1b848e3b - screenshot of the problem

**Comment by Regnander** [comment] 2018-02-26 20:05
You can attach a screenshot by dragging and dropping it into the text field. This way you don't have to link it to another website.

**Comment by SilentNewbee** [comment] 2018-02-26 20:22
![image](https://user-images.githubusercontent.com/36795001/36693278-a09c15ec-1b5c-11e8-86cf-b0b0d57c70c0.png)

**Comment by SilentNewbee** [comment] 2018-02-26 20:25
Can this help in solving the problem?

**Comment by Regnander** [comment] 2018-02-26 21:34
:thumbsup:

**Comment by ManChicken1911** [comment] 2018-03-01 19:35
I'm not sure if it's related as I'm not using favorites, but I have been having an issue where I open the emote menu after initially joining a stream, all the emotes show up. However, **after I use one emote**, in subsequent accesses of the emote menu it's completely blank... but if I scroll up and down several times, eventually they will all draw in. Close the menu, open it again, and it's blank again.

[Here's a link to a movie](https://clients.idolum.com/get/98a24bbde0a9) showing it happen. Firefox 58.0.2 x64, Windows.

**Comment by night** [comment] 2018-03-05 07:23
duplicate of #2941

**Closed by night** 2018-03-05 07:23 UTC
Labels: duplicate
