### ISSUE TITLE
auto-complete bug

### ISSUE THREAD

**Issue by evodoc** [night/BetterTTV#2994] opened 2018-02-24 19:22 UTC
The username and emote auto-complete doesn't seem to work properly. For example if you write "kapp" and press TAB, it will be corrected to "Kappa" in the input field, but if you press enter the original string will be forwarded to chat, so in this case "kapp". This also applies to auto-completed usernames.

**Comment by night** [comment] 2018-02-25 06:06
duplicate of #2987

**Closed by night** 2018-02-25 06:06 UTC
Labels: duplicate
