### ISSUE TITLE
Show Deleted Messages Not Working

### ISSUE THREAD

**Issue by PoppaMad** [night/BetterTTV#3239] opened 2018-08-29 07:19 UTC
The feature to Show Deleted Messages on Twitch has stopped working for me. I've uninstalled and reinstalled the BTTV addon to Chrome but is not working. And I'm sure it isn't people typing "<message deleted>" on purpose.

**Comment by Nareese** [comment] 2018-08-29 07:45
duplicate of #3233

**Closed** 2018-08-29 09:41 UTC
Labels: duplicate
