### ISSUE TITLE
FeatureRequest change volume by scrolling

### ISSUE THREAD

**Issue by MrSlimbrowser** [night/BetterTTV#1714] opened 2016-10-30 11:44 UTC
As written in the title, an option to change the stream volume by scrolling the mouse wheel while hovering the stream would be really nice :)

**Comment by thinkpad4** [comment] 2016-10-31 07:20
that would be hard as you would have to position your mouse NOT on the video to scroll down to the panels under it

**Comment by night** [comment] 2016-10-31 07:26
duplicate of #792

**Closed by night** 2016-10-31 07:26 UTC
Labels: duplicate
