### ISSUE TITLE
I cant see any emotes

### ISSUE THREAD

**Issue by vantekarui** [night/BetterTTV#3432] opened 2019-04-09 01:28 UTC
The option "BetterTV Emotes" is turned on but I can´t see some emotes like PepeHands or FeelsDarkMan. 
I already activated all possible options but some emotes still does not appear.
How can I fix this?

**Comment by night** [comment] 2019-04-09 07:03
duplicate of #3429

**Closed by night** 2019-04-09 07:03 UTC
Labels: duplicate
