### ISSUE TITLE
Dark Split Chat Not Working

### ISSUE THREAD

**Issue by Arcanted** [night/BetterTTV#3217] opened 2018-08-22 20:50 UTC
Hey guys,
My split chat in dark mode doesn't appear in grey gradients but a dark grey then unreadable white. Any solutions?

**Comment by knowfear1337** [comment] 2018-08-22 20:54
Just noticed the same thing for me hopefully its a quick one to fix

**Comment by Nareese** [comment] 2018-08-22 22:32
duplicate of #3216

**Closed** 2018-08-23 03:01 UTC
Labels: bug
