### ISSUE TITLE
BetterTTV not working with Edge

### ISSUE THREAD

**Issue by ArcWolf9** [night/BetterTTV#2476] opened 2017-05-22 11:44 UTC
I can't access BetterTTV's settings. The only changes BetterTTV seems to make are adding the alternate icon to the upper left of the page and changing the chat windows color. I also kept getting this error in the console:
SCRIPT438: Object doesn't support property or method 'ToString'
betterttv.unmin.js (8333,1)

**Comment by Nareese** [comment] 2017-05-22 17:44
There is no officially supported extension of BTTV for Edge.  That error would indicate that Edge is not fully compliant with the latest Javascript standards.  Up until recently, BTTV included a "polyfill", a backwards compatibility library to emulate missing functions, but it was found to be causing problems with Twitch's HTML5 player on current browsers, so it was removed.  This means that BTTV currently requires a fully compliant browser, which the latest version of all of the mainline popular browsers (Chrome, Firefox, Safari, etc) are.  You'll need to use one of them if Edge isn't, given that it's not officially supported in the first place.

**Comment by ArcWolf9** [comment] 2017-05-22 18:31
Alright, thanks for the info.

**Comment by night** [comment] 2017-05-22 18:34
duplicate of #2464

**Closed by night** 2017-05-22 18:34 UTC
Labels: duplicate
