### ISSUE TITLE
Image gets flagged as duplicate when it is not

### ISSUE THREAD

**Issue by leftovernick** [night/betterttv#6477] opened 2023-11-16 07:25 UTC
### Describe the bug

When uploading my emote, it gets marked as a duplicate of https://betterttv.com/emotes/551d19ac62e6bd0027aee2d2

### Steps to reproduce

Attempt to upload my emote, note that it is marked as duplicate for a different image

### Expected behavior

My emote would upload normally

### Screenshots

| My Emote | "Duplicate" Emote |
| --- | --- |
| ![NikuLogoBlackTransparent_112px](https://github.com/night/betterttv/assets/21072531/2564acd1-5f1b-413b-a18b-9e0ca0d03416) | ![3x](https://github.com/night/betterttv/assets/21072531/ddeb360f-28ed-4e00-88ed-e74db6a604f8) |

### Device information

Macbook
MacOS
Safari

**Comment by night** [comment] 2023-11-16 15:53
duplicate of #6423

**Closed by night** 2023-11-16 15:53 UTC
Labels: bug, duplicate
