### ISSUE TITLE
Emote menu

### ISSUE THREAD

**Issue by km1sat** [night/BetterTTV#2064] opened 2017-02-13 19:59 UTC
For the last several weeks I have been having trouble with the BTTV emote menu. When I click on the icon for it the menu only shows a few emotes and not any of the ones for the channels I am subscribed to or many normal emotes. It only shows some of the BTTV emotes. Please tell me what the problem is. Thanks

**Comment by night** [comment] 2017-02-19 11:14
duplicate of #2022

**Closed by night** 2017-02-19 11:14 UTC
Labels: duplicate
