### ISSUE TITLE
Feature Request: Scroll wheel over video to adjust volume

### ISSUE THREAD

**Issue by TheBeardedDoom** [night/BetterTTV#1047] opened 2016-03-30 09:19 UTC
I have grown used to this in MagicActions for Youtube and find my self trying to do it in BetterTTV.
It is EXTREMELY handy for adjusting volume on a second screen stream without having to click on the window (or more importantly, click OFF the game on the primary screen).

**Comment by night** [comment] 2016-03-30 18:18
Duplicate of #792

**Closed by night** 2016-03-30 18:18 UTC
Labels: duplicate
