### ISSUE TITLE
[Feature Request] Hide "Rerun" VoD's from /directory/following

### ISSUE THREAD

**Issue by ghost** [night/BetterTTV#3368] opened 2019-02-03 15:34 UTC
Would it be possible to have an option to block "Rerun" VoD's on Twitch's Following directory? They're distracting and I always think there are more channels streaming than there really is.

**Comment by Kobberholm** [comment] 2019-05-12 22:27
I would love to see this feature also applied to the sidebar (if this already exists, I have not been able to find it).

**Comment by night** [comment] 2019-09-23 10:02
duplicate of #2496

**Closed by night** 2019-09-23 10:02 UTC
Labels: duplicate
