### ISSUE TITLE
Left Side Chat?

### ISSUE THREAD

**Issue by 3py0n** [night/BetterTTV#1848] opened 2016-12-09 17:14 UTC
Would be great if BTTV could have an option to put the chat on the left side :D

**Comment by EhsanKia** [comment] 2016-12-09 18:56
For what it's worth I've got this mostly working. The annoying part isn't chat, but rather the other bar which would go on the right. More specifically, the hover popups for that are really annoying to fix so that they open on the proper side.

**Comment by night** [comment] 2016-12-09 21:58
duplicate of #202

**Closed by night** 2016-12-09 21:58 UTC
Labels: duplicate
