### ISSUE TITLE
Blacklist messages by message length

### ISSUE THREAD

**Issue by jeremyhill-up** [night/BetterTTV#3558] opened 2019-08-29 00:35 UTC
BTTV is great, I love it. I have a feature request, which is to expand the blacklist functionality a little bit. Either/or of these would be excellent:

1. Full regex support, or
2. Blacklisting messages based on message length

Fortunately a lot of streamers block the "░░░▒░█────▄▀░░░░░░░░▀" junk, but I'd love to be able to do it on my end for the streamers who don't.

**Comment by night** [comment] 2019-09-09 02:01
Duplicate of #141

**Closed by night** 2019-09-09 02:01 UTC
Labels: duplicate
