### ISSUE TITLE
BetterTTV feature request

### ISSUE THREAD

**Issue by Tortilla00** [night/BetterTTV#406] opened 2015-05-09 09:04 UTC
Hey, love your plugin for the night mode feature. There's something else I would like to see as well. I have two monitors and I often put twitch on the right hand side. Because of this It's hard to see the chat while I'm doing work stuff on the left monitor. 

So I would like to be able to flip the left sidebar with the chat box.

Cheers and I hope it's possible!

**Comment by night** [comment] 2015-05-11 08:24
Duplicate of #202

**Closed by night** 2015-05-11 08:24 UTC
Labels: duplicate
