### ISSUE TITLE
Hide recommended channels.

### ISSUE THREAD

**Issue by Gittyhub123** [night/betterttv#4721] opened 2021-08-05 13:45 UTC
Add the option to remove/hide the recommended channels sidebar on Twitch. The one between your online followed channels, and your online friends.

Also hide the recommended channels on the "Following" tab, below live channels and above latest videos.

Edit: I've just seen that the option to hide recommended channels is there, under featured channels. Might the reason for it not working be that I use Edge? 

Would still love the ability to hide recommended channels on the "Following" tab.

**Comment by night** [comment] 2021-08-06 06:47
duplicate of #4183

**Closed by night** 2021-08-06 06:47 UTC
Labels: duplicate
