### ISSUE TITLE
BTTV emotes break after hiding and unhiding chat

### ISSUE THREAD

**Issue by neil-lobo** [night/betterttv#3991] opened 2020-06-23 05:51 UTC
All BTTV emotes are just shown in plain text after hiding then unhiding as well as popping out then remounting chat. FFZ emotes however still work and are converted to their respective emotes.

If it helps, I've only tried it on Chrome version 83.0.4103.106.

EDIT: It seems that many bttv features like tab completion and user chat logs also break

**Comment by night** [comment] 2020-07-05 20:53
duplicate of #3184

**Closed by night** 2020-07-05 20:53 UTC
Labels: duplicate
