### ISSUE TITLE
[Feature request] Ability to remove the new "Person is offline, watch the latest VOD" thing

### ISSUE THREAD

**Issue by Yrlish** [night/BetterTTV#378] opened 2015-04-24 17:30 UTC
Hi!

It would be awesome if there was an possibility to remove that annoying box that appears above the player if the streamer is offline. Yes, I know I can just scroll down, but it's annoying and rather not have it at all.

http://imgur.com/vMv4lb4

Yrlish

**Comment by night** [comment] 2015-04-24 18:45
Duplicate of #366

**Closed by night** 2015-04-24 18:45 UTC
Labels: duplicate
