### ISSUE TITLE
Multiple issues

### ISSUE THREAD

**Issue by dsn4hf** [night/BetterTTV#2516] opened 2017-06-12 16:21 UTC
My Enter button doesn't send messages, there's always multiple "We failed to connect to chat" messages before connecting to chat, BetterTTV emotes do not show in chat nor are they displayed in the emote menu.

**Comment by Nareese** [comment] 2017-06-12 17:12
Ensure that your Chrome is fully updated (latest version is 59.0.3071.86, Menu->Help->About Google Chrome to check and force an update if needed).  This has resolved these issues for everyone who has reported them.

Duplicate of #2504

**Closed** 2017-06-13 17:30 UTC
Labels: invalid
