### ISSUE TITLE
Hide Recommended Channels is not working

### ISSUE THREAD

**Issue by ian9k** [night/BetterTTV#3355] opened 2019-01-16 18:58 UTC
I don't use any other extensions. I tried clean chrome install. 

![bttv](https://user-images.githubusercontent.com/46759514/51271763-ab52e180-19c8-11e9-850c-5f5872e56294.JPG)

**Comment by Sintamatix** [comment] 2019-01-19 04:30
I'm having the same issue

**Comment by whitecrownclown** [comment] 2019-02-11 00:32
@ian9k @Sintamatix I cannot seem to reproduce this, do you still have this issue?

**Comment by ian9k** [comment] 2019-02-12 03:17
Yes.

**Comment by whitecrownclown** [comment] 2019-02-12 14:53
@ian9k Could you provide more details? Like the browser you're using, if you tried it without other extensions, etc? Thank you!

**Comment by ian9k** [comment] 2019-02-12 20:29
I use chrome, i did fresh install with no other extensions and the problem is still there. I also tried firefox same problem.

**Comment by ufos** [comment] 2019-02-20 12:05
Same here. I'm using newest Firefox 65.0.1 @ Windows 10 1809 and this feature doesn't work at all.

**Comment by whitecrownclown** [comment] 2019-02-21 16:31
@Reqruiz @ian9k Are you using the latest bttv version?

**Comment by ian9k** [comment] 2019-02-21 20:57
Yes 7.2.1.

**Comment by Peuuuur-Noel** [comment] 2019-02-28 23:36
Hi, got the same issue since a while. Using the latest version (7.2.52)
Looks like ".recommended-channels" is not on the element.

The element can be reach with this query:
`.tw-full-width.tw-flex-grow-1 > .tw-mg-b-2`

Possible fixe in "src/modules/hide_sidebar_elements/style.css":
```
.bttv-hide-featured-channels {
  .recommended-channels,
  .tw-full-width.tw-flex-grow-1 > .tw-mg-b-2 {
    display: none;
  }
}
```

![featured-channels](https://user-images.githubusercontent.com/22428121/53605610-50f89380-3bb8-11e9-9c6e-27876c374e0b.png)

**Comment by whitecrownclown** [comment] 2019-03-01 16:46
That's weird, it must mean they're AB testing something... It's still working for me.

![image](https://user-images.githubusercontent.com/8309417/53652706-2fe48100-3c52-11e9-80d1-b3415223665f.png)

**Comment by Peuuuur-Noel** [comment] 2019-03-01 19:26
Yep, maybe testing something.
As far as I can remember, I've got this issue before november 2018 but not really troubled by that.

**Comment by night** [comment] 2019-09-16 07:51
closing since I cannot reproduce this and we've not gotten recent reports. maybe it was an experiment that never shipped.

**Closed by night** 2019-09-16 07:51 UTC
Labels: bug

**Comment by GreenTea13** [comment] 2020-07-11 19:21
I am current;y having this problem, so I don't think it's "fixed"

**Comment by OGLordBlight** [comment] 2020-07-30 13:21
This isn't working for me either. 
Chrome 84.0.4147.105 Official Build 64-bit or 
Firefox 78.0.2 and 79.0 both 64-bit
Windows 10 1909 (Build 18363.959)
BetterTTV v. 7.2.84

**Comment by avibhagat** [comment] 2020-08-13 05:34
Found open issue https://github.com/night/betterttv/issues/4023

**Comment by TeddybearEnthusiast** [comment] 2020-08-20 00:50
also having this issue.

**Comment by kevinberg92** [comment] 2020-08-29 09:30
this is annoying, please fix.
