### ISSUE TITLE
Remove the Recommended for you Listings

### ISSUE THREAD

**Issue by breezak** [night/BetterTTV#1667] opened 2016-10-18 15:50 UTC
Can you please add this feature, i am tired of twitch pushing fucking cosplay streams down my throat, i don't view them, never have and never will, yet i have to delete these so "Recommended for you based on your viewing history" every day

**Comment by night** [comment] 2016-10-21 02:53
duplicate of #1311

**Closed by night** 2016-10-21 02:53 UTC
Labels: duplicate

**Comment by breezak** [comment] 2016-10-21 02:56
no problem, was not aware of the duplicity, thank you
