### ISSUE TITLE
following hovering feature request

### ISSUE THREAD

**Issue by ErlingWis** [night/BetterTTV#1962] opened 2017-01-11 02:09 UTC
Would be nice to have a list that pops up when hovering over the 'following' option in the left bar that shows a list of all of the channels currently online, without leaving the current stream.

**Comment by Stoupedog** [comment] 2017-01-11 02:12
Duplicate of https://github.com/night/BetterTTV/issues/62

**Closed** 2017-01-11 08:05 UTC
Labels: duplicate
