### ISSUE TITLE
emote menu disappears

### ISSUE THREAD

**Issue by naotaXD13** [night/betterttv#6842] opened 2024-06-01 14:04 UTC
### Describe the bug

The emotes menu button disappears when the 7TV or FFZ extensions are installed. However, when you turn off and on the BTTV emote menu in BTTV settings, the button appears and works without any problems. If you reload the page it disappears again. 

### Steps to reproduce

*with the FFZ or 7TV extension installed and enabled*

1. Open any twitch stream
2. The button is gone.

### Expected behavior

The emotes menu button should be present under the chat box

### Screenshots

![bttv](https://github.com/night/betterttv/assets/113900947/8cef5ce4-a9b5-42d7-af63-1bc31b2d01da)

### Device information

Device: PC
OS: Windows 10
Browser: Google Chrome
Version: 125.0.6422.141

**Comment by night** [comment] 2024-06-03 14:05
duplicate of #6838

**Closed by night** 2024-06-03 14:05 UTC
Labels: bug
