### ISSUE TITLE
[Feature request] Hide channels broadcasting a rerun on the Following page

### ISSUE THREAD

**Issue by Aithys** [night/BetterTTV#3192] opened 2018-08-02 03:28 UTC
I have no interest in watching reruns and I often overlook the little "rerun" icon in the top left and mistakenly open a stream only to be disappointed when I discover its a rerun. I'd like to be able to just hide all rerun streams on my following page altogether.

**Comment by Nareese** [comment] 2018-08-02 06:17
duplicate of #2496

**Closed** 2018-08-04 21:32 UTC
Labels: duplicate
