### ISSUE TITLE
Toggle viewer count when in Theater mode

### ISSUE THREAD

**Issue by Akadin** [night/BetterTTV#673] opened 2015-08-23 10:43 UTC
Would be cool if there was a way to see the live viewer count when watching a channel in theater mode, maybe make it a toggle as i understand not everyone would want to see that. Something similar to the way Kadgar.net does it would be nice.

**Comment by night** [comment] 2015-08-23 15:14
Duplicate of #669

**Closed by night** 2015-08-23 15:14 UTC
Labels: duplicate
