### ISSUE TITLE
"Show deleted messages" not working properly 

### ISSUE THREAD

**Issue by Michaelix** [night/BetterTTV#3246] opened 2018-08-31 03:46 UTC
I tried reinstalling BetterTTV onto chrome, logging out and back in Twitch and even disconnecting and reconnecting my twitch account to BetterTTV

**Comment by Nareese** [comment] 2018-08-31 13:10
duplicate of #3233

**Comment by Michaelix** [comment] 2018-09-01 02:08
Apologies, feel free to remove.

**Closed** 2018-09-01 18:38 UTC
Labels: duplicate
