### ISSUE TITLE
Improvements to the Following page.

### ISSUE THREAD

**Issue by MrFine1** [night/BetterTTV#1904] opened 2016-12-19 09:24 UTC
I think it would be a useful option to disable the "Based on your viewing history" section in the Following tab. Currently, it bumps your followed games quite low on the page (or off the first page entirely). I want my followed games to be more visible.

**Comment by Stoupedog** [comment] 2016-12-19 09:27
Duplicate of https://github.com/night/BetterTTV/issues/1311

**Closed** 2016-12-22 07:50 UTC
Labels: duplicate
