### ISSUE TITLE
BTTV not working properly on Safari

### ISSUE THREAD

**Issue by Ravenner** [night/BetterTTV#2985] opened 2018-02-23 07:46 UTC
Followed the instructions and here is my javascript console on Safari, trying to run BTTV.
<img width="528" alt="nayttokuva 2018-2-23 kello 9 45 14" src="https://user-images.githubusercontent.com/36757479/36583434-63306888-187e-11e8-82cb-d35891d0cdb3.png">

**Comment by night** [comment] 2018-02-23 07:52
duplicate of #2982

**Closed by night** 2018-02-23 07:52 UTC
Labels: duplicate
