### ISSUE TITLE
Follow command

### ISSUE THREAD

**Issue by biwegas** [night/BetterTTV#2606] opened 2017-08-09 12:22 UTC
it would be cool if you could make a /follow command it chat and it makes you follow the current channel if it's possible.

**Comment by Stoupedog** [comment] 2017-08-11 12:15
duplicate of #2019

**Comment by biwegas** [comment] 2017-08-11 22:17
thats not exactly a issue for me i think it would be a good feature for people who doesn't use mouse often and prefers browsing/typing with keyboard or has limited accesibility on mouse usage (like with mouse pad is not easy to get used to it fast) also it would be more convenient for example if you use it while it is in followers only mode so you quickly type /follow and can use chat afterwards

**Closed** 2017-08-18 05:14 UTC
Labels: duplicate

**Comment by biwegas** [comment] 2017-08-18 10:49
@night you probably didn't noticed but other guy which asked about the /follow command his intentions was way different... Nothing is broken on twitch side with follow button i want to read you what i commented on my other message. Hope you understand it's more convenient for some people to use command (there is some cases) unless ofcourse you don't really have time or will to do it. Everything is understandable from your side if you are not willing to do it.
