### ISSUE TITLE
Tab complete is bugged

### ISSUE THREAD

**Issue by thinkpad4** [night/BetterTTV#2986] opened 2018-02-23 08:39 UTC
Tab complete isn't cycling through names, I have to double tap tab in BTTV for tab complete to work now

**Comment by Nareese** [comment] 2018-02-23 08:44
Additionally it appears to be non-functional for emotes.  I expect this is because of a regression on #2908 for getting the emote sets (they probably moved them again with yesterday's changes).  I'll look at it and see if I can find them tomorrow and make a PR.  I'll see if I can figure out the name complete issue as well.

**Comment by night** [comment] 2018-02-23 08:57
name completion is a twitch feature, not our feature

emote completion is broken because the keypress event is not being captured any longer.. im guessing twitch is blocking these from bubbling up to our handler

**Comment by night** [comment] 2018-02-23 09:11
fixed in master

**Closed by night** 2018-02-23 09:11 UTC
Labels: bug, chat
