### ISSUE TITLE
Flip chat side.

### ISSUE THREAD

**Issue by AnticZane** [night/BetterTTV#722] opened 2015-09-21 18:45 UTC
Not an issue, just an enhancement idea.

I find that I am able to monitor chat more easily when i move the chat to the left, and theater mode video to the right. Perhaps other people would like it as well. This would most likely need to be fired when entering theater mode, and after window resize events if the option is enabled.

The snippet i paste into my chrome console is as follows:

$('#right_col').css('right',null).css('left','0px');
$('#main_col').css('margin-right','0px').css('margin-left','364px');

Thanks for the awesome addon! It makes the Twitch UI so much better!
-Zane

**Comment by night** [comment] 2015-09-22 22:43
It is not so easy to implement this. While you can swap the CSS like you've done, BetterTTV also allows users to resize the chat. The logic used for resizing requires a complete overhaul if we were to support the flipping of chat, which is why it has not been implemented. This is something @voloshink was working on, but I have no idea its progress.

Duplicate of #202

**Closed by night** 2015-09-22 22:43 UTC
Labels: duplicate
