### ISSUE TITLE
Reverse Chat Direction

### ISSUE THREAD

**Issue by ttartari** [night/betterttv#5850] opened 2023-01-15 18:14 UTC
**Describe the bug**
The option reverse chat direction isn't working anymore. The "chat bar" goes to top, but the newest messages don't. I installed the 7.4.40 version to check if it was the version and nothing changed.

**To Reproduce**
Go to BetterTTV settings and activate the Reverse Chat Direction.

**Expected behavior**
The "chat bar" with the newest messages should go to the top.

I tested on Chrome, Edge and Brave.

It is a great tool for me and I only find it on Better TTV.
Thank you in advance for your hardwork.

**Comment by Delirya** [comment] 2023-01-15 19:59
I'm also experiencing the same issue, in Opera, Chrome and Edge

**Comment by night** [comment] 2023-01-15 23:38
duplicate of #5841

**Comment by dreamisun** [comment] 2023-01-16 10:02
have exactly the same problem and with the version 7.4.41

**Comment by night** [comment] 2023-01-18 20:29
This is fixed in 7.5.0

**Closed by night** 2023-01-18 20:29 UTC
Labels: duplicate

**Comment by animalcookiez** [comment] 2023-01-20 04:59
Fixed in version 7.5.0, Thank you.
