### ISSUE TITLE
BetterTTV emotes not appearing in the BetterTTV emote menu

### ISSUE THREAD

**Issue by Darthyoda12** [night/BetterTTV#2083] opened 2017-02-22 04:15 UTC
Every so often The BetterTTV emotes do not appear at all, I also mean the Twitch Prime emotes as well. I have tried uninstalling the extension and reinstalling it along with restarting the browser and turning on and off the list and emotes.
![bettv not fully working](https://cloud.githubusercontent.com/assets/25945088/23197048/6d5c6870-f872-11e6-9c73-64dc09e71361.JPG)

**Comment by night** [comment] 2017-02-22 09:42
duplicate of #2022

**Closed by night** 2017-02-22 09:42 UTC
Labels: duplicate
