### ISSUE TITLE
Anon Chat

### ISSUE THREAD

**Issue by VanDC** [night/BetterTTV#2492] opened 2017-05-30 17:25 UTC
When I have Anon Chat on, on Twitch then I can be seen in the viewing list anyways. I closed Twitch yesterday with it on, and had it on when I turned on the first stream, but people could see me. I haven't had 'Share my activity' on, only 'Anon Chat', but apparently it didn't work.
Please fix it :)
Thank you.

**Comment by Sonder13** [comment] 2017-05-30 20:14
I'm having the same issue as well. Thanks for the work towards a quick fix!

**Comment by night** [comment] 2017-05-30 20:50
duplicate of #2402

**Closed by night** 2017-05-30 20:50 UTC
Labels: duplicate
