### ISSUE TITLE
Option to have streamers chat highlighted

### ISSUE THREAD

**Issue by Rozkipz** [night/BetterTTV#604] opened 2015-07-28 17:29 UTC
Would be nice to have the streamer's messages in chat highlighted in a red colour, without having to add their name as a highlighted word, which also highlights any @streamer messages.

**Comment by voloshink** [comment] 2015-07-28 19:53
IMO the red badge is already enough, this will just add confusion between being mentioned and broadcaster messages

**Comment by night** [comment] 2015-07-28 21:05
Assuming you follow the broadcaster, duplicate of #94

**Closed by night** 2015-07-28 21:05 UTC
Labels: duplicate
