### ISSUE TITLE
There is no way to report user

### ISSUE THREAD

**Issue by ericbrian** [night/BetterTTV#2589] opened 2017-07-27 09:58 UTC
When clicking on a user name, the button to report a user is no longer there.

**Comment by Nareese** [comment] 2017-07-28 01:49
duplicate of #2501 

That button, on both Twitch's native and BTTV's mod card, is not "report user", it's "ignore user".  Twitch's ignore button on their mod card forces you to report a user in order to ignore them.  That functionality has never been a part of BTTV, and as mentioned in the referenced previous issue, it has been investigated and it is not possible for BTTV to trigger that popup from twitch, so it's something BTTV can't/won't fix.

**Closed** 2017-07-29 22:32 UTC
Labels: invalid
