### ISSUE TITLE
Suggestion: Audio only feature

### ISSUE THREAD

**Issue by Sabishi1985** [night/BetterTTV#2655] opened 2017-08-30 08:32 UTC
The mobile version of Twitch has an useful feature: It offers an "Audio only"-mode.  The browser version of twitch lacks this feature. So I would love to see this added by BTTV! :-)

**Comment by Stoupedog** [comment] 2017-09-01 23:46
Duplicate of #1493

**Closed** 2017-09-02 17:42 UTC
Labels: duplicate
