### ISSUE TITLE
"Tab Completion Emote" does not work

### ISSUE THREAD

**Issue by Eduardinholoko** [night/BetterTTV#3152] opened 2018-06-23 16:09 UTC
The "Tab Completion Emote" command does not work, when I press TAB it does not complete the Emoji, just Nicknames.
![screenshot_1](https://user-images.githubusercontent.com/40523695/41811474-9a811e10-76e6-11e8-83cd-a95f86723b40.png)

**Comment by Eduardinholoko** [comment] 2018-06-23 16:10
(firefox)
![image](https://user-images.githubusercontent.com/40523695/41811484-d1189bf6-76e6-11e8-9059-e8f4eed84a5e.png)

**Comment by samfun123** [comment] 2018-06-23 16:32
Duplicate of #3151

**Closed** 2018-06-23 17:59 UTC
Labels: duplicate
