### ISSUE TITLE
Ability to hide channels in local language

### ISSUE THREAD

**Issue by birjolaxew** [night/BetterTTV#2929] opened 2018-01-20 23:14 UTC
Twitch displays a collection of channels in your local language on top of all other channels. In the old Twitch this could be disabled - it cannot be disabled in the new design.  Would it be possible to add a feature to BetterTTV to do so?

Related: [Uservoice #1](https://twitch.uservoice.com/forums/297558-general/suggestions/32280346-hide-channels-in-my-local-language), [Uservoice #2](https://twitch.uservoice.com/forums/310222-mobile-ios-android/suggestions/11046444-option-to-disable-same-language-channels), [Reddit](https://www.reddit.com/r/Twitch/comments/2n2y6w/how_do_you_remove_twitch_searching_for_streams_in/)

And a quick screenshot for clarity - "Kanaler på dansk" means "Channels in danish":

![Local language example](https://user-images.githubusercontent.com/4542461/35188896-9c23de1c-fe3f-11e7-95a6-386d17ca5bdd.png)

**Comment by birjolaxew** [comment] 2018-01-20 23:27
Bit of technical info:

- Containing `<div>` doesn't have any class, ID or other attribute to identify it. It is a plain `<div>...</div>` as the first child of `div[data-target="directory-container"]`.

- Loaded as part of a request to `https://gql.twitch.tv/gql`, which is `POST`'d with request data object of the shape:

    ```
    [
      { operationName: "BrowsePopular_InternationalStreams", ... },
      { operationName: "BrowsePage_Popular", ... },
      ...
    ]
    ```

    Compare this to only loading the top streams:

    ```
    [
      { operationName: "BrowsePage_Popular", ... },
      ...
    ]
    ```

**Comment by night** [comment] 2018-01-28 09:49
duplicate of #70 tbh

**Closed by night** 2018-01-28 09:49 UTC
Labels: duplicate

**Comment by birjolaxew** [comment] 2018-01-28 16:31
@night Programmatically the two are separate; #70 is about blacklisting some item (a specific game, a specific channel) from displaying in a list, #2929 is about blacklisting an entire list (local directory) from displaying all together - without blacklisting the streams inside.

It is of course possible to just lump it all into #70; that's up to you.
