### ISSUE TITLE
Host button disappeared

### ISSUE THREAD

**Issue by SharkiB** [night/betterttv#4543] opened 2021-05-20 18:33 UTC
The 'Host Button' has recently disappeared within the last 2 days. I updated my Microsoft Edge and that was when it happened, I think.

**Comment by robonxt** [comment] 2021-05-20 20:30
+1. BTTV also disappeared from the chat settings

**Comment by dmreins** [comment] 2021-05-20 21:59
Disappeared from both chrome and edge for me - approx the same timeframe.  I checked settings and host button is still enabled.

**Comment by TitoLeproso** [comment] 2021-05-22 18:32
Same here with Opera browser (Chrome Extension)

**Comment by Namaretuklefu** [comment] 2021-05-22 19:56
Same here - Mozilla firefox. Looks like twitch made changes to their player so it ruins everything else. again...

**Comment by night** [comment] 2021-05-23 05:21
duplicate of #4537

**Closed by night** 2021-05-23 05:21 UTC
Labels: duplicate
