### ISSUE TITLE
Anon Chat broken

### ISSUE THREAD

**Issue by Sonder13** [night/BetterTTV#2493] opened 2017-05-30 21:55 UTC
Have noticed "Anon Chat" not working. Was advised a new release was out a couple of hours ago. Closed everything restarted, etc. etc. 

Now "Anon Chat" will show you logged out of chat, but now as well as appearing in the viewer list, I can still type in chat too. Screenshot attached. 
![unnamed](https://cloud.githubusercontent.com/assets/29073690/26606747/2c8ca436-4561-11e7-9e5e-edebe2e9c14d.jpg)
 

Thanks.

**Comment by night** [comment] 2017-05-30 21:57
duplicate of #2402

**Closed by night** 2017-05-30 21:57 UTC
Labels: duplicate
