### ISSUE TITLE
filtering viewers isn't working

### ISSUE THREAD

**Issue by spell09** [night/BetterTTV#1726] opened 2016-11-03 18:40 UTC
http://i.imgur.com/cgcgjpO.png http://i.imgur.com/QRX1UsC.png i tried reinstall better ttv but it doesnt helped me

**Comment by EhsanKia** [comment] 2016-11-03 22:59
Duplicate of #1713 will be fixed soon

**Closed by EhsanKia** 2016-11-03 22:59 UTC
