### ISSUE TITLE
Hide Recommend Channels Bug While Panel Collapsed

### ISSUE THREAD

**Issue by StargamerXD** [night/betterttv#4562] opened 2021-05-25 08:48 UTC
I have my left side of Twitch with all my followed channels collapsed. BTTV only hides the recommended channels when the left panel is not collapsed. 
Whenever I manually turn the option off and on again, while not collapsed, BTTV hides the channels again like it should. But when I collapse the panel again it doesn't keep the recommended channels hidden anymore after a (F5) refresh.

"Hide Offline Followed Channels" seems to work fine while collapsed and doesn't bug.

**Comment by Nareese** [comment] 2021-05-25 12:05
duplicate of #4183

**Closed** 2021-05-26 08:50 UTC
Labels: duplicate
