### ISSUE TITLE
Viewer list scrolling by itself

### ISSUE THREAD

**Issue by ToffEU** [night/BetterTTV#2342] opened 2017-04-26 14:48 UTC
When I open the viewerlist and scroll past names that start with an A its starting to scroll rapidly by itself to the bottom.

**Comment by EhsanKia** [comment] 2017-04-26 17:22
Duplicate of #2269, in the mean time, just search for the name you're looking for instead of scrolling in huge lists.

**Closed by EhsanKia** 2017-04-26 17:22 UTC
