### ISSUE TITLE
Twitch left sidebar "channels followed" number missing? 

### ISSUE THREAD

**Issue by dougchu21** [night/BetterTTV#1130] opened 2016-05-09 02:48 UTC
As stated in the title, there was previously a number showing how many Twitch channels that a user followed were live in the left sidebar (attached to the heart symbol). Wherever did that disappear to? Please add that back if ya could!

**Comment by night** [comment] 2016-05-09 18:26
Duplicate of #1129

**Closed by night** 2016-05-09 18:26 UTC
Labels: duplicate
