### ISSUE TITLE
Host Button missing probably due to Theater Mode Button being moved by Twitch

### ISSUE THREAD

**Issue by Firedingo** [night/BetterTTV#918] opened 2016-01-22 10:29 UTC
Host Button Appears to Be missing since today and according to twitch they have moved the theater mode button so the probable cause for the missing button is twitch's change.

Twitch's Announcement Of The Change: https://twitter.com/TwitchSupport/status/690406247623999490
A screenshot of the broken button: http://pasteboard.co/YTbxH6b.png

**Comment by night** [comment] 2016-01-22 17:12
Duplicate of #915

**Closed by night** 2016-01-22 17:12 UTC
Labels: duplicate
