### ISSUE TITLE
Add toggle for 'Click to pause'

### ISSUE THREAD

**Issue by darosk** [night/BetterTTV#1636] opened 2016-10-10 06:39 UTC
While Click to pause is standard on almost every video player out there, it is not on Twitch. Twitch isn't Youtube, it's live streaming. It is far too easy to accidentally click on the streaming video and pause the live content - hence obstructing the viewing experience.

**Comment by voloshink** [comment] 2016-10-10 07:08
Duplicate of #1635

**Closed by voloshink** 2016-10-10 07:08 UTC
