### ISSUE TITLE
Theater mode

### ISSUE THREAD

**Issue by satchmo2002** [night/BetterTTV#1571] opened 2016-09-30 17:20 UTC
With a new update all the streamer info that is normally below the video, now displays on the right side of the screen when in theater mode (therefore making theater mode useless because it is shrunken down again). Theater mode is good because it's a full screen in frame letting you use the entire screen for normal use without having to exit full screen when ever you need to do something else. As things are now, theater mode is USELESS. Being able to turn the side frame off displaying theater mode like it used to be would be a godsend.

**Comment by night** [comment] 2016-10-01 06:53
duplicate of #1568

**Closed by night** 2016-10-01 06:53 UTC
Labels: duplicate
