### ISSUE TITLE
Emote menu page zoom blurryness

### ISSUE THREAD

**Issue by night** [night/betterttv#4837] opened 2021-09-16 21:18 UTC
There has been reports that the new emote menu text and/or emotes can appear blurry upon changing page zoom from the default 100%.

![image](https://user-images.githubusercontent.com/2942184/133687131-2b0b9340-a7d3-4ce9-af82-a2ea74838d8d.png)

**Comment by movedoa** [comment] 2021-09-17 10:38
For me they are blurry even with the default zoom level (Firefox)

**Comment by dclstn** [comment] 2021-09-17 23:44
partially fixed via #4843, unsure what's the cause of blurry text

**Comment by TheFeelTrain** [comment] 2021-09-18 05:16
It's not just text, the entire element is blurred. I can't see any obvious reason why though.

Here is the purple border at 100% (scaled 4x) 
![Screenshot_20210917_221035](https://user-images.githubusercontent.com/12601452/133873530-e73cef28-2673-4825-95b0-78ee5c883d3f.png)

Here is the purple border at my default zoom of 125% (scaled 4x) 
![Screenshot_20210917_220737](https://user-images.githubusercontent.com/12601452/133873531-bc1c023c-5245-465f-9bce-71331581b6bd.png)

It's no longer a solid line like it should be, which implies something wrong with the scaling in general not just the emotes or text.

**Comment by TheFeelTrain** [comment] 2021-09-18 05:23
I have figured it out, it is caused by the -2px transform here:
![Screenshot_20210917_221906](https://user-images.githubusercontent.com/12601452/133873765-6304a00d-4081-48df-b76b-a89ef048206f.png)

Here is before and after unchecking them:
![Screenshot_20210917_222000](https://user-images.githubusercontent.com/12601452/133873788-cf5d469a-c506-4f24-a1f4-709023593e65.png)

**Closed** 2021-09-19 02:19 UTC
Labels: bug
