### ISSUE TITLE
Request for an option to remove the "Free With Prime" from the side bar for BTTV users

### ISSUE THREAD

**Issue by marzialid** [night/BetterTTV#1598] opened 2016-10-02 22:48 UTC
I would like to request an option for BTTV to remove the "Free With Prime" segment from the side bar on twitch as it makes the side bar even more cluttered. This is more of a request to make the side bar convenient for others. Furthermore, the "Free With Prime" option is annoying as it covers up a lot of the stream if you hover your mouse over any part of it. Thank you for your time!

**Comment by night** [comment] 2016-10-03 01:30
duplicate of #1583

**Closed by night** 2016-10-03 01:30 UTC
Labels: duplicate
