### ISSUE TITLE
[Request] Hide "Based on your viewing history" in Videos tab

### ISSUE THREAD

**Issue by valfaun** [night/BetterTTV#2626] opened 2017-08-16 17:33 UTC
as stated in the title, it would be nice if we could hide the suggested videos that take up the entire screen in the Videos tab. unless most people don't mind it. personally, though, i'm not interested in suggestions and just want to see past broadcasts from my followed channels when i go to that tab. 
very minor concern since it's just a matter of scrolling down, but would be appreciated if it's not much of a hassle to implement

**Comment by lackofwords** [comment] 2017-08-16 21:07
A quick fix is to just set the css display to none for the recommended video container
the class selector is js-videos

```
.js-videos {
    display: none !important;
}
```

**Comment by valfaun** [comment] 2017-08-17 13:47
@lackofwords 
hm, perhaps i misunderstand the concept, but just using the `.js-videos` selector hides all videos from the videos page. specifying the container's id doesn't work either as it's `ember####` with a dynamic number. after playing around for a bit, using `.js-videos.tower` seems to work, though. the "Based on your viewing history" header is still there and might be too generic to specify, but i can live with that. thanks for the quick workaround

**Comment by lackofwords** [comment] 2017-08-17 17:26
@valfaun Oops, yeah you're right, they've used the js-video selector for "Recent Videos" too.

If you want to get rid of the entire block, including the title, you'll need to use javascript to remove it.
The css solution was more of a band-aid solution to just get it out of view, unless if you want to use another browser extension/add-on to deal with it.

Just as a sidenote, don't forget to let Twitch know with a feedback on the UI for the Overview tab, or re-haul the Discovery system;
https://help.twitch.tv/customer/portal/articles/2537603

**Comment by night** [comment] 2017-08-18 05:16
duplicate of #1311

**Closed by night** 2017-08-18 05:16 UTC
Labels: duplicate
