### ISSUE TITLE
White patch on clips page in dark mode

### ISSUE THREAD

**Issue by bmon** [night/BetterTTV#2388] opened 2017-04-30 02:45 UTC
![image](https://cloud.githubusercontent.com/assets/2115272/25560860/7173574c-2da2-11e7-82e8-8a5efce79257.png)

This white patch is caused by a `height: auto;` rule on the body causing it to not fill the viewport, just grow to fit the page content.

**Comment by night** [comment] 2017-04-30 06:30
duplicate of #2292

**Closed by night** 2017-04-30 06:30 UTC
Labels: duplicate
