### ISSUE TITLE
New tab complete bug when chat scrolls

### ISSUE THREAD

**Issue by thinkpad4** [night/BetterTTV#2989] opened 2018-02-23 21:03 UTC
This issue https://github.com/night/BetterTTV/issues/2986 has been fixed, I can tab complete and cycle through names and emotes again, but a new bug has cropped up.  After hitting tab to complete the name or emote but before typing anything if the chat scrolls it removes the name and just shows the few letters you typed in to start tab completing.  As you can imagine this makes it difficult to use tab complete for names or emotes in a very busy chat.

**Comment by Nareese** [comment] 2018-02-23 21:16
Duplicate of the regrettably prematurely closed #2987.  Hopefully night will have a look at that when he sees these additional references.

**Comment by Weeeishy** [comment] 2018-02-23 22:41
I'm having the same issue right now. The only workaround I've found is to hit space immediately after hitting tab so it doesn't disappear.

**Comment by DeathOfBalance** [comment] 2018-02-23 22:48
I am also having this issue.

**Comment by heatblayze** [comment] 2018-02-24 17:53
Can confirm @Weeeishy 's workaround for the legacy popout

**Comment by night** [comment] 2018-02-25 06:06
duplicate of #2987

**Closed by night** 2018-02-25 06:06 UTC
Labels: duplicate
