### ISSUE TITLE
Hovering over emote doesn't show entire details

### ISSUE THREAD

**Issue by jollyaustin** [night/BetterTTV#2347] opened 2017-04-26 23:14 UTC
When an emote is on the far left side of the chat and I hover over it to see what channel it is or what the name is, it's cut off behind the video player.  It's like that for sub emotes as well as global emotes.  http://i.imgur.com/4zOttzf.png Here is a screencap of what I'm talking about.  The same applies to the far right side.  I can't recall if this has always been an issue or it's something I just recently noticed.

**Comment by night** [comment] 2017-04-27 00:38
duplicate of #2295

**Closed by night** 2017-04-27 00:38 UTC
Labels: duplicate
