### ISSUE TITLE
Twitch Chat on left does not display and UI is out of alignment

### ISSUE THREAD

**Issue by Quitch** [night/betterttv#3895] opened 2020-05-16 17:47 UTC
Microsoft Edge Version 81.0.416.72 (Official build) (64-bit)
BetterTTV v7.2.76 (latest in Microsoft Edge Add-ons) and also tested with 7.2.79 (latest in Chrome Web Store)

When chat is displayed on the left the UI shows as below

![image](https://user-images.githubusercontent.com/5182715/82126591-9e552680-97a5-11ea-9e62-bd03a5ec7d79.png)

I am unable to access the config to move chat to its initial position to see if this resolves the issue as the cog to access settings resides within the chat panel which is not shown. Disabling the extension does fix the issue.

The config in use broke on the 15th May. No changes to the config had been made,

**Comment by Rawh** [comment] 2020-05-17 19:34
I also have this issue with FF 76.0.1 64bit and BetterTTV 7.2.79

Chat seems fine when you leave it on the right side... but when you move it to the left, the twitch video itself shows a large black area to the right and the left only has the fold out button shown:
> |->

**Comment by night** [comment] 2020-05-18 22:42
duplicate of #3873

**Closed by night** 2020-05-18 22:42 UTC
Labels: duplicate
