### ISSUE TITLE
Feature Request - Portrait Mode Chat 

### ISSUE THREAD

**Issue by ryeply** [night/betterttv#5627] opened 2022-09-14 05:22 UTC
The idea is something I got from the ChatReplay extension by Restorn, but essentially it moves the chat on top of the stream. This makes the chat and stream way easier to watch on vertical monitors.

**Comment by Dorantic** [comment] 2022-09-14 22:17
> The idea is something I got from the ChatReplay extension by Restorn, but essentially it moves the chat onto of the stream. This makes the chat and stream way easier to watch on vertical monitors.

Was going to make my own feature request for this but I guess I wont, I will just build of this idea. Vertical chat, an additional option in the setting to view the chat below the stream video in theater mode. Or like I've seen suggested before a transparent overlay of the chat onto the stream.

**Comment by night** [comment] 2022-10-01 02:31
duplicate of #1933

**Closed by night** 2022-10-01 02:31 UTC
Labels: duplicate
