### ISSUE TITLE
Türkçe dil desteği / Turkish language support

### ISSUE THREAD

**Issue by lazhayalet** [night/betterttv#4248] opened 2020-11-28 18:06 UTC
Merhabalar, Türkçe dil desteği gelirse uygulamadan memnun olacağım veya dil paketini gönderirseniz Türkçeye çevirip tekrar gönderebilirim. Kontrol edebilirsiniz. Şimdiden teşekkürler.

Hello, I will be pleased with the application if Turkish language support comes, or if you send the language pack, I can translate it into Turkish and send it again. You can check it out. Thanks in advance.

**Comment by Nareese** [comment] 2020-11-28 19:04
Duplicate of #2728

BTTV does not currently offer support for any language translations.  It is something that night has indicated that he would like to do some day, but there is no estimate as to when that might be (and under current circumstances, probably not any time soon).

**Closed** 2020-11-28 20:54 UTC
Labels: duplicate
