### ISSUE TITLE
Chat not loading with better ttv? 

### ISSUE THREAD

**Issue by TruthsAdvocate** [night/BetterTTV#1572] opened 2016-09-30 22:03 UTC
Like 90% of the time when I open a stream, the chat just doesnt load any messages from me or anyone else. Works fine without betterttv. Help?

**Comment by RandomGOTI** [comment] 2016-09-30 23:55
same issue , it happens if i load the page with the anon chat...atleast for me

**Comment by night** [comment] 2016-10-01 06:08
Hmm I cannot reproduce this with anon chat. What browser/os? Have you tried clearing your cookies and cache (from the beginning of time)?

**Comment by jdmanring** [comment] 2016-10-01 08:13
Same happens to me.  The chat loads all previous messages to the scrollback amount and then they disappear immediately.  No new messages are displayed to the user after sent.  Google Chrome / Windows 8.1 Pro 64-bit.

Reloading the channel 5 to 10 times will sometimes make everything work properly.

**Comment by danielbruni** [comment] 2016-10-01 10:42
Same Problem here.

**Comment by dequeues** [comment] 2016-10-01 14:47
Does it mention anything in the developer console? (CTRL+SHIFT+J on Chrome)

**Comment by night** [comment] 2016-10-01 16:29
You should also try disabling all of your other chrome extensions, as one could be incompatible with ours for some reason. Clearing chat when it loads is because the chat history Twitch loads is being eaten, which is a separate bug.

**Comment by danielbruni** [comment] 2016-10-02 16:15
I disabled all addons except bttv:
Chrome Dev Console:

> GET https://edge.quantserve.com/quant.js net::ERR_INSECURE_RESPONSE
global-c7d46c5….js:29 GET chrome-extension://hfaagokkkhdbgiakmmlclaapfelnkoah/cast_sender.js net::ERR_FAILEDe.cast.ApiBootstrap_.isExtensionInstalled_ @ global-c7d46c5….js:29e.cast.ApiBootstrap_.findInstalledExtensionHelper_ @ global-c7d46c5….js:29(anonymous function) @ global-c7d46c5….js:29r.onerror @ global-c7d46c5….js:29
global-c7d46c5….js:29 No cast extension found
global-c7d46c5….js:29 document not ready yet, trying again in 500 milliseconds...
global-c7d46c5….js:16 GET https://api.twitch.tv/api/channels/zhootdotse/product?on_site=1 404 (Not Found)send @ global-c7d46c5….js:16ajax @ global-c7d46c5….js:16n._ajax @ global-c7d46c5….js:29n.get @ global-c7d46c5….js:29(anonymous function) @ emberapp-9a88788….js:107(anonymous function) @ emberapp-9a88788….js:185_ @ emberapp-9a88788….js:14d @ emberapp-9a88788….js:15n @ emberapp-9a88788….js:185request @ emberapp-9a88788….js:107request @ emberapp-9a88788….js:103loadMore @ emberapp-9a88788….js:103load @ emberapp-9a88788….js:103(anonymous function) @ emberapp-9a88788….js:102h @ emberapp-9a88788….js:5r @ emberapp-9a88788….js:10create @ emberapp-9a88788….js:10create @ emberapp-9a88788….js:103r @ emberapp-9a88788….js:7findOne @ emberapp-9a88788….js:103setCurrentChannelRoom @ emberapp-9a88788….js:96setupController @ emberapp-9a88788….js:105r @ emberapp-9a88788….js:7setup @ emberapp-9a88788….js:8f @ emberapp-9a88788….js:14f @ emberapp-9a88788….js:14h @ emberapp-9a88788….js:14g @ emberapp-9a88788….js:14(anonymous function) @ emberapp-9a88788….js:14y @ emberapp-9a88788….js:14b @ emberapp-9a88788….js:14g @ emberapp-9a88788….js:14(anonymous function) @ emberapp-9a88788….js:9invoke @ emberapp-9a88788….js:1flush @ emberapp-9a88788….js:1flush @ emberapp-9a88788….js:1end @ emberapp-9a88788….js:1run @ emberapp-9a88788….js:1join @ emberapp-9a88788….js:1l.join @ emberapp-9a88788….js:6(anonymous function) @ emberapp-9a88788….js:6B @ global-c7d46c5….js:18j @ global-c7d46c5….js:18D @ global-c7d46c5….js:18xt @ global-c7d46c5….js:18
global-c7d46c5….js:16 GET https://api.twitch.tv/kraken/feed/zhootdotse/posts?limit=10 403 (Forbidden)send @ global-c7d46c5….js:16ajax @ global-c7d46c5….js:16n._ajax @ global-c7d46c5….js:29n.get @ global-c7d46c5….js:29(anonymous function) @ emberapp-9a88788….js:107(anonymous function) @ emberapp-9a88788….js:185_ @ emberapp-9a88788….js:14d @ emberapp-9a88788….js:15n @ emberapp-9a88788….js:185request @ emberapp-9a88788….js:107(anonymous function) @ emberapp-9a88788….js:107y @ emberapp-9a88788….js:14b @ emberapp-9a88788….js:14g @ emberapp-9a88788….js:14(anonymous function) @ emberapp-9a88788….js:9invoke @ emberapp-9a88788….js:1flush @ emberapp-9a88788….js:1flush @ emberapp-9a88788….js:1end @ emberapp-9a88788….js:1run @ emberapp-9a88788….js:1join @ emberapp-9a88788….js:1l.join @ emberapp-9a88788….js:6(anonymous function) @ emberapp-9a88788….js:6B @ global-c7d46c5….js:18j @ global-c7d46c5….js:18D @ global-c7d46c5….js:18xt @ global-c7d46c5….js:18
global-c7d46c5….js:16 GET https://api.twitch.tv/kraken/users/beyinsen?on_site=1 422 (Unprocessable Entity)send @ global-c7d46c5….js:16ajax @ global-c7d46c5….js:16n._ajax @ global-c7d46c5….js:29n.get @ global-c7d46c5….js:29(anonymous function) @ emberapp-9a88788….js:107(anonymous function) @ emberapp-9a88788….js:185_ @ emberapp-9a88788….js:14d @ emberapp-9a88788….js:15n @ emberapp-9a88788….js:185request @ emberapp-9a88788….js:107(anonymous function) @ emberapp-9a88788….js:84h @ emberapp-9a88788….js:5r @ emberapp-9a88788….js:10create @ emberapp-9a88788….js:10y @ emberapp-9a88788….js:4p.create @ emberapp-9a88788….js:4d @ emberapp-9a88788….js:3S @ emberapp-9a88788….js:12T @ emberapp-9a88788….js:13inline @ emberapp-9a88788….js:13l.populateNodes @ emberapp-9a88788….js:13l.render @ emberapp-9a88788….js:13o @ emberapp-9a88788….js:13(anonymous function) @ emberapp-9a88788….js:12(anonymous function) @ emberapp-9a88788….js:12(anonymous function) @ emberapp-9a88788….js:3i @ emberapp-9a88788….js:3n @ emberapp-9a88788….js:3compute @ emberapp-9a88788….js:4value @ emberapp-9a88788….js:7n @ emberapp-9a88788….js:3(anonymous function) @ emberapp-9a88788….js:12s @ emberapp-9a88788….js:13C @ emberapp-9a88788….js:12k @ emberapp-9a88788….js:12x @ emberapp-9a88788….js:12block @ emberapp-9a88788….js:13(anonymous function) @ emberapp-9a88788….js:13i @ emberapp-9a88788….js:13block @ emberapp-9a88788….js:13l.populateNodes @ emberapp-9a88788….js:13l.revalidateWith @ emberapp-9a88788….js:13r @ emberapp-9a88788….js:13i @ emberapp-9a88788….js:13block @ emberapp-9a88788….js:13l.populateNodes @ emberapp-9a88788….js:13l.revalidateWith @ emberapp-9a88788….js:13r @ emberapp-9a88788….js:13i @ emberapp-9a88788….js:13content @ emberapp-9a88788….js:13l.populateNodes @ emberapp-9a88788….js:13l.revalidateWith @ emberapp-9a88788….js:13i.invoke @ emberapp-9a88788….js:13(anonymous function) @ emberapp-9a88788….js:4r @ emberapp-9a88788….js:4p.rerender @ emberapp-9a88788….js:4d @ emberapp-9a88788….js:3S @ emberapp-9a88788….js:12T @ emberapp-9a88788….js:13inline @ emberapp-9a88788….js:13(anonymous function) @ emberapp-9a88788….js:13i @ emberapp-9a88788….js:13inline @ emberapp-9a88788….js:13l.populateNodes @ emberapp-9a88788….js:13l.revalidateWith @ emberapp-9a88788….js:13r @ emberapp-9a88788….js:13i @ emberapp-9a88788….js:13content @ emberapp-9a88788….js:13l.populateNodes @ emberapp-9a88788….js:13l.revalidateWith @ emberapp-9a88788….js:13i.invoke @ emberapp-9a88788….js:13(anonymous function) @ emberapp-9a88788….js:4r @ emberapp-9a88788….js:4p.rerender @ emberapp-9a88788….js:4d @ emberapp-9a88788….js:3S @ emberapp-9a88788….js:12T @ emberapp-9a88788….js:13inline @ emberapp-9a88788….js:13(anonymous function) @ emberapp-9a88788….js:13i @ emberapp-9a88788….js:13inline @ emberapp-9a88788….js:13l.populateNodes @ emberapp-9a88788….js:13l.revalidateWith @ emberapp-9a88788….js:13r @ emberapp-9a88788….js:13i @ emberapp-9a88788….js:13block @ emberapp-9a88788….js:13l.populateNodes @ emberapp-9a88788….js:13l.revalidateWith @ emberapp-9a88788….js:13r @ emberapp-9a88788….js:13i @ emberapp-9a88788….js:13block @ emberapp-9a88788….js:13l.populateNodes @ emberapp-9a88788….js:13l.revalidateWith @ emberapp-9a88788….js:13r @ emberapp-9a88788….js:13i @ emberapp-9a88788….js:13content @ emberapp-9a88788….js:13l.populateNodes @ emberapp-9a88788….js:13l.revalidateWith @ emberapp-9a88788….js:13r @ emberapp-9a88788….js:13i @ emberapp-9a88788….js:13block @ emberapp-9a88788….js:13l.populateNodes @ emberapp-9a88788….js:13l.revalidateWith @ emberapp-9a88788….js:13r @ emberapp-9a88788….js:13i @ emberapp-9a88788….js:13content @ emberapp-9a88788….js:13l.populateNodes @ emberapp-9a88788….js:13l.revalidateWith @ emberapp-9a88788….js:13r @ emberapp-9a88788….js:13i @ emberapp-9a88788….js:13content @ emberapp-9a88788….js:13l.populateNodes @ emberapp-9a88788….js:13l.revalidateWith @ emberapp-9a88788….js:13l.revalidate @ emberapp-9a88788….js:13l.revalidateTopLevelView @ emberapp-9a88788….js:7e.default.l.Mixin.create.m.revalidate @ emberapp-9a88788….js:11invoke @ emberapp-9a88788….js:1flush @ emberapp-9a88788….js:1flush @ emberapp-9a88788….js:1end @ emberapp-9a88788….js:1run @ emberapp-9a88788….js:1join @ emberapp-9a88788….js:1l.join @ emberapp-9a88788….js:6t.success @ emberapp-9a88788….js:27f @ global-c7d46c5….js:15fireWith @ global-c7d46c5….js:15x @ global-c7d46c5….js:16t @ global-c7d46c5….js:16
global-c7d46c5….js:16 GET https://api.twitch.tv/kraken/feed/zhootdotse/posts?limit=10 403 (Forbidden)send @ global-c7d46c5….js:16ajax @ global-c7d46c5….js:16n._ajax @ global-c7d46c5….js:29n.get @ global-c7d46c5….js:29(anonymous function) @ emberapp-9a88788….js:107(anonymous function) @ emberapp-9a88788….js:185_ @ emberapp-9a88788….js:14d @ emberapp-9a88788….js:15n @ emberapp-9a88788….js:185request @ emberapp-9a88788….js:107(anonymous function) @ emberapp-9a88788….js:107y @ emberapp-9a88788….js:14b @ emberapp-9a88788….js:14g @ emberapp-9a88788….js:14(anonymous function) @ emberapp-9a88788….js:9invoke @ emberapp-9a88788….js:1flush @ emberapp-9a88788….js:1flush @ emberapp-9a88788….js:1end @ emberapp-9a88788….js:1run @ emberapp-9a88788….js:1join @ emberapp-9a88788….js:1l.join @ emberapp-9a88788….js:6(anonymous function) @ emberapp-9a88788….js:6s.emitEvent @ player.js:2s.emit @ player.js:2(anonymous function) @ player.js:14(anonymous function) @ player.js:11u @ player.js:43(anonymous function) @ player.js:43dispatch @ player.js:43(anonymous function) @ player.js:21
global-c7d46c5….js:29 TransportStream() Found AAC stream at PID 256
global-c7d46c5….js:29 TransportStream() Found AVC stream at PID 257
global-c7d46c5….js:29 TransportStream() Found ID3 stream at PID 258
global-c7d46c5….js:29 fmp4 addTrackAvc() id:1 avc1.4D401F
global-c7d46c5….js:29 fmp4 addTrackAac() id:2 mp4a.40.2
global-c7d46c5….js:29 Writing Init fragment
global-c7d46c5….js:29 codec: {"height": 720, "level": "3.1", "mime": "avc1.4D401F", "
global-c7d46c5….js:29 codec: {"channels": 2, "frequency": 44100, "mime": "mp4a.40.2"}
global-c7d46c5….js:16 GET https://api.betterttv.net/2/channels/zhootdotse 404 ()send @ global-c7d46c5….js:16ajax @ global-c7d46c5….js:16p.(anonymous function) @ global-c7d46c5….js:16getJSON @ global-c7d46c5….js:16r.loadBTTVChannelData @ betterttv.js?0.2819428908170145:44o.exports @ betterttv.js?0.2819428908170145:44S @ betterttv.js?0.2819428908170145:54l @ betterttv.js?0.2819428908170145:54
global-c7d46c5….js:16 GET https://api.twitch.tv/kraken/feed/zhootdotse/posts?limit=10 403 (Forbidden)send @ global-c7d46c5….js:16ajax @ global-c7d46c5….js:16n._ajax @ global-c7d46c5….js:29n.get @ global-c7d46c5….js:29(anonymous function) @ emberapp-9a88788….js:107(anonymous function) @ emberapp-9a88788….js:185_ @ emberapp-9a88788….js:14d @ emberapp-9a88788….js:15n @ emberapp-9a88788….js:185request @ emberapp-9a88788….js:107(anonymous function) @ emberapp-9a88788….js:107y @ emberapp-9a88788….js:14b @ emberapp-9a88788….js:14g @ emberapp-9a88788….js:14(anonymous function) @ emberapp-9a88788….js:9invoke @ emberapp-9a88788….js:1flush @ emberapp-9a88788….js:1flush @ emberapp-9a88788….js:1end @ emberapp-9a88788….js:1run @ emberapp-9a88788….js:1join @ emberapp-9a88788….js:1l.join @ emberapp-9a88788….js:6(anonymous function) @ emberapp-9a88788….js:6s.emitEvent @ player.js:2s.emit @ player.js:2(anonymous function) @ player.js:14(anonymous function) @ player.js:11u @ player.js:43(anonymous function) @ player.js:43value @ player.js:42value @ emberapp-9a88788….js:23value @ emberapp-9a88788….js:24value @ emberapp-9a88788….js:23value @ emberapp-9a88788….js:24

**Comment by dequeues** [comment] 2016-10-02 20:44
That's all you had when the chat did _not_ load?

**Comment by danielbruni** [comment] 2016-10-03 08:25
I updated the file with the output of another twitch channel... the strange thing is... the chat message show up on loading the chat but then disappear.

https://gist.github.com/danielbruni/0284b4e86c6d0f04c7833b4e58b02b73

**Comment by night** [comment] 2016-10-03 16:25
> the chat message show up on loading the chat but then disappear.

Refer to what I said earlier in this issue:

> Clearing chat when it loads is because the chat history Twitch loads is being eaten, which is a separate bug.

That doesn't mean the chat is broken. New messages you send should be rendered.

**Comment by RandomGOTI** [comment] 2016-10-04 03:08
@night 
Windows 7 Ultimate 64
Chrome 53.0.2785.143 m (64-bit)
BetterTTV 6.9

And yes i did clean my browsing data and even reset the settings , turned off the anon chat and i no longer have chat issues , the chat loads normally

**Comment by danielbruni** [comment] 2016-10-04 07:29
As i said before. I have no extensions enabled.... just betterTTV. And i cant even see my own messages with betterTTV.  It was working 4 days ago without changing anything.

**Comment by night** [comment] 2016-10-10 03:32
closing because we cannot reproduce this issue. if you're still having issues, make sure you're clearing your cookies and cache "from the beginning of time."

**Closed by night** 2016-10-10 03:32 UTC
Labels: invalid

**Comment by jdmanring** [comment] 2016-10-10 19:46
The issue still clearly happens for me every single time I enter a stream for the first time that day, and for several others.  I have certainly cleared my cache from the beginning of time multiple times.  I get that you cannot reproduce it but it closing a real issue and calling it invalid good idea?
