### ISSUE TITLE
Left side chat bug

### ISSUE THREAD

**Issue by YaniiBeezy** [night/betterttv#4155] opened 2020-09-25 02:01 UTC
There is a bug with the left side chat, since Twitch rolled out that feature that pulls out the live list when hovering over, there's a big black bar on the right when turned on. Can that be fixed soon, I miss that feature very much.

https://gyazo.com/6bf153715ee0f921784745936acd5da3

**Comment by night** [comment] 2020-09-29 10:37
duplicate of #4142

**Closed by night** 2020-09-29 10:37 UTC
Labels: duplicate
