### ISSUE TITLE
Featured Channels Setting no longer works

### ISSUE THREAD

**Issue by GG137** [night/BetterTTV#938] opened 2016-01-30 19:19 UTC
Bug: Featured Channels no longer works. 

Steps to Reproduce: Leave Featured Channels at it's default setting. 

Outcome: Featured Channels are not removed from the sidebar on twitch.tv.

Other information: I have tried both settings, Off and On. After switching between the settings, I closed the BetterTTV popup and refreshed the page. Neither settings seem to have an effect. 

![wmbgptk](https://cloud.githubusercontent.com/assets/9310399/12697918/6bdd6ab4-c75c-11e5-9da3-04abdf3aec5a.jpg)

**Comment by night** [comment] 2016-01-30 20:36
Duplicate of #937

**Closed by night** 2016-01-30 20:36 UTC
Labels: duplicate
