### ISSUE TITLE
Hide Recommended Channels not working

### ISSUE THREAD

**Issue by PrinceMew** [night/betterttv#4026] opened 2020-07-09 04:56 UTC
I keep Hide Recommended Channels on at all times, but about 3 days ago it stopped working.
I wondered if it was just my BTTV so I went through settings I could change that would be immediately visible: I chose putting my chat on the left side of my screen, and that worked right away.
So I'm wondering what's wrong with hiding recommended channels.

**Comment by Nareese** [comment] 2020-07-09 11:57
duplicate of #4023

**Closed** 2020-07-12 19:24 UTC
Labels: duplicate
