### ISSUE TITLE
Separate highlight keywords for being viewer/mod/streamer

### ISSUE THREAD

**Issue by Cyberbeni** [night/BetterTTV#1426] opened 2016-08-02 15:08 UTC
Setting common chat bot phrases in your highlight keywords is pretty useful for moderating but it's annoying when you are in another channel where you are not a mod. I think it would be cool to set them up separately.

**Comment by night** [comment] 2016-08-03 03:18
duplicate of #68

**Closed by night** 2016-08-03 03:18 UTC
Labels: duplicate
