### ISSUE TITLE
New Feature

### ISSUE THREAD

**Issue by mkjol** [night/BetterTTV#735] opened 2015-10-01 20:48 UTC
Hay!
Can you add option to turn off auto-aborting clearing chat? ;p (I, know my english isnt really good :/ )
Here is an example of what I mean
![bez tytulu](https://cloud.githubusercontent.com/assets/14931676/10233373/5c9ad064-688e-11e5-8aca-a76d6bcf3051.jpg)

Greets and thanks you in advance!

**Comment by night** [comment] 2015-10-01 20:50
Duplicate of #524

**Closed by night** 2015-10-01 20:50 UTC
Labels: duplicate
