### ISSUE TITLE
[Feature request] mode to hide all emotes

### ISSUE THREAD

**Issue by gamernation89** [night/BetterTTV#2225] opened 2017-04-03 17:06 UTC
can we have a disable emote mode that will allow us to not see no emotes at all and only messages

**Comment by EhsanKia** [comment] 2017-04-03 20:09
There's /localascii, though I think it only works for emojis right now. We were planning on adding emotes to it too.

**Comment by Koen09** [comment] 2017-05-01 17:41
I was thinking of something similar. I'd love to have a mode which filters out messages that **only** contain emotes. This way you get rid of a lot of the emote spam and keep the messages which actually say something.

**Comment by night** [comment] 2017-07-19 04:51
duplicate of #85

**Closed by night** 2017-07-19 04:51 UTC
Labels: duplicate
