### ISSUE TITLE
2 bugs

### ISSUE THREAD

**Issue by sanity69** [night/BetterTTV#2048] opened 2017-02-09 02:56 UTC
Emotes quite often wont show for me but will for other people in chat. and when i try to click on bttv settings on the left side menu on twitch where freinds list is, It will ghost through that panel and click on a freinds name underneath and send me to what ever stream they are watching. Also seems pretty slow to load lately even when clearing cache ect. Quite unresponsive!

**Comment by night** [comment] 2017-02-09 09:19
duplicate of #2022

**Closed by night** 2017-02-09 09:19 UTC
Labels: duplicate
