### ISSUE TITLE
Out of nowhere BTTV emotes stopped working on a Macbook Pro using Firefox

### ISSUE THREAD

**Issue by snusif** [night/BetterTTV#2966] opened 2018-02-10 00:07 UTC
As stated BTTV emotes doesn't show, neither the spesific channel ones like monkaS nor the BTTV global ones like FeelsBadMan. I have tried reinstalling, disable and enable the addon in Firefox, disable and enable both emotes and GIFs in BTTV settings, restarting laptop and obviously restarting Firefox. Nothing works. 

It worked earlier today (Friday 9. Feb) on a Windows Desktop, but when I went to bed and started watching on my Mac the emotes wouldn't show.

Is it a known issue?

**Comment by Starfola** [comment] 2018-02-10 00:22
I'm also getting this issue. Pretty sure it's happening to a lot of people since twitch chat is talking about it.

here's the debug console:
![pf084w7](https://user-images.githubusercontent.com/5252904/36055987-84b46dde-0dce-11e8-80ea-92ef189f1063.png)

**Comment by Dsingis** [comment] 2018-02-10 00:43
Not only on firefox, on Chrome as well. I tried both.

Just a couple hours ago, everything worked fine and then poof, suddenly everything stops showing.

**Comment by night** [comment] 2018-02-10 04:13
duplicate of #2963

**Closed by night** 2018-02-10 04:13 UTC
