### ISSUE TITLE
Block All Emotes

### ISSUE THREAD

**Issue by Ashedragon** [night/BetterTTV#317] opened 2015-04-01 18:43 UTC
As the title suggests, a setting to block all emotes.

**Comment by CharlesIsOp** [comment] 2015-04-02 22:44
You are aloud to set your own personal BlackList. If you don't like a cretin Emote you could always black list it. (Setting -> "Set Blacklist Keywords" )

**Comment by metarmask** [comment] 2015-04-03 11:20
Here's all the emotes ready to be pasted:
    4Head ANELE ArsonNoSexy AsianGlow AtGL AthenaPMS AtIvy AtWW BabyRage BatChest BCWarrior BibleThump BigBrother BionicBunion BlargNaut BloodTrail BORT BrainSlug BrokeBack BuddhaBar CougarHunt DAESuppy DansGame DatHass DatSheffy DBstyle DendiFace DogFace EagleEye EleGiggle EvilFetus FailFish FPSMarksman FrankerZ FreakinStinkin FUNgineer FunRun FuzzyOtterOO GasJoker GingerPower GrammarKing HassanChop HeyGuys HotPokket HumbleLife ItsBoshyTime Jebaited JKanStyle JonCarnage KAPOW Kappa Keepo KevinTurtle Kippa Kreygasm KZskull Mau5 mcaT MechaSupes MrDestructoid MVGame NightBat NinjaTroll NoNoSpot noScope NotAtk OMGScoots OneHand OpieOP OptimizePrime panicBasket PanicVis PazPazowitz PeoplesChamp PermaSmug PicoMause PipeHype PJHarley PJSalt PMSTwin PogChamp Poooound PraiseIt PRChase PunchTrees PuppeyFace RaccAttack RalpherZ RedCoat ResidentSleeper RitzMitz RuleFive Shazam shazamicon ShazBotstix ShibeZ SMOrc SMSkull SoBayed SoonerLater SriHead SSSsss StoneLightning StrawBeary SuperVinlin SwiftRage tbBaconBiscuit tbChickenBiscuit tbQuesarito tbSausageBiscuit tbSpicy tbSriracha TF2John TheRinger TheTarFu TheThing ThunBeast TinyFace TooSpicy TriHard TTours UleetBackup UncleNox UnSane Volcania WholeWheat WinWaker WTRuck WutFace YouWHY

**Comment by CharlesIsOp** [comment] 2015-04-03 13:56
Metarmask Cheers to you, taking the time to type that out.

**Comment by cletusc** [comment] 2015-04-03 13:59
> personal BlackList

That still wouldn't block subscriber emotes unless you happen to add those too, but that's 20k+ (IIRC) emotes to add to the blacklist.

**Comment by CharlesIsOp** [comment] 2015-04-03 14:01
Very true. While at the same time if you dislike Emotes to that extreme- once you see a new one, you can just add it to the list.

**Comment by metarmask** [comment] 2015-04-03 14:04
> unless you happen to add those too
Here you go... hope it isn't too large...
`0krXorya 0kr0kr0shka galalaSB davidMACKERZ davidFILTH davidWEOW davidOSCAR davidSHEEP 0x33Rage 0x33Salute 0x33Kappa 0x33Ded 0x33Win 0x33Luv 0x33Alert 0x33GG oxaSombreor oxaCactus oxaMisha oxaCandySkip oxaYeezy oxaEva oxaDrian oxaBaka fowBUNS fowGJ fowHYPE fowSB fowRIOT fowB fowMLG fowTRAIN fowGAR fowPOW fowSD fowREADS fowPUNCH fowDUNK fowMISSED fowMG fowDEADLY fowHH fowHUNT fowEB 1gpikaSubhype 1gpikaChu 1gpikaGiveaway 1gpikaDevil 1gpikaAngel 1gpikaLove 1gpikaFeet insaneBaby insaneHype insaneGL insaneLove insaneKappa insaneRage insaneCash insaneChoo dosWink dosLankyHate dosDang dosPapoosed dosOhBanana dosInMyDay 2tvSUBHYPE 2tv2face 2tvEZSKINS 2tvECOCOBRA 2tvICECREAM 2tvGGWP 2tvWHY 2tvEZPZ 2mgLeo 2mgGoldy 2mgMask 2mgVern 2mgThirsty 2mgParty 2mgHype 2mgLove 2mgMVP 2mgPee 2mgRekt 2mgZesty 2mgRage 2mgKnife 2mgKKona 2mgSad 2kgChoke 2kgSub 2kgGez blueTea pooleSwisscheese pooleWho pooleHype poolePoints pooleA pooleTroll pooleOpenpack pooleSpin siqqRawr siqqPunch 3g1cLove 3g1cKappa 3g1cWayho 3g1cFail 3g1cHype 3g1cRekt 4gamersFISH 4gamersPHISHING 04sFACE 04sWHIP 04sSitdown 04sAGS 04sDDS 04s00 shizWook shizBOOP shizLoot shizSync shizAxe shizTetris shizFriendly shizSmile shizScience shizFoil shizNips shizCheese shizRng dgafSupNerd dgafGotEm dgafBlame5upa dgafKry 8bitSad 8bitYaass 8bitShady 8bitBye 8bitLava 8bitSlay 8bitShrekt 8bitHey ewrFrayjulance ewrSlenderPie ewrDieminionMode ewrHeLovesYou ewrSoTopTier ewrWhensMahvel ewrIkarugaSpam ewrPrepareToDie ddxFace ddxStorm tentabsCup tentabsWtf pointBM pointOphelia pointGasm klenispenM klenispenHest klenispenP12a klenispenK klenispenP klenispenZ 52arya52 52aryaWp 52aryaBeanie vskas FFs arthurS arthurA knochenTV knochenFace knochenFinger knochenRatsche knochenFrag knochenSchnitzel chrisFrankersaur chrisKiss chrisWOW chrisRIP chrisHi chrisEpic chrisPantsu chrisWTF chrisBoo chrisKarp grhPutin grhRage grhRekt grhSlip grhRIP 1437Midas 1437Lappa 1437Bro veriYeah veriGJ veri01 veriEz veriKing veri322 veriNicho veriLove gazSMm gazBronze gazKb gazRic feisusu1 alohaRIP alohaHype alohaYikes alohaTrumpet alohaREKT alohaGnome alohaAloha alohaRNG alohaDOOT alohaHeart alohaYeah alohaRisk alohaThump alohaSplit alohaSkirt aa9Real aa9Face aa9Booyah dapperKAPOI dapperSMITE dapperSHEEP dapperBADGE dapperTROLL abdouKappa abdouUmad abdouEye abdouBars abdouTrap abdouCrap abdouBBB abdouBoyz abdouCrit abeAstronaut abeHabibi ableMoo ableMark ableBrian ableCraig abmobCry abmobDiu lodEvil lodBoom lodCook lodBox lodRaughs absGold absRigged absLoveit absBert absInthe absRage absCry absPoint ludaFinn ludaStachio absoHalo abbyCake abbyRekt abbyMeme abbySkappa abbyJest abbyHeart abbyThump abbyWheel abzWTF abzSOFORT abzDUDEN abzX abzKATZE abzBAN acceNelson acceTata ggemoteOpenFire ggemoteAces ggemoteFire ggemotePeka acesCrate acesBomb acesKill acesHeart acesCard acesSoul acesFlare acesFist achesBG achesSR achesID achesSP achesBM achesBA achesMS achesWB undeadSkull undeadScythe undeadREKT undeadSalty undeadHYPE undeadGasm undeadGG undeadTaz undeadGTA undeadDiamond acoolLOL acoolAmelia acoolKoo acoolEZ acoolEasy acoolEA acouUdders acouHeart acouMurloc acouCookie acouGrill acouCup acouQQ acouScience acouHype acouFail bnaArmy bnaGrapeface bna1st bnaDog bnaBeanie bnaGasm bnaLiz bnaSuk bnaNrd bnaLove bnaScum bnaLurk bnaCry bnaRekt bnaHype actKobe actGuns actGasm actCry actRekt actRage actDance actWife actLove actSub apvpSkeet activKappa activHeart activFat activGlock activPls activHello activBelieve activFire activSlay activChoke adamTenderLove adamSmoothCriminal adamIBegYa adamApeSpit adamWololo adamAyy mathsquadWizard mathsquadBleh mathsquadRage mathsquadStoked adeZ adeS ade322 adeA adeK adeR adeT adeH rooShades rooSweet rooYe rooPrised rooRawr rooFlection rooRip rooD rooHype rooLewd rooRescue rooHoo rooGood rooLove rooPopcorn rooDone rooWhat rooPs rooSwiggity admiralS4 admiralFood admiralGasm admiralHappy admiralHYPE admiralKristin admiralDream admiralGame admiralHug admiralKappe admiralSexy tr4pwatKappa tr4pwatLeon tr4pwatJedi tr4pwatKatten tr4pwatSwag tr4pwatEliten adrShiny adrGuitar adrTkachu adrCheese adrHax adrZip adrSub adrLuck adrenLol adrenNailed adrenBond adrenMorg adrenDream adrenNuts adrenWhat adrenD adrenVac adrenL daurenEZ curryRap1 curryHatr curryHatL curryRap2 curryCat currySmoking curryKEEM curryFBRAD nagamimiMi adryanZOLWIK adryanHARDBASS adryanGIMBUS adumFace adumHmm adumCat coophs1 coophs2 coophs4 coophs3 adziokMurzyn adziokSpin adziokLaczek adziokBeng rekktFail rekktGosu rekktZaiko affeFail affeKackt affeBanana affeFeed affeBan affeSpinnt affeMad affeOo affHandsUp affFaceTime affMadNerd affAffiniDad affAffiniCat affMowDown afkHue afkLel`

**Comment by CharlesIsOp** [comment] 2015-04-03 14:08
That is quite i list; However, I do not think that is all of the sub emotes. 
Side note- If you do take the time to blacklist all of these; Make sure to back up your settings.

**Comment by metarmask** [comment] 2015-04-03 14:09
Yeah... they didn't fit. You will have to replace the linebreaks with space if you want to use the words from the site.

**Comment by night** [comment] 2015-04-30 13:37
Duplicate of https://github.com/night/BetterTTV/issues/85

**Closed by night** 2015-04-30 13:37 UTC
Labels: duplicate
