### ISSUE TITLE
Fix the theater mode bottom bar animation when hovering over video

### ISSUE THREAD

**Issue by btipling** [night/BetterTTV#506] opened 2015-06-19 16:51 UTC
It's really annoying when you hover over the video with your mouse because the video gets resized that way when the bottom bars with the controls animates into view. I think maybe if it were always hidden or shown it would be better than the video being resized. It could also be fixed by just showing the bar if you hover at the bottom instead of the video.

**Comment by night** [comment] 2015-06-20 08:55
Duplicate of #419

**Closed by night** 2015-06-20 08:55 UTC
Labels: duplicate
