### ISSUE TITLE
Split chat and emotes not working

### ISSUE THREAD

**Issue by jefy14** [night/BetterTTV#2967] opened 2018-02-10 00:08 UTC
Not much else to say, those two things are not working for me, I've already tried clearing my browsing data but nothing happened. 
![screenshot_1](https://user-images.githubusercontent.com/36316503/36055739-5cdbc5b4-0ddd-11e8-9e19-3fb4b808a2f5.png)
![screenshot_2](https://user-images.githubusercontent.com/36316503/36055740-5cfe8f36-0ddd-11e8-86a1-5e9fbb649d05.png)

**Comment by LollolGames** [comment] 2018-02-10 00:14
Having same problems. :c

**Comment by NarryG** [comment] 2018-02-10 00:20
Just broke for me as well. "Show Deleted Messages" is also not working.

**Comment by Khurune** [comment] 2018-02-10 02:59
This maybe down to twitch removing all legacy aspects of the site now. Only leaving us with the Legacy popout chat option which all chat features 'should' still work from. (All legacy chat extensions I've tried today are also broken and won't revert the chat back to legacy.)

**Comment by night** [comment] 2018-02-10 04:14
duplicate of #2963

**Closed by night** 2018-02-10 04:14 UTC
Labels: duplicate
