### ISSUE TITLE
Do it for microsoft edge

### ISSUE THREAD

**Issue by ShacoIsMyLife** [night/BetterTTV#1860] opened 2016-12-11 05:50 UTC
I'm a user of Chrome but with the update of edge for the extensions i want it in edge

**Comment by Stoupedog** [comment] 2016-12-11 06:06
Duplicate of https://github.com/night/BetterTTV/issues/1435

**Comment by EhsanKia** [comment] 2016-12-11 07:05
Does Microsoft Edge have Greasemonkey yet?

**Comment by Stoupedog** [comment] 2016-12-11 07:41
Oh yeah, looks like it does now. 👍 

@ShacoIsMyLife You can install BTTV on Edge through another extension called Greasemonkey, which you will first have to install from [here](https://www.microsoft.com/store/apps/9nblggh5162s).

Once you have that installed, you can install BTTV through tampermonkey. Go to https://nightdev.com/betterttv/, click 'for another browser' and click Userscript.

**Closed** 2016-12-13 03:45 UTC
Labels: duplicate
