### ISSUE TITLE
 Highlight Users

### ISSUE THREAD

**Issue by dragonx2x1** [night/BetterTTV#2068] opened 2017-02-14 07:17 UTC
It would be nice to have a way to set certain users to a chosen highlighted color, that way as you get to know people in a stream, you can categorize users by for instance trolls, helpful people, spammers, etc...

**Comment by AlcaDesign** [comment] 2017-02-14 23:13
This could be useful **and** aesthetic if only the usernames were colored based on the category.

**Comment by dragonx2x1** [comment] 2017-02-15 04:08
Exactly.

**Comment by night** [comment] 2017-02-19 11:01
duplicate of #237

**Closed by night** 2017-02-19 11:01 UTC
Labels: duplicate
