### ISSUE TITLE
Chat slow mode/timeout indicator

### ISSUE THREAD

**Issue by sparcut** [night/BetterTTV#2726] opened 2017-10-18 10:23 UTC
Would be great to have a progress countdown circle, bar etc. to show when you can type again in chats in slow mode or after being timed out.

Adding a timeout progress indicator should be easy, not sure about chat timeout, prob stored in state. 

YouTube live has a similar feature that uses a circle progress bar and disables send message

**Comment by night** [comment] 2017-12-18 03:22
duplicate of #2392

**Closed by night** 2017-12-18 03:22 UTC
Labels: duplicate
