### ISSUE TITLE
Since the new update, personal BTTV emotes are not working

### ISSUE THREAD

**Issue by PoppySins** [night/betterttv#4799] opened 2021-09-12 22:14 UTC
I have subbed to BTTV for ages, and I now have 21 personal bttv emotes I cannot use since the latest update. This feature is 99% of why I subscribe to this feature and I am looking for a fix so that I can use the emotes I am so used to having.

**Comment by dclstn** [comment] 2021-09-12 22:23
dupe of #4798,

Sorry for the inconvenience

**Comment by night** [comment] 2021-09-13 16:55
This is fixed in v7.4.1 and higher

**Closed by night** 2021-09-13 16:55 UTC
Labels: duplicate
