### ISSUE TITLE
[Feature Request] Disable channel point features (emotes, colorization, pop-ups)

### ISSUE THREAD

**Issue by wnslx** [night/BetterTTV#3650] opened 2019-11-12 17:41 UTC
I find these features very annoying, spammy and obtrusive. I tried to ask twitch support if they would allow viewer side disabling of channel point features but didn't get any response. AFAIK only the streamer/channel owner can control these features on their channel and the viewer can do nothing to filter out the color spam.

**Comment by night** [comment] 2019-11-18 06:40
duplicate of #3634

**Closed by night** 2019-11-18 06:40 UTC
Labels: duplicate
