### ISSUE TITLE
Tab completion of emotes not working

### ISSUE THREAD

**Issue by uwoflyer** [night/betterttv#7055] opened 2024-09-28 17:24 UTC
### Describe the bug

Tab completion of Twitch emotes has stopped working within the past week or so.

### Steps to reproduce

1. Begin to type out an emote
2. Hit tab

### Expected behavior

Before, when you hit tab after beginning to type an emote, it would fill the remainder of the emote text. Having emote completion over username enabled doesn't change anything. This issue with tab completion seems to only be with Twitch emotes as BTTV emotes still work this way.

### Screenshots

![chrome_eUEl5wBIDa](https://github.com/user-attachments/assets/536a1c58-5ed4-4828-bf6c-fb7156b30840)

### Device information

Device: PC
OS: Windows 11
Browsers: Google Chrome and Mozilla Firefox

Chrome version 129.0.6668.71
Firefox version 130.0.1

### BetterTTV Version

7.6.6

### Additional information

I believe it worked roughly last week, so it is a recent problem.

I also have uBlock Origin, Picture-in-Picture extension (by Google), Twitch Ad Muter, and Privacy Badger extensions installed and active when on Twitch pages on Chrome.

On Firefox, I only have uBlock Origin and BTTV enabled.

I've disabled uBlock to see if that was where the problem occurs, but it doesn't fix it.

### Version Check

- [X] I have checked that I'm using the newest version of BetterTTV available.

**Comment by night** [comment] 2024-09-28 17:42
duplicate of #7053

**Closed** 2024-09-28 17:42 UTC
Labels: bug, duplicate
