### ISSUE TITLE
Optional "Reason" box for moderators

### ISSUE THREAD

**Issue by Nilesy1** [night/BetterTTV#1398] opened 2016-07-25 09:54 UTC
Hey there.

I would like to request a feature for BTTV.

On Twitch, as moderators, we can provide a reason for timing out/banning. However, when using the timeout 1 hr / 8 hr / 24 hr / permaban options this simply issues a timeout/ban with no reason.

I would like to request an optional setting which can be toggled on/off which pops up a dialogue box for moderators to quickly type in why a timeout/ban was issued. This would assist in situations where users ask for unbans and logs do not show reasons for initial ban. This would also allow moderators to tag bans so logs can show who issued the ban/timeout, which makes it easier to discusses unbans.

Thanks for reading.

**Comment by night** [comment] 2016-07-27 07:27
duplicate of #1246

**Closed by night** 2016-07-27 07:27 UTC
Labels: duplicate
