### ISSUE TITLE
BetterTTV Feature Request

### ISSUE THREAD

**Issue by Ryku** [night/BetterTTV#535] opened 2015-07-04 02:02 UTC
When in theater mode, if your mouse is not on the actual stream itself, it is large. However, if you move your mouse over the stream, it moves it upwards and distorts it slightly, and undoes it again if you move your cursor off. An idea for a feature is to make the stream to stay a solid size even if your cursor is not on it.

**Comment by night** [comment] 2015-07-04 02:57
Duplicate of #419

**Closed by night** 2015-07-04 02:57 UTC
Labels: duplicate
