### ISSUE TITLE
Anon chat doesn't log out on page load

### ISSUE THREAD

**Issue by Itaku** [night/BetterTTV#2473] opened 2017-05-21 21:06 UTC
Anon chat doesn't log you out of chat on page load right now, stops you from chatting in chat still saying you can't talk in anon chat mode. Also makes you show up in the viewer list too.

**Comment by Nareese** [comment] 2017-05-22 00:51
duplicate of #2402

It is a known issue and is in the queue to be investigated and worked on. As mentioned in that issue, you can work around it by turning anon mode off and on again while in the chat you wish to be anonymous in. Note that because of caching, it may take up to 2 minutes before you disappear off the user list.

**Closed** 2017-05-22 18:35 UTC
Labels: duplicate
