### ISSUE TITLE
hovering subscriber emotes doesn't show the channel anymore

### ISSUE THREAD

**Issue by evodoc** [night/BetterTTV#3001] opened 2018-02-26 03:40 UTC
Before there was a feature that hovering emotes would also show the channel not just the string and it linked the channel to the emote (clicking it would open that channel's page).

**Comment by Nareese** [comment] 2018-02-26 04:24
duplicate of #2939 (the click issue is also related to the same issue).

**Closed** 2018-02-26 04:25 UTC
Labels: duplicate
