### ISSUE TITLE
Add setting to not freeze chat on meta

### ISSUE THREAD

**Issue by cathrinevaage** [night/betterttv#4197] opened 2020-10-16 19:06 UTC
This is a feature request for adding setting for disabling the feature that pauses chat scroll when you click the meta key.
On a mac, the cmd key is the meta key. Unlike on windows with `alt + tab`, the hotkey to switch between programs, is `cmd + key`. This causes the the chat to be paused quite frequently, and without intention.

**Comment by jcrippen** [comment] 2020-11-16 00:59
I get the “Chat paused due to scroll” from pressing `ctrl`. I have some keyboard shortcuts with this and they constantly pause chat when I don’t want them to. I’d also appreciate being able to disable this feature.

**Comment by night** [comment] 2020-11-17 08:02
duplicate of #4181

**Closed by night** 2020-11-17 08:02 UTC
Labels: duplicate
