### ISSUE TITLE
Welcome message

### ISSUE THREAD

**Issue by CravingGaming** [night/BetterTTV#642] opened 2015-08-11 21:53 UTC
I think it will be a great idea for us to have a "welcome message" or "host message" when you join a stream. Instead of seeing "Welcome to CravingGaming's Chat Room" we could see this by example? http://prntscr.com/83jqvf This could be in our dashboard or our chat settings?

**Comment by night** [comment] 2015-08-11 23:11
Duplicate of #363

**Closed by night** 2015-08-11 23:11 UTC
Labels: duplicate
