### ISSUE TITLE
Re-open issue: Automatic theater mode stopped working

### ISSUE THREAD

**Issue by R1dyk** [night/betterttv#5417] opened 2022-05-31 23:08 UTC
@night Hey, sorry no other way for me to contact you. 

This issue #5361, has definitely not been resolved as several users including me are continuing to experience the bug still. I strongly recommend looking into this issue again.

Feel free to delete this one afterwards.

Thank you.

**Comment by night** [comment] 2022-06-06 04:39
Thanks for the feedback. Can you reply with a video demonstrating how to reproduce this behavior? I cannot see this locally.

**Comment by Kotaless** [comment] 2022-06-06 09:58
> Thanks for the feedback. Can you reply with a video demonstrating how to reproduce this behavior? I cannot see this locally.

Hello. Hope this helps.
https://user-images.githubusercontent.com/9118532/172138973-beacba25-11dc-461c-b85a-7b296a693c83.mp4
It works when the page refreshed or if I open the stream via left bar.

**Comment by R1dyk** [comment] 2022-06-06 11:26
For me it behaves a bit differently. Theatre mode pops for a second and closes right away. 

https://imgur.com/VlPEi0i

It doesn't show on the video, but as @Kotaless mentioned, it WORKS when opened via left sidebar.

**Comment by adamcmain** [comment] 2022-06-08 19:42
Same thing happening to me.  
1. Go to https://www.twitch.tv/directory/following
2. Click on one of the live channels
3. Page tries to load into theater mode
4. Page exits theater mode automatically after a second or so.

**Comment by Kotaless** [comment] 2022-07-14 17:56
I created this script as a workaround. It's not perfect but useable.
https://greasyfork.org/en/scripts/447861-twitch-auto-theatre-mode/code

**Comment by night** [comment] 2022-07-18 01:23
duplicate of #5415

**Closed by night** 2022-07-18 01:23 UTC
