### ISSUE TITLE
General Issues, 500 and 404 errors, BTTV FFZ emote integration not showing up when Enabled.

### ISSUE THREAD

**Issue by Vafarien** [night/BetterTTV#3433] opened 2019-04-09 05:27 UTC
FFZ emotes have stopped loading within the past 24hrs
500 errors
and 404 errors in Chrome Dev console:
![image](https://user-images.githubusercontent.com/2349950/55774964-2cf85f80-5a4c-11e9-8ae0-1200d7dfc39c.png)
![image](https://user-images.githubusercontent.com/2349950/55774997-4ef1e200-5a4c-11e9-823e-5ba004fc182e.png)
Seems to only affect some users, other people in chat are using FFZ emotes that i can't view, Because the FFZ doesn't even load: (even when enabled in BTTV setting)
usually the FFZ emotes would show up here:
![image](https://user-images.githubusercontent.com/2349950/55775095-b314a600-5a4c-11e9-894b-c1e5ca64a814.png)
but i guess 500 error is stopping the server from loading the emotes?
![image](https://user-images.githubusercontent.com/2349950/55775125-db9ca000-5a4c-11e9-9c5b-a4ac794d0cad.png)

Google Chrome is up to date: Version 73.0.3683.103 (Official Build) (64-bit)
Windows 7 64-bit Home Pro
BTTV Chrome Exstension: 7.2.1 (ID: ajopnjidmegmdimjlfnijceegpefgped)

**Comment by Vafarien** [comment] 2019-04-09 05:32
Trying to connect to channel emote manager also is having trouble connecting and trying too many times?
![image](https://user-images.githubusercontent.com/2349950/55775417-17843500-5a4e-11e9-85f3-799d9044dc23.png)
oh and this i guess?
![image](https://user-images.githubusercontent.com/2349950/55775444-2b2f9b80-5a4e-11e9-90a9-9cb91d4efbdf.png)

**Comment by night** [comment] 2019-04-09 07:03
duplicate of #3429

**Closed by night** 2019-04-09 07:03 UTC
Labels: duplicate
