### ISSUE TITLE
[Feature Request] Force chat under player

### ISSUE THREAD

**Issue by grgsimonnet** [night/betterttv#4304] opened 2021-01-04 21:46 UTC
I know this was already discussed in #4074 . However when watching in theatre mode and shrinking the window, the chat now automatically slides bellow player :
![Image of Yaktocat](https://i.ibb.co/pWC2Gq0/twitch.png) 
The problem is that this only happens when browser width is lower than about 950px (I have 1440p screen) and I wish this could be forced when placing 2 streams side by side so width ~1280px. Twitch might have changed something since the issue got closed, I'm not sure but this could be worth checking cause I think it would really be a cool upgrade !

**Comment by night** [comment] 2021-03-14 23:49
duplicate of #4074

**Closed by night** 2021-03-14 23:49 UTC
Labels: duplicate
