### ISSUE TITLE
no chat when i first come into a stream

### ISSUE THREAD

**Issue by animorph127** [night/BetterTTV#2045] opened 2017-02-08 06:26 UTC
**ok for the past two months every time i go into a stream there is no chat. I an sit there for a long period of time and still no chat, thus causing me the need to reload. When i reload the chat is back and i can see people talking again like i should. Does anyone else have this problem? Because it's rather annoying to constantly needing to refresh when i join a channel. And i've brought this up at least one other time and got completly ignored**

**Comment by Bren002** [comment] 2017-02-09 02:36
same

**Comment by Trubbel** [comment] 2017-02-11 18:43
I have the same thing and it's been like that for a long time now. Basically all I see is;
> "BetterTTV v6.8 Loaded.
>  Welcome to <streamer>'s chat room!"

And after this I either see people subscribing or getting timed out, until I refresh the page to get chat to work again.

**Comment by animorph127** [comment] 2017-02-11 19:11
yup pretty much exactly it

**Comment by night** [comment] 2017-02-19 11:07
duplicate of #1898

**Closed by night** 2017-02-19 11:07 UTC
Labels: duplicate
