### ISSUE TITLE
Stop button and playlists

### ISSUE THREAD

**Issue by antyone** [night/BetterTTV#2243] opened 2017-04-07 20:44 UTC
If the stream is live and I wanna pause it, it will do so.

But my problem is with playlists, because once any streamer finishes a stream and starts a playlist, it will automatically play it, even though I stopped the stream and didn't want to watch.

There is no option to block playlists from automatically playing, if I click the pause/stop button to stop the stream, I want it to stay that way and not start a frigging playlist when I'm doing something else on another monitor.

It's the same with hosts once somebody stops streaming, but at least that option is in the settings and you can block any hosting done by channels.

Please add an option to disable automatic playlists when somebody stops streaming.

**Comment by night** [comment] 2017-04-10 22:41
duplicate of #1996

**Closed by night** 2017-04-10 22:41 UTC
Labels: duplicate
