### ISSUE TITLE
Highlights on following page

### ISSUE THREAD

**Issue by Mattstar11** [night/BetterTTV#1313] opened 2016-06-26 10:29 UTC
Since the most recent update the highlights section below the people you follow that are live has disappeared and a "based on your viewing history" has appeared. From what I can tell no one likes this and I hate it as well, so I think a highlights only option should be an option. Thanks for the great work you guys have already done and hope to see some new stuff soon.

**Comment by night** [comment] 2016-06-27 00:48
duplicate of #1311

**Closed by night** 2016-06-27 00:48 UTC
Labels: duplicate
