### ISSUE TITLE
Live Stream Pauses When Clicked on

### ISSUE THREAD

**Issue by thsie004** [night/BetterTTV#1639] opened 2016-10-10 07:49 UTC
Whenever I click on a live stream player, the stream pauses. After pausing and resuming twice, the players blacks out playing only audio no matter how many times I pause and resume. I have to reload the page to view the stream again, and disabling BTTV completely removes this bug.

**Comment by Senpos** [comment] 2016-10-10 08:10
It happens to me sometimes, but not that often. Can confirm, that Play/Pause on click feature is not useful for all users and could be great to see option to disable it in BTTV.

**Comment by thinkpad4** [comment] 2016-10-10 08:15
There is one now

**Comment by Senpos** [comment] 2016-10-10 08:22
@thinkpad4 Oh wow, true. Thanks.

**Comment by thsie004** [comment] 2016-10-10 08:23
Okay, if my memory serves right, in my months of using BTTV this feature has been off, yet it magically turned itself on today. Anyways, thank you.

**Comment by voloshink** [comment] 2016-10-10 08:36
@thsie004 this feature has just been added and it's on by default.

**Comment by voloshink** [comment] 2016-10-10 08:39
duplicate of #1635

**Comment by voloshink** [comment] 2016-10-10 08:40
Actually this is slightly different, so i guess i'll leave this on. This bug is caused by clicking the play button in the middle of the video play.

**Comment by DAOWAce** [comment] 2016-10-10 16:26
I saw something similar when I was accidentally pausing the stream every time I focused my other monitor.

It would randomly break and require a page reload.

Finally found out the pause thing was a BTTV 'feature' (ugh) and not something Twitch did. Haven't tested this specific issue after disabling it, so I don't know if it's been fixed or not.  Won't until later tonight.

**Comment by night** [comment] 2016-10-12 17:17
Bug is being followed up in #1639

**Closed by night** 2016-10-12 17:17 UTC
Labels: invalid
