### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Lucas559-noob** [night/betterttv#4107] opened 2020-08-24 03:49 UTC
When the streamer does a marbles on stream or another streamer has a mini game in their bots, after a number of comments it will send an automatic message for me
e.g. Chat is "spamming" `!heist 1000` and the extension will get if something like heist was sent in the chat, it will send after x messages an automatic message with a personalized message.
Anti-spam: in the twitch, you will see many people saying 1, 2, 3 or other commands, but for people in the chat they can see it, so when x numbers of the same message are sent, it will start blocking other messages with the same word.
A different color for the deleted messages, many times it is a little difficult to see the message because it is a little more transparent than the others, so you could change the background or the font color.

**Comment by night** [comment] 2020-08-30 11:26
duplicate of #1922

**Closed by night** 2020-08-30 11:26 UTC
Labels: duplicate
