### ISSUE TITLE
change chat highlighting color

### ISSUE THREAD

**Issue by Umbozz** [night/BetterTTV#1050] opened 2016-04-01 00:14 UTC
a more subtle highlight color would work just fine, the red can make text hard to read sometimes and it stands out a bit too much (which is the point, but it is a but hard on the eyes, imo).
a quick search brought up that you had this request submitted before (#984, maybe more), but closed it due to a lack of popularity. i wish to express my support for this idea.

**Comment by ConditionOfMan** [comment] 2016-04-01 02:33
I support this request. A customizable highlight color would be ideal.

**Comment by night** [comment] 2016-04-01 03:18
duplicate of #237

**Closed by night** 2016-04-01 03:18 UTC
Labels: duplicate
