### ISSUE TITLE
Highlight My Message

### ISSUE THREAD

**Issue by billysielu** [night/BetterTTV#3702] opened 2019-12-23 15:03 UTC
The "Highlight My Message" feature of Twitch Chat:

1. I would like an option to hide highlighted messages. It's particularly annoying when chat decides to spam it.

2. The "Clear My Chat" function does not fully clear the "Redeemed Highlight My Message" messages.
![image](https://user-images.githubusercontent.com/59173811/71364882-54b93480-2595-11ea-9126-c0995dff9f10.png)

**Comment by night** [comment] 2019-12-23 19:45
duplicate of #3634

**Closed by night** 2019-12-23 19:45 UTC
Labels: duplicate
