### ISSUE TITLE
Ignore a user bug

### ISSUE THREAD

**Issue by Eywyn** [night/BetterTTV#2501] opened 2017-06-05 02:27 UTC
When you click on the nickname of a user and then click ignore, there's no pop up to tell the reason of the ignore: spam, hate speech, abuse, etc... Twitch has this but it works only without BTTV. Not sure if it's a pop-up but I'm a 100% sure this feature exists.

![image](https://cloud.githubusercontent.com/assets/29188924/26768455/5b6c5436-49a8-11e7-8c69-07b55663206e.png)

**Comment by Nareese** [comment] 2017-06-05 03:53
Confirmed.  There is indeed now a popup when ignoring a user without BTTV enabled.  It appears to be a variant of the Report function, with a very limited selection of reasons (Spam, Harassment, Other) on a dropdown.  You must select one of these options and hit send before the user is placed on ignore.  Leaving the dropdown on "Select one..." and hitting send prompts that it is required, and closing the popup leaves the user unignored.

BTTV completely re-implements the "modcard" (the panel shown above), so it would probably be somewhat difficult to configure BTTV's ignore button to call twitch's report popup anyway.

That said, however, personally, I consider it a feature that BTTV bypasses this popup and I would be very opposed to BTTV re-implementing it.  Most times (99%+), I just want to put a user on ignore because I find them annoying, not because they've actually done anything that warrants reporting them to twitch for "investigation".  If they've really done something worthy of reporting, the report function still exists on their channel page, with a much more granular list of reasons.  This should require additional steps to access, to discourage frivolous reporting.  If this feature is "fixed", I would request that there is an option to disable it and restore the previous BTTV functionality of allowing users to be ignored without reporting them.

**Comment by night** [comment] 2017-06-10 22:57
This was investigated a long time ago, but there wasn't an easy way to trigger twitch's ui. this is a wontfix.

**Closed by night** 2017-06-10 22:57 UTC
Labels: cantfix
