### ISSUE TITLE
Suggestion - Allow disabled emotes to show up in search results.

### ISSUE THREAD

**Issue by RaidinD** [night/betterttv#5802] opened 2022-12-16 23:58 UTC
As the title says, allow emotes that we upload but don't have enabled in our channels to still appear in search results.

Example scenario: 

- A user wants to add a specific emote.
- The user cannot find it, since it is hidden due to the original creator not having it enabled in their own chat (even with sharing turned on).
- The user has to either reupload the emote OR if they know the original person who uploaded it, ask them to enable it in their channel (which may or may not be possible as the creator may have ran out of slots)

This makes having disabled emotes effectively useless since no one can add them even with sharing turned on in the properties. Since people who don't immediately find an emote they're looking for could easily upload another variation of it, creating more duplicates in the process.

Allow us to upload emotes, not have them enabled in our own channels but still be publicly available in the search results.

**Comment by night** [comment] 2022-12-24 05:17
This would be considered a duplicate of #5698

**Closed by night** 2022-12-24 05:17 UTC
Labels: duplicate
