### ISSUE TITLE
Having problem with dark theme

### ISSUE THREAD

**Issue by klocek1234** [night/BetterTTV#3219] opened 2018-08-22 21:05 UTC
After turning on dark theme in setting I have like white and black chat fragments. 
for example https://i.imgur.com/KaDqemX.png

**Comment by xFirez** [comment] 2018-08-22 21:17
Same.

**Comment by fossilz** [comment] 2018-08-22 21:38
This is an old bug re-surfacing. If you turn off Split Chat in the settings it should be ok until it's fixed.

**Comment by derpyderpaderp** [comment] 2018-08-22 21:50
Can confirm this being an issue.

**Comment by Nareese** [comment] 2018-08-22 22:32
duplicate of #3216

**Closed** 2018-08-23 03:01 UTC
Labels: duplicate

**Comment by klocek1234** [comment] 2018-08-23 09:53
thx
