### ISSUE TITLE
Option to disable certain global BTTV emotes

### ISSUE THREAD

**Issue by orangecarnation** [night/betterttv#5526] opened 2022-07-21 16:27 UTC
For example, I personally don't really like the D: one.  But I don't want to _completely_ disable BTTV emotes, because there's ones that I _really, really_ like.  So the option to opt out of a few would be great !

**Comment by night** [comment] 2022-10-01 02:29
duplicate of #85

**Closed by night** 2022-10-01 02:29 UTC
Labels: duplicate
