### ISSUE TITLE
BTTV can't work on the chat room

### ISSUE THREAD

**Issue by zhong090** [night/BetterTTV#2474] opened 2017-05-22 00:31 UTC
What if BTTV doesn't work on the chat room? I have the TWITCH plus BTTV icon in the upper left corner of my page, but BTTV doesn't work on the chat room. In the personal settings BTTV option, the BTTV SETTING page is blank.

**Comment by zhong090** [comment] 2017-05-22 00:33
![133333](https://cloud.githubusercontent.com/assets/28836310/26288662/45d81798-3ec9-11e7-98a7-38b4c932ac84.jpg)

**Comment by night** [comment] 2017-05-22 18:34
duplicate of #2464

**Closed by night** 2017-05-22 18:34 UTC
Labels: duplicate
