### ISSUE TITLE
Left Side Chat and Chrome Firefox

### ISSUE THREAD

**Issue by Discostoff** [night/betterttv#4245] opened 2020-11-27 21:02 UTC
Left side chat and google chrome, firefox does weird things with the video.
I had left side chat for some time already - worked, but for some reason my screen is broken since ca. 3 days. 
https://i.imgur.com/fOLqIlM.png

**Comment by Nareese** [comment] 2020-11-27 22:00
Duplicate of #4243

**Closed** 2020-11-28 20:55 UTC
Labels: duplicate
