### ISSUE TITLE
Better Viewer List Bug

### ISSUE THREAD

**Issue by Deakula** [night/BetterTTV#2485] opened 2017-05-28 03:07 UTC
When using the Better Viewer List option with any amount of viewers in a Twitch channel, after scrolling down a bit, the scroll bar auto scrolls to the bottom of the viewer list making it impossible to view most of the users in chat. This makes it exceptionally difficult for mods to find user that needs to be moderated in a chat.

**Comment by Nareese** [comment] 2017-05-28 04:23
duplicate of #2269 

As mentioned in that issue, you can use the search box to narrow down the list to find specific users until this can be fixed.

**Closed** 2017-05-28 04:47 UTC
Labels: duplicate
