### ISSUE TITLE
Some animated emotes ghosting on Twitch

### ISSUE THREAD

**Issue by TheIdealCopy** [night/betterttv#6476] opened 2023-11-14 15:15 UTC
### Describe the bug

Certain animated emotes - seemingly ones which contain a wider a range of movement - have been leaving static remnants of previous frames behind for a few weeks now. Nothing I've done in settings, deleting & reinstalling BTTV, clearing my browser cache etc has had any effect. It's not the biggest issue but it is a bit of a pain so if there's a way of fixing it then I'd be grateful to find out what it is!

### Steps to reproduce

Type : [emoteName] into chat to bring up the preview. A couple of examples of affected emotes I've found are BIGFROG, SteerR and TeaTime.

### Expected behavior

Both in the preview window and in chat once a message containing an affected emote has been sent, static remnants of a single frame will remain in place around the edges of the emote as it animates.

### Screenshots

<img width="53" alt="Screenshot 2023-11-14 at 15 03 47" src="https://github.com/night/betterttv/assets/150825257/e845f1d3-e1bc-4029-aa1c-ee265cc6fabe">
<img width="36" alt="Screenshot 2023-11-14 at 15 02 24" src="https://github.com/night/betterttv/assets/150825257/9e04ae4d-cdc8-41c6-aec1-bbc4ad36f3d6">
<img width="49" alt="Screenshot 2023-11-14 at 15 03 21" src="https://github.com/night/betterttv/assets/150825257/cade45e9-fe98-4515-bd1f-142725bfa80e">

### Device information

MacBook Pro M1 running MacOS Ventura 13.4, on Safari version 16.5. Bug also occurs on current versions of Chrome and Firefox on the same machine.

**Comment by TheIdealCopy** [comment] 2023-11-14 17:51
Just upgraded to Sonoma and the issue is still present.

**Comment by TheIdealCopy** [comment] 2023-11-14 18:28
Still there. Not sure if this is worth mentioning but the issue started happening mid-session, and when I wasn't doing anything else in other tabs or windows. I was watching a stream and in the space fo a couple of minutes between sending messages the issue appeared seemingly without cause.

**Comment by night** [comment] 2023-11-14 18:48
I am not able to reproduce any issues on Chrome/Firefox but there does seem to be bugs in Safari's WebP implementation regarding transparency: https://bugs.webkit.org/show_bug.cgi?id=217897

Namely, it looks like background disposal for transparent backgrounds is not working properly, and is why you're seeing remaining data after a frame change.

You may need to use Chrome or Firefox instead unless we add an option for Safari to render GIFs rather than WEBPs.

**Comment by TheIdealCopy** [comment] 2023-11-14 19:15
I'll uninstall and reinstall them and try again then. Thanks for getting to the bottom of this for me - as I said it's not experience-ruining but it is a PITA. I know Apple hates WEPBs for some reason (much like FLAC audio, still 🙄) so it doesn't surprise me that this issue lies squarely with them.

**Comment by night** [comment] 2023-11-28 16:52
closing this since it appears to be an upstream bug with WebKit

**Closed by night** 2023-11-28 16:52 UTC
Labels: bug
