### ISSUE TITLE
hide request muted audio popup/frame notification at VODs

### ISSUE THREAD

**Issue by Daisenki** [night/BetterTTV#3122] opened 2018-05-26 12:17 UTC
Is it possible to hide the muted audio popup/frame(?) notification on VODs?

"Audio for portions of this video has been muted as it appears to contain copyrighted content owned or controlled by a third party." 

It appears on every VOD with muted audio and is annoying.

**Comment by night** [comment] 2018-05-29 01:58
duplicate of #1764

**Closed by night** 2018-05-29 01:58 UTC
Labels: duplicate
