### ISSUE TITLE
Emote Menu not working

### ISSUE THREAD

**Issue by Mxcixs** [night/BetterTTV#3492] opened 2019-07-02 01:16 UTC
The BetterTTV emotes are showing in chat, but the menu to use them is not appearing.

**Comment by itsazhuhere** [comment] 2019-07-13 06:15
@night I did some digging and this is reproducible whenever the viewer list button that usually appears next to the settings button in the bottom right fails to load.  [From this line](https://github.com/night/Userscript--Twitch-Chat-Emotes/blob/master/src/modules/ui.js#L83) we see that Twitch Chat Emotes attempts to load the emote menu button after the viewer list button but fails because that button doesn't exist, so it never attaches. 

If I open twitch up in an incognito window, the viewer list button shows up again and therefore the emote menu attaches correctly.  I don't know why this is the case but either way it can be fixed by adding the emote menu button after the settings button if the viewer list button doesn't exist, or by adding the emote menu button to the end of the container of all these buttons.

**Comment by night** [comment] 2019-07-13 20:00
duplicate of #3487

**Closed by night** 2019-07-13 20:00 UTC
Labels: duplicate
