### ISSUE TITLE
Set animated emotes as static images

### ISSUE THREAD

**Issue by 420Seeker** [night/betterttv#4940] opened 2021-10-17 15:35 UTC
![Screenshot 2021-10-17 102410](https://user-images.githubusercontent.com/92682981/137634273-3ea86baf-b44d-4e8f-acfd-2e5df0ac5b9d.png)
Like the FrankerZ control center, this is a great option to have.

**Comment by night** [comment] 2022-10-01 02:26
duplicate of #4657

**Closed by night** 2022-10-01 02:26 UTC
Labels: duplicate
