### ISSUE TITLE
Anon Chat is not working anymore.

### ISSUE THREAD

**Issue by iBombe** [night/BetterTTV#3523] opened 2019-08-03 01:24 UTC
It never worked like a charm for me but since yesterday its not working anymore at all.

**Comment by FastMovingBrick** [comment] 2019-08-05 04:44
Same issue. Tried all the solutions that have previously worked, still not working

**Comment by night** [comment] 2019-08-05 08:32
duplicate of #3506

**Closed by night** 2019-08-05 08:32 UTC
Labels: duplicate
