### ISSUE TITLE
Left Side Chat Displays Followed Channels in Theater Mode

### ISSUE THREAD

**Issue by jk102393** [night/betterttv#4049] opened 2020-07-15 20:57 UTC
When "Left Side Chat" is toggled on, the Followed Channels bar still appears when going into theater mode. It also stays on the left side. Normally the followed channels bar is on the right when chat is on the left. Now its on the left, alongside the chat, and I can't get it to go away. It causes the chat to cover up part of the stream as well.

**Comment by night** [comment] 2020-07-19 23:05
duplicate of #4044

**Closed by night** 2020-07-19 23:05 UTC
Labels: duplicate
