### ISSUE TITLE
Disable Homepage Autoplay not working

### ISSUE THREAD

**Issue by Amleto** [night/BetterTTV#3164] opened 2018-06-30 22:28 UTC
In bttv settings I have 'Disable Homepage Autoplay - ON'.

When I go to https://www.twitch.tv/ the central feed in the 'roulette' plays.

BetterTTV v7.2.30

I'm using firefox 61.0 (64-bit). Trouble shooting info:
```
Name | Firefox
-- | --
61.0
20180621125625
Show Update History
release
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0
Windows_NT 10.0
Open Folder                                C:\Users\***\AppData\Roaming\Mozilla\Firefox\Profiles\59kkyzr3.default
about:plugins
about:buildconfig
about:memory
about:performance
about:serviceworkers
1/1 (Enabled by default)
5/4
Inactive
Found
Found
false
about:profiles
```

**Comment by Nareese** [comment] 2018-07-01 02:51
duplicate of #3157

**Closed** 2018-07-08 12:02 UTC
Labels: duplicate
