### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by LMyers31** [night/BetterTTV#1453] opened 2016-08-16 07:52 UTC
Hello BetterTTV, I would love a feature that allows you to move the chat to the left margin of your screen. This may already be an option and I'm just blind, but I feel it would be very useful when watching in theater mode on a right sided secondary monitor.

**Comment by Stoupedog** [comment] 2016-08-17 11:50
duplicate of #202

**Closed** 2016-08-20 03:51 UTC
Labels: duplicate
