### ISSUE TITLE
Change Twitch Design Feature

### ISSUE THREAD

**Issue by Turksoldier** [night/BetterTTV#2583] opened 2017-07-19 18:23 UTC
It would be nice to change the whole appearance of Twitch like in Better Discord. 
I saw a program on reddit which allowed you to connect to a channel and change the skin of the chat ... BUT you can't write in the "chat" and its a bit buggy. It's called "ChatGameFontificator"

**Comment by night** [comment] 2017-07-30 18:42
duplicate of #658

**Closed by night** 2017-07-30 18:42 UTC
Labels: duplicate
