### ISSUE TITLE
Sync BTTV settings

### ISSUE THREAD

**Issue by breon** [night/BetterTTV#1643] opened 2016-10-11 02:07 UTC
I use BTTV on a few computers. It seems that I can't remember to get all my settings, keywords, etc on each device. I would love to be able to save my settings config to Google Drive (or Dropbox) so that changes on one computer are synced to all of my computers.

**Comment by night** [comment] 2016-10-12 17:15
duplicate of #766

**Closed by night** 2016-10-12 17:15 UTC
Labels: duplicate
