### ISSUE TITLE
Settings translation

### ISSUE THREAD

**Issue by LexHyro** [night/BetterTTV#3527] opened 2019-08-04 14:43 UTC
It would be great for non-English-speaking users. My native language is Russian, I can translate settings to it. CIS segment(which mostly speaks Russian online) has good viewer numbers so this tiny upgrade can help widen BTTV audience.
I guess translating settings to asian languages would do even more.

**Comment by night** [comment] 2019-08-05 06:43
we'd love to one day.

duplicate of #2728

**Closed by night** 2019-08-05 06:43 UTC
Labels: duplicate
