### ISSUE TITLE
BetterTTV Not Working

### ISSUE THREAD

**Issue by therussianpyro** [night/BetterTTV#3780] opened 2020-03-09 23:23 UTC
![image](https://user-images.githubusercontent.com/61995889/76265586-5660d300-623b-11ea-97c4-7781c183fbfb.png)

![image](https://user-images.githubusercontent.com/61995889/76265623-70021a80-623b-11ea-8dca-95ed1b563458.png)

**Comment by night** [comment] 2020-03-09 23:38
duplicate of #3778

**Closed by night** 2020-03-09 23:38 UTC
Labels: duplicate
