### ISSUE TITLE
Unable to see highlighted and pinned @mentions

### ISSUE THREAD

**Issue by kryvn** [night/BetterTTV#3327] opened 2018-12-11 01:56 UTC
Just today I am unable to see @/messages. I've checked my bttv settings and made sure my username is in the highlighted words list. I've also asked others and they also have the same problem. Hope to hear back soon.

**Comment by samfun123** [comment] 2018-12-11 02:59
Duplicate of #3325

**Closed** 2018-12-11 04:39 UTC
Labels: duplicate
