### ISSUE TITLE
Switchable chat location

### ISSUE THREAD

**Issue by edge226** [night/BetterTTV#408] opened 2015-05-11 08:46 UTC
It would be awesome if we could switch the chat location to the left side of the screen. This would be useful for dual monitor setups. You could either have both chats right beside each other to make it easier to track multiple channels at a time or have the video right beside each other to make watching multiple channels at a time easier without using multitwitch or kadgar.

**Comment by night** [comment] 2015-05-11 08:53
Duplicate of #202

**Closed by night** 2015-05-11 08:53 UTC
Labels: duplicate
