### ISSUE TITLE
cant read deleted messages anymore on Firefox addon

### ISSUE THREAD

**Issue by makedir** [night/betterttv#7065] opened 2024-09-30 14:45 UTC
### Describe the bug

cant read deleted messages anymore on Firefox addon

### Steps to reproduce

-

### Expected behavior

-

### Screenshots

-

### Device information

-

### BetterTTV Version

7.6.6

### Version Check

- [X] I have checked that I'm using the newest version of BetterTTV available.

**Comment by dclstn** [comment] 2024-09-30 16:00
Duplicate of #7051

**Closed by dclstn** 2024-09-30 16:00 UTC
Labels: bug, duplicate
