### ISSUE TITLE
Bug with sidebar settings

### ISSUE THREAD

**Issue by kilroy98** [night/betterttv#6660] opened 2024-03-02 08:27 UTC
### Describe the bug

When the sidebar is collapsed, the settings for it do not work. And I think that "Recently Watched Channels" and "Similar Channels" do not work, because if you expand the sidebar and try to change these settings, nothing changes. And for some reason some translations are missing.

### Steps to reproduce

1. Go to twitch.tv
2. Collapse the sidebar
3. Open BetterTTV settings
4. Try to change "Tab settings"

### Expected behavior

I think the settings should work even when the sidebar is collapsed.

### Screenshots

![Screenshot_3](https://github.com/night/betterttv/assets/13346898/b98294ec-91aa-4f70-bb15-1969ea856423)

### Device information

OS: Windows 10
Browser: Google Chrome 122.0.6261.95
Version: 7.5.18

**Comment by subsection3** [comment] 2024-03-03 18:47
+ experiencing the same issue

**Comment by night** [comment] 2024-03-12 15:24
duplicate of #6661

**Closed by night** 2024-03-12 15:24 UTC
Labels: duplicate
