### ISSUE TITLE
Feature request: Auto Claim Moments

### ISSUE THREAD

**Issue by gowerr** [night/betterttv#5322] opened 2022-04-09 13:37 UTC
I am sure that I, as many others, would love to have this feature enabled in BTTV. Sometimes you miss the moment because you're cooking dinner, or whatever example people can come up with.

Thanks a lot!

**Comment by Nareese** [comment] 2022-04-09 13:43
duplicate of #5216

**Closed** 2022-04-10 06:39 UTC
Labels: duplicate
