### ISSUE TITLE
suggestion 7tv

### ISSUE THREAD

**Issue by MrDolan1337** [night/betterttv#5021] opened 2021-11-17 13:29 UTC
would be really nice to have 7tv support as an addon for bttv since it got kinda popular but their extension isnt that great

**Comment by Nareese** [comment] 2021-11-17 13:39
duplicate of #4662 

Additionally, night indicated [here](https://github.com/night/betterttv/pull/4840#issuecomment-922406564) that he is not willing to add 7tv support due to TOS issues.

**Closed** 2021-11-27 19:49 UTC
Labels: duplicate
