### ISSUE TITLE
hide offline followed channels not working

### ISSUE THREAD

**Issue by bruno-kalel** [night/betterttv#6846] opened 2024-06-02 20:23 UTC
### Describe the bug

hide offline followed channels not working

### Steps to reproduce

yeah pretty much the title, all the offline followed channels are showing in the sidebar lately, turning on and off said option doesn't change a thing unfortunately

### Expected behavior

hide offline followed channels in the sidebar when the option is activated

### Screenshots

not necessary

### Device information

windows 11, google chrome, 125.0.6422.113

**Comment by EightofBlades** [comment] 2024-06-03 04:51
same problem, also on chrome

**Comment by kilroy98** [comment] 2024-06-03 09:56
Duplicate of #6841

**Closed** 2024-06-03 14:08 UTC
Labels: bug
