### ISSUE TITLE
Error code reading chat

### ISSUE THREAD

**Issue by animorph127** [night/BetterTTV#2007] opened 2017-01-28 01:07 UTC
![image](https://cloud.githubusercontent.com/assets/25396668/22392846/e70bf754-e4cb-11e6-8c7f-f11bb36a44d6.png)

It wasn't doing this earlier, as of about an hour ago it just started doing this. BTTV has not done this before. But i am also assuming its a bug between both twitch and bttv cause twitch has been all screwy with their site, via having to reload when i get into chat cause chat wont appear unless i reload.

**Comment by night** [comment] 2017-01-28 07:22
duplicate of #2005

**Closed by night** 2017-01-28 07:22 UTC
Labels: duplicate
