### ISSUE TITLE
bttv auto fill in emotes 

### ISSUE THREAD

**Issue by martking26** [night/BetterTTV#3153] opened 2018-06-23 17:30 UTC
Auto fill in for emotes are broken. i def find that one very handy to use since MOST of the channel emotes are VERY long and for me good to still use them due to auto fill in. PLS fix it <3

**Comment by samfun123** [comment] 2018-06-23 17:31
Duplicate of #3151

**Closed** 2018-06-23 17:59 UTC
Labels: duplicate

**Comment by mikkymit** [comment] 2018-08-28 03:56
Still broken
