### ISSUE TITLE
Black List of games - Not in view

### ISSUE THREAD

**Issue by fernandohg** [night/BetterTTV#199] opened 2015-01-25 01:53 UTC
Is there a way to filter the page: "twitch.tv/directory/all", so the name of games in a black list , dont appear in the directory/all channels.

For example: i dont like games like: LOL, WOW, heartstone, dota , starcraft etc.  I put them in a blacklist and they dont show up in the directory/all.

I'm not sure if "BetterTTV" can modify these aspects of TwitchTV but it would be awesome to have a feature like these.

**Comment by night** [comment] 2015-02-08 22:30
Duplicate of #70

**Closed by night** 2015-02-08 22:30 UTC
Labels: duplicate
