### ISSUE TITLE
Can we have more slots to contribute emotes?

### ISSUE THREAD

**Issue by bootyislife** [night/betterttv#4925] opened 2021-10-13 16:12 UTC
Is the only option for monthly fee? I don't use dashboard for "my emotes" I use it to upload custom made emotes. But I see after 15 you are kind of screwed.

I don't want to use these emotes I just want to upload them to share with others if my point didn't come across

**Comment by night** [comment] 2021-11-28 20:49
duplicate of #4173

**Closed by night** 2021-11-28 20:49 UTC
Labels: duplicate
