### ISSUE TITLE
BTTV chat not showing up

### ISSUE THREAD

**Issue by Technical-13** [night/BetterTTV#2100] opened 2017-03-03 16:49 UTC
About 40% of the time chat fails to load and I can't read anything put in chat.  This forces me to have to chat through my HexChat IRC client to read what's going on in chat.

![image](https://cloud.githubusercontent.com/assets/4294498/23560130/6012ada4-0007-11e7-87c4-5bb0e010669a.png)

**Comment by night** [comment] 2017-03-14 07:25
duplicate of #1898

**Closed by night** 2017-03-14 07:25 UTC
Labels: duplicate
