### ISSUE TITLE
BTTV emote list not working

### ISSUE THREAD

**Issue by SportmanGuy** [night/BetterTTV#2919] opened 2018-01-15 23:25 UTC
bttv emote list loads very rarely in streams maybe 1 in 20 streams visited it loads completely. I cant see the bttv emotes at all in the list and have removed bttv as a whole and even checked the settings and it still wont load.

**Comment by night** [comment] 2018-01-16 04:05
duplicate of #2901

**Closed by night** 2018-01-16 04:05 UTC
Labels: duplicate
