### ISSUE TITLE
No emotes in settings.

### ISSUE THREAD

**Issue by Cssandico** [night/BetterTTV#2531] opened 2017-06-21 14:03 UTC
The option to add bttv emotes gone, any fix for this? I tried reinstalling several times. And I can't use enter key to send messages anymore.

**Comment by Nareese** [comment] 2017-06-21 22:50
Update your Chrome (Menu->Help->About Google Chrome)

duplicate of #2504

**Comment by Cssandico** [comment] 2017-06-23 11:18
Fixed! Thank you so much!

**Closed** 2017-06-24 00:25 UTC
Labels: invalid
