### ISSUE TITLE
Show Deleted Messages not working.

### ISSUE THREAD

**Issue by lemont34** [night/BetterTTV#3244] opened 2018-08-30 17:05 UTC
Used to work, but a few days ago it just stopped working.
The messages will turn into message deleted even if I have Show Deleted Messages ON.
No matter how many times I turn it off and on it just wont work anymore.
![58647](https://user-images.githubusercontent.com/42845220/44867265-f12d3880-acb9-11e8-9be1-49ed55dcd10d.JPG)

**Comment by Nareese** [comment] 2018-08-30 17:49
duplicate of #3233

**Closed** 2018-09-01 18:38 UTC
Labels: duplicate
