### ISSUE TITLE
Quick Purge / Timeout Duration Setting

### ISSUE THREAD

**Issue by devonzara** [night/BetterTTV#410] opened 2015-05-12 05:08 UTC
Opening the moderator card is a bit of a hassle when moderating an active chat. To make things a bit easier, I'd like to propose the follow two ideas:  
 * An option to enable a 3rd button next to the usernames to quickly purge a user.
 * An option to set the default duration of the timeout button.

**Comment by night** [comment] 2015-05-13 16:09
Duplicate of #76

**Closed by night** 2015-05-13 16:09 UTC
Labels: duplicate

**Comment by devonzara** [comment] 2015-05-14 06:31
Not a duplicate, though roughly related. 

Based on my understanding of #76, they want to be able to set custom durations for the buttons within the moderator cards.

My suggestions were pertaining to the buttons next to the name in the chat, not the ones in the moderator cards.
