### ISSUE TITLE
More Highlights

### ISSUE THREAD

**Issue by NanoWolf** [night/BetterTTV#908] opened 2016-01-16 00:20 UTC
So i think it would be useful to have more than 1 highlight in chat, for example i would like to have one purple highlight that i can have different triggerwords in like one where i have my name (as usual) and 1 where i can have people saying bad words so i can see who is talking shit easier and timeout them, i don't think this should be and issue for you guys to add at least

**Comment by night** [comment] 2016-01-16 00:25
Duplicate of #237

**Closed by night** 2016-01-16 00:25 UTC
Labels: duplicate
