### ISSUE TITLE
Feature request: Swap chat and sidebar positions

### ISSUE THREAD

**Issue by Chezus** [night/BetterTTV#784] opened 2015-10-24 14:07 UTC
I'd really like it if I could swap the chat and sidebar positions. I often put twitch on my second screen and then the chat is a little too far for me too read properly. Being able to have it on the left instead would be really quite nice. I was thinking I could write it myself but I have no idea if that would break things, so I figured I might as well feature request it for BetterTTV.

Thanks for BetterTTV. I love it! Dark Theme is so nice.

**Comment by night** [comment] 2015-10-24 15:47
Duplicate of #202

**Closed by night** 2015-10-24 15:47 UTC
Labels: duplicate
