### ISSUE TITLE
deleted messages still wont show

### ISSUE THREAD

**Issue by beanchill** [night/betterttv#7056] opened 2024-09-28 20:38 UTC
### Describe the bug

i click on the 
Highlight Deleted Messages

Changes <message deleted> back to users' original messages and highlights them. 
option, and it still only shows deleted messages as: 
message deleted by a moderator.
 

### Steps to reproduce

bttv settings, scroll down to deleted messages, click on highlight deleted messages and it doesnt work

### Expected behavior

i expected the deleted messages to show and be highlited in red like usually

### Screenshots

![Screenshot 2024-09-28 213617](https://github.com/user-attachments/assets/a4e5796b-fd12-421f-8971-ab593c4e3042)
![Screenshot 2024-09-28 213731](https://github.com/user-attachments/assets/d0b4aab0-732a-4cae-be7f-38182076e4dc)

### Device information

browser, chrome

### BetterTTV Version

newest version, i just reinstalled

### Version Check

- [X] I have checked that I'm using the newest version of BetterTTV available.

**Comment by night** [comment] 2024-09-28 21:13
duplicate of #7051

**Closed by night** 2024-09-28 21:13 UTC
Labels: bug, duplicate
