### ISSUE TITLE
ability to completely remove all emotes from chat

### ISSUE THREAD

**Issue by xInterceptor** [night/BetterTTV#1793] opened 2016-11-27 06:47 UTC
I would like to see a feature added that gets rid of all emotes and removes any chats that only contain emotes. I'm not sure if any other people are interested in this sort of feature but I personally don't like to see emotes. Thanks for reading.

**Comment by night** [comment] 2016-12-01 06:12
duplicate of #144

**Closed by night** 2016-12-01 06:12 UTC
Labels: duplicate
