### ISSUE TITLE
Feature Request: Ban/Timeout Templates?

### ISSUE THREAD

**Issue by Mi-Turner** [night/BetterTTV#1250] opened 2016-06-07 22:38 UTC
I was talking with some mods about moderation utilities when a Twitch Admin, Moblord, suggested a great idea for BTTV.

He said that it would be great to have the ability to like click a username and have a menu appear where it sets up in the chat box the timeout/ban command and all you need to do is enter a reason. Or if there were predefined messages made for this as well. Just to make banning and timing-out users more efficient and effective while utilizing the new reasoning feature. 

Thank you for your consideration!

**Comment by night** [comment] 2016-06-08 02:49
Duplicate of #1246

**Closed by night** 2016-06-08 02:49 UTC
Labels: duplicate
