### ISSUE TITLE
Personal emotes (BTTV pro) not working/showing up in Twitch

### ISSUE THREAD

**Issue by SadduurTTV** [night/betterttv#4643] opened 2021-06-28 22:17 UTC
Hi!

My SSD broke and had to reinstall windows and browser (Brave). Everything was working fine before but now my personal emotes (BTTV pro) are not working anymore. Tried removing and adding them back, but still no go. Any clue as to what is the cause? All other BTTV channel/global emotes work fine as well as FrankerFaceZ emotes. 

Thank you in advance!

**Comment by night** [comment] 2021-06-30 02:19
duplicate of #4381

**Closed by night** 2021-06-30 02:19 UTC
Labels: duplicate

**Comment by DorCoMaNdO** [comment] 2021-06-30 03:27
@night not sure it is a duplicate, a friend of mine recently got BTTV Pro to use personal emotes, it was working, but as of a few days ago it is no longer working, in/out of mod view (we found that it usually doesn't work if the personal emote user is in mod view, potentially related to #4587 ) and in different channels we both view/moderate, I believe we're both using latest Chrome.
