### ISSUE TITLE
No settings visible, BetterTTV not working

### ISSUE THREAD

**Issue by 6Grimmjow6** [night/BetterTTV#2468] opened 2017-05-19 17:53 UTC
Today I had a trouble viewing any stream in Chrome; Bttv emotes also weren't seen, and clicking on settings resulted in "Here you can manage the various BetterTTV options. Click On or Off to toggle settings." and a blank window below. Even disabling all extensions (Bttv included), clearing cache and Twitch cookies didn't help. Changing Chrome profile/going incognito helped with the streams, but the Bttv problem is still here.

**Comment by night** [comment] 2017-05-19 18:08
duplicate of #2464

**Closed by night** 2017-05-19 18:08 UTC
Labels: duplicate
