### ISSUE TITLE
Left side chat showing followed channel sidebar in theatre mode

### ISSUE THREAD

**Issue by IamTehShadow** [night/betterttv#4030] opened 2020-07-10 20:27 UTC
just like the title says, it suddenly started happening today after i refreshed a stream, it fixes when i disable left side chat option, but if I toggle it back on the sidebar shows and it eats a part of the stream
![Untitled](https://user-images.githubusercontent.com/68128442/87200282-e192c800-c304-11ea-884c-b2c105acf001.png)

**Comment by lazycrypt** [comment] 2020-07-10 20:42
Can confirm, having the same issue on Firefox. Cleared cache and reinstalled the extension thinking something went wrong on my end but the issue persists, the Following bar is stuck on the left side instead of moving to the right side with the "Left Side Chat" enabled.

**Comment by night** [comment] 2020-07-12 19:22
duplicate of #4029

**Closed by night** 2020-07-12 19:22 UTC
Labels: duplicate
