### ISSUE TITLE
Left side chat broken

### ISSUE THREAD

**Issue by xDuskWolf2** [night/BetterTTV#3062] opened 2018-04-06 18:29 UTC
After having left side chat enabled for a few months, it will no longer go back to the right side on either the "ON" or "OFF" settings.

**Comment by night** [comment] 2018-04-07 02:13
duplicate of #2971

**Closed by night** 2018-04-07 02:13 UTC
Labels: duplicate

**Comment by xDuskWolf2** [comment] 2018-04-11 01:59
How is this a duplicate? I am having the opposite problem of #2971
