### ISSUE TITLE
New option to revert back to the old twitch layout. 

### ISSUE THREAD

**Issue by Visirum** [night/BetterTTV#1566] opened 2016-09-30 02:38 UTC
The new twitch layout is just stupid. It looks like garbage. I would like to see if you could put all of the buttons like the follow, subscribe, videos, and such back below the stream. 

Thanks for reading my dude

**Comment by night** [comment] 2016-10-03 01:37
duplicate of #1558

**Closed by night** 2016-10-03 01:37 UTC
Labels: duplicate
