### ISSUE TITLE
Split chat for BTTV

### ISSUE THREAD

**Issue by DynuKin** [night/BetterTTV#2870] opened 2017-12-13 23:51 UTC
the split chat feature while in darkmode for twitch makes half the chat blindingly white all of a sudden
![brokentwitchchat](https://user-images.githubusercontent.com/34525665/33968577-de4729b2-e025-11e7-92aa-2e66152a8f99.PNG)

**Comment by Stoupedog** [comment] 2017-12-14 01:09
Duplicate of #2867

**Closed** 2017-12-14 18:56 UTC
Labels: duplicate
