### ISSUE TITLE
Feature Request: Auto-Quality Selection

### ISSUE THREAD

**Issue by ksred95** [night/betterttv#5246] opened 2022-03-05 00:42 UTC
My Twitch player constantly seems to default to 480p and I manually have to change this to source or auto. 
I have an extension for YouTube which automatically sets every videos resolution to a pre-defined choice, this would be great to have for Twitch if possible.

**Comment by dclstn** [comment] 2022-03-05 01:22
It's unlikely for us to implement an existing twitch feature, have you considered reaching out to them about this issue?

**Comment by ksred95** [comment] 2022-03-05 01:30
> It's unlikely for us to implement an existing twitch feature, have you considered reaching out to them about this issue?

Thanks for the reply! Apologies but I think I explained the request incorrectly. Rather than an “auto quality” selection, perhaps it’s better to word it as “Force quality”. Whilst Twitch offers an auto quality setting, I am referring to having the stream default to 1080p source when available, rather than having it reset to selecting 480p for me, despite having gigabit internet speeds.

Clicking “auto” will in the quality options will have the desired effect for me of bringing the stream back to source quality, it’s just frustrating that I seem to have to constantly click to myself to change this back from 480p to auto or source on each stream load.

Regardless, I shall also reach out to Twitch with this issue!

**Comment by night** [comment] 2022-03-27 19:24
duplicate of #4174

**Closed by night** 2022-03-27 19:24 UTC
Labels: duplicate
