### ISSUE TITLE
Emotes work fine, but cant log in to edit.

### ISSUE THREAD

**Issue by TheRealTecknos** [night/BetterTTV#3431] opened 2019-04-08 23:32 UTC
I can't connect to change my emotes, and tried clearing cache and cookies. currently have v7.2.54 in case it may be a missing update problem.

**Comment by Vafarien** [comment] 2019-04-09 02:04
i'm also experiencing this issue.
The
https://api.betterttv.net/2/changelog
responds with a: {"status":500,"message":"error fetching changelog"}

**Comment by night** [comment] 2019-04-09 07:02
duplicate of #3429

**Closed by night** 2019-04-09 07:02 UTC
Labels: duplicate
