### ISSUE TITLE
Feature Request - Filter subscribers/emotes from chat

### ISSUE THREAD

**Issue by ConceitfulResolution** [night/betterttv#5614] opened 2022-09-10 23:36 UTC
No idea how realistic this idea is - is it possible to filter out people in chat who are subscribers to certain channels? There are times when I just don't want to read stuff from certain big communities as in ruins the chat experience. The best alternative right now is to manually add the channel's emotes into the BTTV blocklist for words.

**Comment by night** [comment] 2022-10-01 03:12
duplicate of #267

**Closed by night** 2022-10-01 03:12 UTC
Labels: duplicate
