### ISSUE TITLE
hosted channel 

### ISSUE THREAD

**Issue by gamernation89** [night/BetterTTV#2674] opened 2017-09-09 18:03 UTC
can you please fix the setting that disables hosted channels on streams because even though its turned on and i am still getting hosted channels which i find them annoying and its been happening for awhile 
![screenshot 829](https://user-images.githubusercontent.com/19208617/30242608-9bb3d798-9567-11e7-9dac-8c4e928f5736.png)

**Comment by night** [comment] 2017-09-09 18:19
Duplicate of #2601

**Closed by night** 2017-09-09 18:19 UTC
Labels: duplicate
