### ISSUE TITLE
Missing "Auto expand following list"?

### ISSUE THREAD

**Issue by Nerxxy** [night/betterttv#5648] opened 2022-09-27 18:05 UTC
I remember there being an option that made the the following list expand automatically. Is there a reason for removal or was this an ffz thing? I cant seem to find the option on either extension.

I may entirely be remembering something that didnt exist, if thats the case then it would be a nice feature to add :)

**Comment by night** [comment] 2022-10-01 02:06
duplicate of #4770

**Closed by night** 2022-10-01 02:06 UTC
Labels: duplicate

**Comment by Nerxxy** [comment] 2022-10-01 02:12
Sorry if im just misunderstanding but im not sure how this is a duplicate... 4770 says that auto expanding doesnt work if the side bar is collapsed, where as my issue is that there is not option to turn auto expanding on or off in the bttv menu...

**Comment by night** [comment] 2022-10-01 02:39
<img width="484" alt="image" src="https://user-images.githubusercontent.com/2942184/193379888-5ad8e4a9-0836-4aaf-b187-080094158e62.png">

the setting is called auto expand channels. it just doesn't work in 100% of cases (collapsed sidebar)

**Comment by Nerxxy** [comment] 2022-10-01 02:55
![image](https://user-images.githubusercontent.com/37718547/193383643-fcf7474e-6226-461e-b9ba-0eca944e5f44.png)
but umm?

**Comment by Nerxxy** [comment] 2022-10-01 23:14
the only way that i can toggle auto expand channels on and off is if i backup the settings, change it from a .backup to a .json file and enable/disable it there and then import the backup file back into bttv
