### ISSUE TITLE
[bug] BTTV settings not synced between twitch.tv and new dashboard

### ISSUE THREAD

**Issue by pointydev** [night/betterttv#3719] opened 2020-01-14 00:40 UTC
Heya,

So this seems like a similar issue to #58 and #1623, but thought I'd report since it seems like a similar problem that isn't resolved. Currently, to synchronise settings between main twitch and the dashboard chat, you've gotta use the backup/import feature to manually transfer your settings. I've had reports from multiple people that this is undesirable, and that it seems to have been introduced around the time the new dashboard was introduced (also when the move was made to the dashboard.twitch.tv subdomain).

I have a feeling this may be something that *some* people might like due to things like `localsub` being available while streaming, but I believe this is still unintentional behaviour.

Repro at time of issue is Chrome v7.2.74.

Thanks,
Elliott

**Comment by night** [comment] 2020-08-30 10:39
duplicate of #766

**Closed by night** 2020-08-30 10:39 UTC
Labels: duplicate
