### ISSUE TITLE
Offline sidebar snafu

### ISSUE THREAD

**Issue by Dustup224** [night/betterttv#6844] opened 2024-06-01 18:21 UTC
### Describe the bug

When I set my BetterTTV  preference to hide offline follows, my entire sidebar is filled with offline follows instead of no offline follows that I set in the Better TTV settings.

### Steps to reproduce

1) On Twitch, click on the settings cog icon located under the chat message input box.
2) Scroll to the "Better TTV settings" and click on it.
3) At the Better TTV settings page, click on the second from the top directory settings icon to open the sidebar preferences.
4) Uncheck the box marked "Offline Followed Channels"
5) Close the Better TTV settings page and return to Twitch.
6) Now the sidebar is full of offline channels instead of the normal disappearance of all offilne followed channels.

### Expected behavior

After clicking into the Better TTV settings page and unchecking the "Offline Followed Channels" box and returning to Twitch, when this deselection of "Offline Followed Channels" usually eliminates all offline channels from my sidebar. Instead, just the opposite happens and the sidebar is filled with a long list of offline channels, some of which I am not currently following.

### Screenshots

<img width="179" alt="Before Going into BTTV settings at Twitch" src="https://github.com/night/betterttv/assets/171442217/fd94dc1f-53a7-4c36-a2c7-e893cfc6f10e">

<img width="426" alt="Before BTTV Setting on Twitcch sidebar" src="https://github.com/night/betterttv/assets/171442217/108e7cc4-3d2f-41aa-9830-eeea66f00a92">

<img width="426" alt="After unclicking Offline setting on BTTV" src="https://github.com/night/betterttv/assets/171442217/a3b2fdf4-8df8-42ae-ab41-a75add7a8b89">

<img width="177" alt="After unclicking Offline setting Twitch sidebar" src="https://github.com/night/betterttv/assets/171442217/7f8a335d-ea5b-4eef-ac4e-5611c9b3e61b">

### Device information

Device: MSI Laptop 11th Gen CPU
OS: Windows 10 Pro Version 22H2
Browser: Chrome, version 125.0.6422

### Additional information

**Prior to this bug:**
1) Twitch sidebar Followed Channels had one or two offline followed channels listed because Twitch saved room for Reccomended channels on the sidebar.

2) After going to the Better TTV settings page and unclicking the Offline Followed Channels box, closing the BTTV settings page,  then returning to Twitch, my sidebar has no offline channels remaining on the sidebar.

**After this bug appeared:**

3) After going to the Better TTV settings page and unclicking the Offline Followed Channels box, closing the BTTV settings page,  then returning to Twitch, my sidebar is filled with offline channels to the point you have to scroll far to get to the end.

**Comment by Dustup224** [comment] 2024-06-01 18:33
I have tried clearing my browser cache and cookies in Chrome. I have also verified my Chrome version is fresh and up to date. I am stubbornly holding off switching to Windows 11 because my preview made me pissed with he stripped features from W10, but I always keep Windows 10 Pro versions up to date as they are offered.

I have researched this same bug on Google and find references only to 2019/2020 and claims in forums that the issue was "Fixed". A Twitch update was said to have been the cause of the Better TTV bug.

**Comment by RangePup** [comment] 2024-06-02 15:07
I have been having a similar issue. The only box I have checked is "Recently watched" but I'm also seeing Offline and Recommended. The problem didn't start until this week. Tried to uninstall and reinstall and didn't fix it.

OS: Windows 10 22H2
Browser: Chrome, Version 125.0.6422.142 (Official Build) (64-bit)
Plugin: Version 7.6.0

**Comment by Dustup224** [comment] 2024-06-02 17:13
Reply to Range Pup:
Thanks for chiming in because it helps me verify my problem is not local to my account or laptop.

**Comment by EightofBlades** [comment] 2024-06-03 04:53
same problem, windows 10, google chrome - made sure everything was updated - offline channels showing even though selected to be hidden

**Comment by Dustup224** [comment] 2024-06-03 05:07
Reply to EightofBlades: Thanks for adding to the discussion. It would not be so bad except that I am always looking at the Recommended channels for new channels to follow and support. 

With this bug, my offline followed channels list is quite long and I have to scroll quite far down to get to the recommended channels list. When I try to hide the offline followers list by clicking "See Less", it takes me 4 to 5 attempts, each time having to scroll up to catch up to the "See Less" control so I can remove more offline follows.

If I click on another of my live followed channels the gosh darn very long list of offlines reappears...

**Comment by EightofBlades** [comment] 2024-06-03 05:16
Yeah basically same issue for me. I don't use the recommended, I only use the auto-expand list option, but even with offline followed channels deselected, it is still showing me all of them and I have to hit "show less" 4 or 5 times to hide them all

**Comment by night** [comment] 2024-06-03 14:07
duplicate of #6837

**Closed by night** 2024-06-03 14:07 UTC
Labels: bug

**Comment by Dustup224** [comment] 2024-06-03 14:24
"Closed"??
WTF. The issue persists, superman. 
Better TTV is just another ignorant Google wannabe. Go FOAD if this is how you fix your bugs.

**Comment by night** [comment] 2024-06-03 15:33
> "Closed"?? WTF. The issue persists, superman. Better TTV is just another ignorant Google wannabe. Go FOAD if this is how you fix your bugs.

It is you who is ignorant. Please refer to the issue linked in the reply. The issue is fixed pending release in version 7.6.2.
