### ISSUE TITLE
Mod deleted messages not showing (Twitch)

### ISSUE THREAD

**Issue by Heggyyy** [night/betterttv#7066] opened 2024-09-30 20:33 UTC
### Describe the bug

I've selected the option to see messages mods delete on Twitch. Seems to have stopped working in the past week or so. It just shows that a message was deleted by a moderator, instead of the deleted message itself which it used to show.

### Steps to reproduce

1. Enable "Show deleted messages"
2. Have a mod delete a message

### Expected behavior

Should show the deleted message instead of that a message was deleted by a mod.

### Screenshots

[Here](https://i.gyazo.com/58043173f383bf32fb4a94ddb903b40f.png)

### Device information

Win10, Chrome

### BetterTTV Version

7.6.6

### Version Check

- [X] #7067

**Comment by dclstn** [comment] 2024-09-30 20:52
Duplicate of #7065

**Closed by dclstn** 2024-09-30 20:52 UTC
Labels: bug, duplicate
