### ISSUE TITLE
The BetterTTV emoticon menu has disappeared when the 7tv extension is enabled

### ISSUE THREAD

**Issue by Katgarik** [night/betterttv#6840] opened 2024-06-01 01:20 UTC
### Describe the bug

The BetterTTV emoticon menu has disappeared when the 7tv extension is enabled

### Steps to reproduce

extensions included, BetterTTV includes advanced emoji. The emoji menu is not showing

### Expected behavior

I want the BetterTTV emoticon menu to be displayed with the 7tv extension enabled

### Screenshots

![Снимок экрана 2024-06-01 121517](https://github.com/night/betterttv/assets/118953622/2b5b8b36-46b0-401c-9556-54329eed4b58)

### Device information

Browser Google Chrome

**Comment by Nelicopterr** [comment] 2024-06-01 01:22
Seems like a recent bug, I fixed mine by disabling the ffz extension and just having bttv one, hope this helps you :)

**Comment by night** [comment] 2024-06-01 04:01
duplicate of #6838

**Closed by night** 2024-06-01 04:01 UTC
Labels: bug
