### ISSUE TITLE
player bad position

### ISSUE THREAD

**Issue by dopesvk** [night/BetterTTV#1811] opened 2016-12-02 15:21 UTC
Twitch player is moved down.

Screenshot:
http://prntscr.com/dei7hs

**Comment by Bren002** [comment] 2016-12-02 17:50
it's the mini player that messed it up

**Comment by EhsanKia** [comment] 2016-12-03 20:24
Should be fixed now.

**Closed by EhsanKia** 2016-12-03 20:24 UTC

**Comment by night** [comment] 2016-12-03 23:29
duplicate of #1806
