### ISSUE TITLE
Hide Recommended Channels Bug

### ISSUE THREAD

**Issue by Kearvs** [night/betterttv#4032] opened 2020-07-10 21:22 UTC
The option does not work. When on option "Yes", the recommended channels do not go away.
![Capture](https://user-images.githubusercontent.com/68129873/87204075-f30eac80-c2d1-11ea-820b-fe265624cdd7.PNG)

**Comment by ceiphr** [comment] 2020-07-12 17:44
Firefox v78.0.1 for Ubuntu 20.04 LTS. Can confirm, same issue.

**Comment by night** [comment] 2020-07-12 19:25
duplicate of #4023

**Closed by night** 2020-07-12 19:25 UTC
Labels: duplicate
