### ISSUE TITLE
An option to display both username and localized name

### ISSUE THREAD

**Issue by a2364983** [night/BetterTTV#1833] opened 2016-12-06 07:28 UTC
I'm a Chinese user. It will be great if there's an option to enable displaying both username and localized name, just like Twitch default. I know there's a "Disable Localized Names" option in setting, but it won't display both. Thanks!

**Comment by Stoupedog** [comment] 2016-12-06 07:37
Duplicate of https://github.com/night/BetterTTV/issues/1488

**Closed** 2016-12-06 10:01 UTC
Labels: duplicate

**Comment by EhsanKia** [comment] 2016-12-06 23:46
Note that you can still see the other name in the card you get when you click on the name.
