### ISSUE TITLE
Tab complete broken

### ISSUE THREAD

**Issue by wbahm** [night/BetterTTV#2995] opened 2018-02-24 22:55 UTC
My tab complete stopped working yesterday.  I hit tab and the thing I'm trying to complete to pops up but then disappears.  Here is a gif of it happening: https://i.imgur.com/l09mDsU.gifv

**Comment by night** [comment] 2018-02-25 06:06
duplicate of #2987

**Closed by night** 2018-02-25 06:06 UTC
Labels: duplicate
