### ISSUE TITLE
Show Deleted Messages

### ISSUE THREAD

**Issue by Mesmary** [night/BetterTTV#3010] opened 2018-03-01 07:19 UTC
Function doesnt work.
Chrome 64.0.3282.186 (64)
![vjwlpbb 1](https://user-images.githubusercontent.com/36948611/36831819-1126bc0c-1d3a-11e8-9e92-8120759f208a.png)

**Comment by ownchoice** [comment] 2018-03-01 11:49
Same for me.

**Comment by Nareese** [comment] 2018-03-01 16:17
duplicate of #3003

**Closed** 2018-03-05 07:19 UTC
Labels: duplicate
