### ISSUE TITLE
Theatre mode and fullscreen toggle

### ISSUE THREAD

**Issue by Jonty800** [night/BetterTTV#1772] opened 2016-11-19 11:29 UTC
Hi,

When I'm in theatre mode and enter full screen (double click or the button) the fullscreen view is not correct. I'm using a MacBook Pro and I cannot replicate this if I disable BetterTTV.

Note the large black bar on the right hand side - the same width as the chat element

![Image of Bug](http://i.imgur.com/9XQkpny.jpg)

**Comment by EhsanKia** [comment] 2016-11-19 21:33
Can confirm the bug is back again...

**Comment by HKS218** [comment] 2016-11-30 21:30
Same here, only way to bring back Theatre/full screen is to disable BetterTTV :(

**Comment by EhsanKia** [comment] 2016-12-01 00:56
You're still having this issue? Also I don't get what you mean, the only time where this is an issue is if you are in theatre and then enter fullscreen. The simple solution is to leave theatre mode BEFORE entering fullscreen and it shouldn't be an issue.

**Comment by Jonty800** [comment] 2016-12-01 23:28
@EhsanKia Yes, this is a bug which is only caused when entering fullscreen mode while already in theatre mode.

There is another simple solution: fixing the bug.

**Comment by EhsanKia** [comment] 2016-12-02 01:27
I have been chasing the bug, but it's hard to fix a bug I can't reproduce.
Actually, I may have an idea. How do you enter fullscreen?
I think I have an idea that may fix this.

**Comment by Jonty800** [comment] 2016-12-02 01:29
Wow I didn't realise - this happens only when double clicking the video to enter fullscreen. When clicking the fullscreen icon, it's fine

**Comment by EhsanKia** [comment] 2016-12-02 02:07
Ok, yeah, this explains why I couldn't reproduce it. Alright should be able to fix this tonight.

**Comment by Torixz** [comment] 2016-12-02 22:19
A little after your post @EhsanKia 
I started having issues with the same, just that now i cant go to fullscreen mode when clicking the button. it works fine when bttv is disabled. But here is the strange part, now i can only go fullscreen with the stream when in theater mode and double clicking the video window.

**Comment by HKS218** [comment] 2016-12-02 23:17
My pc on windows 10 has black bars issue going from theatre mod to fullscreen (only by double clicking the video, fullscreen button is working)

On my second pc on Windows 7 i get the opposite, theatre mod is working both way, but double clic or full screen button on no-theatre mod give me this issue : https://github.com/night/BetterTTV/issues/1810

**Comment by EhsanKia** [comment] 2016-12-03 00:43
@Torixz @HKS218 yes, this is a different issue that happened after the miniplayer update yesterday, and we'll use #1810 to to track it.

**Comment by night** [comment] 2016-12-03 23:17
Should be fixed now.

**Closed by night** 2016-12-03 23:17 UTC
Labels: bug, channel
