### ISSUE TITLE
Feature Request: Emote Profiles

### ISSUE THREAD

**Issue by benfaletra** [night/betterttv#5247] opened 2022-03-07 02:04 UTC
Basically just have the ability to create a profile that you can select for emotes on the channel so it's easier for streamer to pick between themed emotes for things like the holidays (Christmas, Halloween) or whatever the streamer might want.

**Comment by Nareese** [comment] 2022-03-08 15:00
duplicate of #4217

**Closed** 2022-03-09 17:02 UTC
Labels: duplicate
