### ISSUE TITLE
[Feature Request] Option to disable Mini Player

### ISSUE THREAD

**Issue by joelunder** [night/BetterTTV#1944] opened 2017-01-05 22:50 UTC
Twitch added a new feature in the "Mini Player", and turned it on with no way to disable it. I greatly prefer the old format, where if I scrolled down, the video stayed at the top of the page, and if I navigated away from a stream, that stream closed. 

An option to disable that player (optionally in each circumstance, I'm sure some people like the feature in one instance or the other) would be awesome.

**Comment by Stoupedog** [comment] 2017-01-05 22:52
Duplicate of #1884

**Closed** 2017-01-06 02:02 UTC
Labels: duplicate
