### ISSUE TITLE
Left side chat no longer working

### ISSUE THREAD

**Issue by JollyGhost** [night/betterttv#3875] opened 2020-05-13 11:18 UTC
The left side chat is no longer working, just removed chat and move the player of the to left side of the screen. Clearly to do with the new Twitch layout

**Comment by djumpen** [comment] 2020-05-13 11:42
Confirm. Reinstall didn't help. I can't open settings to uncheck "left side chat".

**Comment by Suntop-Kinseeker** [comment] 2020-05-13 14:33
Theater mode allowed me to see it and disable left side chat.

**Comment by debaser19** [comment] 2020-05-15 02:19
> Theater mode allowed me to see it and disable left side chat.

confirmed. left side chat works fine in theatre mode. does not work in regular mode
![brave_R79plhS4jS](https://user-images.githubusercontent.com/4327643/82004475-fdddf580-9630-11ea-8409-5d140d5760b5.jpg)
![brave_RyJxlZxO5J](https://user-images.githubusercontent.com/4327643/82004480-00d8e600-9631-11ea-828e-483a4485e669.jpg)

**Comment by night** [comment] 2020-05-18 22:40
duplicate of #3873

**Closed by night** 2020-05-18 22:40 UTC
Labels: duplicate
