### ISSUE TITLE
24 hour time

### ISSUE THREAD

**Issue by sthyregod** [night/BetterTTV#1431] opened 2016-08-03 22:14 UTC
It would be nice if 24 hour time could be implemented (or military time depending on where in the world you are). Seeing 6 when expecting 18 seems a little weird

**Comment by Stoupedog** [comment] 2016-08-04 11:36
Duplicate of #1004 
> You can set your browser locale to a region of the world that uses 24hr clock to get it formatted that way. You can do that in the browser settings.

**Closed** 2016-08-05 05:12 UTC
Labels: duplicate
