### ISSUE TITLE
Have a way to mark messages in the chat as "read".

### ISSUE THREAD

**Issue by OverThrownBaby** [night/BetterTTV#2664] opened 2017-09-05 20:15 UTC
I think this feature would mainly help streamers that try to keep up with a steady chat. Having the ability to easily see at a glance where you last left off reading messages would make it flow a lot more. I think just a simple and fast way mark messages to a certain point in chat as "read" with maybe a double click in the same spot twice on the chat would be a great feature. You could mark via small checks on the side, maybe a darker shade overlay up to where you marked, or even just a empty gap.

**Comment by gapbl4** [comment] 2017-09-05 20:32
That seem like a very niche kind of feature.

**Comment by Raccok** [comment] 2017-09-06 06:14
Good idea, though it is a duplicate of #2049

**Closed** 2017-09-07 04:01 UTC
Labels: duplicate
