### ISSUE TITLE
[Feature Request] Removing/adding feeds

### ISSUE THREAD

**Issue by DeepVoicedGod** [night/BetterTTV#1672] opened 2016-10-19 02:46 UTC
Being able to remove a channel's feed so it looks more tidy and easier to look at panels without scrolling down millions of times just to read something about the streamer. Is this possible or yeah nah?

**Comment by night** [comment] 2017-07-19 04:48
duplicate of #1058

**Closed by night** 2017-07-19 04:48 UTC
Labels: duplicate
