### ISSUE TITLE
[request] Use "@" to message someone in chat

### ISSUE THREAD

**Issue by ChineseOuchie** [night/BetterTTV#216] opened 2015-02-08 21:07 UTC
Can you add the feature when you type "@" in the chat and type a letter you can see everyone in the chat everyone with that letter.

so if i type @c i can see @Chineseouchie , @cheesename. because they began with the letter C

**Comment by night** [comment] 2015-02-08 22:11
Duplicate of #86

**Closed by night** 2015-02-08 22:11 UTC
Labels: duplicate
