### ISSUE TITLE
Channel bot pinning

### ISSUE THREAD

**Issue by weatherdown** [night/BetterTTV#1279] opened 2016-06-17 04:49 UTC
like whispers or tags that pin at the top of the chat so you can see them, i'd like to see an option that pins channel bots to the top that show announcements or giveaways. Maybe make it customization by specifying bot name. or any name for that matter,

**Comment by night** [comment] 2016-06-18 15:46
duplicate of #363

**Closed by night** 2016-06-18 15:46 UTC
Labels: duplicate
