### ISSUE TITLE
cannot send messages in chat

### ISSUE THREAD

**Issue by saxondr** [night/BetterTTV#2006] opened 2017-01-27 23:54 UTC
Hey, when I click enter after typing in a message, it goes to the next line instead of sending the message. This does not seem to happen when I am on my Windows computer but only on my Mac. I can send messages when bttv is turned off. I haven tried to reinstall and restart bttv extension, but that hasn't worked.

**Comment by night** [comment] 2017-01-28 07:22
duplicate of #2005

**Closed by night** 2017-01-28 07:22 UTC
Labels: duplicate
