### ISSUE TITLE
Comma after auto completing emotes

### ISSUE THREAD

**Issue by EhsanKia** [night/BetterTTV#547] opened 2015-07-09 04:05 UTC
Current, if you auto complete an emote at the start of a sentence, it appends a comma at the end, which means Twitch doesn't actually render it. Honestly this feels like something Twitch should fix really (since there's no punctuation in emotes, except parens I guess), but until then, this seems like an issue. 

I realize you just popular the emote names into the auto complete list and this would require some extra hack, but as is, it kinda feels broken.

**Comment by night** [comment] 2015-07-09 04:17
I already added handling for this, and I cannot reproduce any issues with tab completion. If you can find a fault in my logic, feel free to PR: https://github.com/night/BetterTTV/blob/master/src/chat/helpers.js#L261

**Comment by night** [comment] 2015-07-09 23:51
The bug was found and is now fixed.

**Closed by night** 2015-07-09 23:51 UTC
Labels: bug, chat
