### ISSUE TITLE
All settings kinda bugged

### ISSUE THREAD

**Issue by Puqueno** [night/BetterTTV#2358] opened 2017-04-27 22:26 UTC
There was a bug a couple of months ago where the chat in automatic theatre mode would be white. I have that bug again right now, only solved when enabling dark theme. when I disable dark theme, Twitch stays dark?? It's like the bugs are working together to kill my Twitch lol. Also DansGame has the white outlining again :(

**Comment by Puqueno** [comment] 2017-04-27 22:28
And chat isn't showing the last message for like the half part of it. So when it is something like
FeelsBadMan
FeelsGoodMan
FeelsBadMan
It only shows the first FeelsBadMan and a half of FeelsGoodMan.

**Comment by night** [comment] 2017-04-28 05:53
> There was a bug a couple of months ago where the chat in automatic theatre mode would be white. I have that bug again right now, only solved when enabling dark theme. when I disable dark theme, Twitch stays dark?? 

it honestly sounds like you have another extension that is conflicting with out, so I would first try disabling other extensions and seeing if that fixed the problem

> Also DansGame has the white outlining again :(

🤔 we didn't port that yet, but probably will

> And chat isn't showing the last message for like the half part of it.

duplicate of #2295

**Closed by night** 2017-04-28 05:53 UTC
Labels: invalid

**Comment by Puqueno** [comment] 2017-04-28 18:20
I had FrankerFacez enabled but removed it because I wasn't comfortable with it. after that it's bugged, even after I removed cookies and other stuff.

**Comment by Puqueno** [comment] 2017-04-28 18:21
I mean the chat in theatre mode ^

**Comment by EhsanKia** [comment] 2017-04-28 23:34
Theatre mode not properly setting dark mode is a bug, for now, try going theatre manually

**Comment by Puqueno** [comment] 2017-05-01 15:00
Did Twitch push an update or something? this week bttv hasn't been working like it used to. bttv emotes are not showing in whispers anymore, strange.

**Comment by EhsanKia** [comment] 2017-05-02 00:11
No it's a big rewrite of BTTV for performance reasons.
