### ISSUE TITLE
Ability to configure MOD timeout time. 

### ISSUE THREAD

**Issue by coolacid** [night/BetterTTV#421] opened 2015-05-15 14:50 UTC
It would be super useful to configure the mod quick buttons in chat as opposed to hard coded.

**Comment by Maxhype** [comment] 2015-05-16 14:56
/timeout Maxhype 600 (10 minutes)
30min: 1800
1hr: 3600
4hr: 14400
8hr: 28800
24hr: 86400

**Comment by night** [comment] 2015-05-16 20:10
Duplicate of #76

**Closed by night** 2015-05-16 20:10 UTC
Labels: duplicate
