### ISSUE TITLE
Chat colors not appearing correctly on DarkenTTV

### ISSUE THREAD

**Issue by lluvdwayulie** [night/BetterTTV#1079] opened 2016-04-14 22:27 UTC
The chat colors are not appearing correctly on DarkenTTV. I have set it to a dark blue color (but still easily visible for others), but DarkenTTV changes it to a purplish color.

**Comment by night** [comment] 2016-04-16 01:08
duplicate of #1017

**Closed by night** 2016-04-16 01:08 UTC
Labels: duplicate
