### ISSUE TITLE
KIll video

### ISSUE THREAD

**Issue by MaxThomassen** [night/BetterTTV#273] opened 2015-03-08 22:52 UTC
Would be nice if we had an option to deactivate twitch video, for us that have 10 with windows inactive. very annoying when ppl have auto host on as that starts playing the next stream, so one has to stop it manually every time.. one can mute the stream.. put with 10 windows running twitch video it does strain the pc, and the internet bandwidth.. One could kill flash, but that would kill chat.. so thats no good for us collecting points for giveaways... thx for your time... regards max

**Comment by night** [comment] 2015-03-18 15:33
Duplicate of https://github.com/night/BetterTTV/issues/101

**Closed by night** 2015-03-18 15:33 UTC
Labels: duplicate
