### ISSUE TITLE
Hello. 

### ISSUE THREAD

**Issue by rehbecka** [night/BetterTTV#3345] opened 2019-01-05 11:41 UTC

**Comment by rehbecka** [comment] 2019-01-05 11:42
I just downloaded betterttv again and i kinda like it. the only thing im not so happy about it how it changes the colors of the names in twitchchat. Can you fix it? or help me to fix it? my name is white origignally but with betterttv it turns grey. merp.

**Comment by qewerka** [comment] 2019-01-06 02:08
yeah its pretty annoying I have the same issue.. Like why change people color? Its really annoying!!!

**Comment by xgerhard** [comment] 2019-01-07 12:18
duplicate of #3320

**Closed** 2019-01-08 09:13 UTC
Labels: duplicate
