### ISSUE TITLE
fullscreen scaling

### ISSUE THREAD

**Issue by poutiai2** [night/BetterTTV#1812] opened 2016-12-02 19:20 UTC
Fullscreen scales only to same size as theater mode. View is placed so that it is anchored on top and centered horizontally. Rest of the screen appears as black.

On:
firefox 50.0

Addons:
Ubuntu customization

Happens when you open a livestream and press the fullscreen button

Occurs only when BetterTTV addon is enabled. And reinstalling BetterTTV doesn't fix the problem.

Rebooting computer doesn't fix the problem. Clearing cache/cookies doesn't fix the problem. Problem occured this evening

**Comment by poutiai2** [comment] 2016-12-02 19:22
Problem occurs when html5 player is disabled as well

**Comment by poutiai2** [comment] 2016-12-02 19:26
Occurs only when BetterTTV addon is enabled. And reinstalling BetterTTV doesn't fix the problem.

**Comment by poutiai2** [comment] 2016-12-02 19:33
Rebooting computer doesn't fix the problem. Clearing cache/cookies doesn't fix the problem. Problem occured this evening

**Comment by clarkycal** [comment] 2016-12-02 20:19
I can confirm this is an issue with Chrome as well, I have disabled the Extension temporarily

**Comment by Slikrick** [comment] 2016-12-02 20:31
Duplicate of #1810

**Closed** 2016-12-02 21:16 UTC
