### ISSUE TITLE
Option to restore ignore behavior to previous twitch behavior

### ISSUE THREAD

**Issue by pas3n7** [night/BetterTTV#518] opened 2015-06-25 19:09 UTC
Twitch has recently changed ignore so that if you are a moderator, you still see their messages in chat. See: https://twitter.com/TwitchSupport/status/613895595330289664

Often the channel owner will tolerate someone that you would like to ignore. Also, some streamers have made nightbot rather obnoxious through custom commands, making ignore very useful for moderators.

It would be nice to have an option to either restore ignore to its previous behavior, or to have a separate ignore list through BetterTTV (per-channel ignore would be even better). I suspect it's unlikely twitch will add this functionality back on their own.

**Comment by night** [comment] 2015-06-25 21:37
I'm actually with Twitch on this decision. You shouldn't be able to ignore people as a mod of a channel, but you should be able to block whispers from them (which Twitch was fixing the last time I heard).

**Comment by vendethiel** [comment] 2015-06-26 07:25
I disagree. The user should be able to decide: I'm the one who knows why I ignored someone. Maybe they're even another mod.

**Comment by cletusc** [comment] 2015-06-26 15:29
-1, I am with Twitch as well.

**Comment by pas3n7** [comment] 2015-06-27 04:57
>I'm actually with Twitch on this decision. You shouldn't be able to ignore people as a mod of a channel, but you should be able to block whispers from them (which Twitch was fixing the last time I heard).

I suppose an option to enable ignore for other moderators of a channel is too niche a feature request.

**Comment by night** [comment] 2015-06-27 07:10
> I suppose an option to enable ignore for other moderators of a channel is too niche a feature request.

The issue is still open for discussion, hence why it isn't marked "wontfix" and closed. I posted my thoughts, as well as a couple other users. If you feel strongly about this, find other people who feel the same and get them to post replies explaining why we should offer this option.

**Comment by laagone** [comment] 2015-06-27 17:08
I'm on Twitch's side as well, though one workaround already exists if you *really* don't want to see someone's messages. You can put "(username)" as a blacklist keyword, which essentially does the same as /ignore used to do.

**Comment by night** [comment] 2015-07-01 23:24
Since we've not heard anything, I'm going to close this. Replies are still welcome, however.

**Closed by night** 2015-07-01 23:24 UTC
