### ISSUE TITLE
Latest version not functioning correctly

### ISSUE THREAD

**Issue by Latias4Ever** [night/BetterTTV#3449] opened 2019-04-23 21:46 UTC
Since version 7.2.56 came out, the extension hasn't been loading correctly. Many issues have been surfacing such as settings not being available, and not functioning:
![image](https://user-images.githubusercontent.com/24550309/56617956-be50ff80-6610-11e9-8e5c-07ed1ec1ef7c.png)

I have Twitch Prime promotions disabled, and Bits hidden in my settings, however they aren't functioning as they should:
![image](https://user-images.githubusercontent.com/24550309/56618012-db85ce00-6610-11e9-8ab4-19054b1661ef.png)
![image](https://user-images.githubusercontent.com/24550309/56618022-e04a8200-6610-11e9-94fe-821002597a3d.png)

And finally, non-official emotes are having a strange effect, where the emote shows up, but the name of the emote, and its source are also added to the message:
![image](https://user-images.githubusercontent.com/24550309/56618065-ff491400-6610-11e9-83be-ea9ee11cb9ca.png)

This started happening yesterday, I believe since the version came out. If it matters, my version of Chrome is 53. I hope this isn't an issue with that, as Javascript is also not updated with the latest functions in this version.

EDIT: I should add, my Chrome says that the version of BTTV is 7.2.1. I'm unsure what impact this might have, but perhaps Twitch caused something to break this version.

**Comment by xgerhard** [comment] 2019-04-25 10:31
Are you using other browser extensions, if so try disabling them.

The BTTV extension version from the Chrome store is correct, it's a different version number then BTTV itself.

**Comment by Latias4Ever** [comment] 2019-04-25 22:17
I've tried to see if Incognito Mode with only BTTV fixes this, it doesn't, so I don't think this is an issue with other extensions, or cookies.

**Comment by Latias4Ever** [comment] 2019-04-28 20:12
Bumping to add more info, I've checked the console, and I'm unsure where this is happening exactly, but there are some 404s happening, and some function errors (possibly due to my Chrome's Javascript not being up to date).
![image](https://user-images.githubusercontent.com/24550309/56869590-f0d47100-69f1-11e9-82d0-d3c5a1ef4fb5.png)
![image](https://user-images.githubusercontent.com/24550309/56869600-faf66f80-69f1-11e9-9d7c-aeeae0add6e3.png)

**Comment by night** [comment] 2019-04-29 10:30
What other browser extensions do you have installed? Have you tried disabling them all, and then trying again?

Those 404s are normal errors. The intersection observer warning looks like a different extension having a bad time.

**Comment by Latias4Ever** [comment] 2019-04-29 14:07
I have quite a few extensions, but for Twitch I think I only have BTTV, uBlock, The Great Suspender, and the Alternate Player. Like I said I've tried to open Twitch on Incognito Mode, with every extension but BTTV enabled in it, and it didn't fix it.

Here's the console with just BTTV enabled (Incognito), while logged out:
![image](https://user-images.githubusercontent.com/24550309/56901553-f5e3ff80-6a87-11e9-9c23-2430c5718766.png)

While logged in:
![image](https://user-images.githubusercontent.com/24550309/56901567-fed4d100-6a87-11e9-9b8d-225dc18d1010.png)

**Comment by DanLabute** [comment] 2019-05-01 00:34
Same issue here - the BTTV icon is missing in the twitch menu in Chrome.

Tried all of the steps in the troubleshooting guide and confirmed that it doesn't appear to be an interaction with another extension - I removed all extensions except BTTV and the issue persisted. Cleared all browsing data / cookies / cache and the issue persisted, removed and reinstalled the extension and the issue persisted,.

No errors in the console, and looking at the network tab, I do see calls being made to BTTV stuff without any errors, so I'm stumped. It's definitely installed and calls are being made to it without error, but it's just missing from the twitch menu. I'm stumped.

![image](https://user-images.githubusercontent.com/5962891/57001535-2fe7fb00-6b87-11e9-827c-41bf0b4bfaeb.png)
![image](https://user-images.githubusercontent.com/5962891/57001545-42623480-6b87-11e9-9e6b-816e0ba2e2ed.png)


Microsoft Windows 10 Home	10.0.17763 Build 17763
Chrome Version 74.0.3729.131 (Official Build) (64-bit)
BTTV Version 7.2.1

If I can provide additional information or can assist in further troubleshooting, please let me know.

**Comment by night** [comment] 2019-05-06 08:52
Unfortunately none of the reported logs show any actual errors, which makes it nontrivial to fix any issues occurring for you both.

**Comment by kuwoh** [comment] 2019-05-07 10:24
Odd how this also occurs to me using Firefox. It takes luck to fix it but even then fix isn't really consistent

**Comment by ApocalypsePlease0** [comment] 2019-05-19 09:59
Having all the same issues, but also it makes all the streams buffer every 5-10 seconds. When I disable it, everything works as usual.

**Comment by night** [comment] 2019-05-20 09:15
If the stream is buffering continually that could mean something is chewing CPU. Really the only way for us to debug would be for you to run a CPU profile and then upload it to this issue so we can take a look: https://developers.google.com/web/tools/chrome-devtools/evaluate-performance/reference

**Comment by ApocalypsePlease0** [comment] 2019-05-20 10:15
I have never done this, but is [this](https://mega.nz/#!6kBS3KAQ!iAFNJjyTsKEmDTuJpna_Riiv55wx4jMFRe80A9gb7uM) what you are looking for?

**Comment by ApocalypsePlease0** [comment] 2019-05-20 10:15
> If the stream is buffering continually that could mean something is chewing CPU. Really the only way for us to debug would be for you to run a CPU profile and then upload it to this issue so we can take a look: https://developers.google.com/web/tools/chrome-devtools/evaluate-performance/reference

I have never done this, but is [this ](https://mega.nz/#!6kBS3KAQ!iAFNJjyTsKEmDTuJpna_Riiv55wx4jMFRe80A9gb7uM)what you're looking for?

**Comment by Latias4Ever** [comment] 2019-05-29 21:14
So it's been over a month since I mentioned this problem, and well, it's still going. I really hope this isn't an issue caused by my Chrome version, as I don't want/have any plans to update it, but it's really aggravating have BTTV emotes showing up like this:

![image](https://user-images.githubusercontent.com/24550309/58591727-7304bf00-8256-11e9-88ff-def27d8af97b.png)

And no, the settings don't show up at all, either, so I can't do anything like exporting my settings, reinstall BTTV, and importing them back.

![image](https://user-images.githubusercontent.com/24550309/58591773-8f086080-8256-11e9-8392-976d708c285b.png)

**Comment by Latias4Ever** [comment] 2019-06-07 02:00
It's been fixed! Tonight's update has fixed BTTV for me completely!

Settings appear again:
![image](https://user-images.githubusercontent.com/24550309/59076903-e26a5680-88c7-11e9-92e2-4829cda57266.png)

Twitch Prime promotions is gone:
![image](https://user-images.githubusercontent.com/24550309/59076918-f1510900-88c7-11e9-9f71-ed1531bdf916.png)

Even message divisions are done, and emotes have been fixed!
![image](https://user-images.githubusercontent.com/24550309/59076928-fc0b9e00-88c7-11e9-93c3-432eb085b41d.png)

I'm not sure what fixed this, but it has all been fixed! After a month and half, I'm so happy to see this working again.

**Comment by night** [comment] 2019-06-07 04:25
fwiw the update we pushed would not have changed anything that would affect this, but perhaps twitch's site updates fixed it as a side-effect. glad to hear it's fixed, so i'll close this

**Closed by night** 2019-06-07 04:25 UTC
