### ISSUE TITLE
Emotes Not Working on VODs

### ISSUE THREAD

**Issue by jerrylee22** [night/BetterTTV#2685] opened 2017-09-20 16:50 UTC
This randomly happened yesterday when I returned to a VOD I was watching. I verified BTTV and browser update installation, restarted computer, checked on Firefox and Google Chrome. Confirmed working on live-streams, but no longer works in VODs. Noticed this when I started seeing tons of "LuL" text in chat.

BTTV Emotes setting is "On" (enabled).
Now noticing a "Post at *Clock*" icon on the chat window, timestamps are on, and all names are purple. Tried with and without Beta. 
White scroll bar in theatre mode on Firefox and only Firefox for some reason, too.

**Comment by Jfamig** [comment] 2017-09-21 00:36
The VOD chat is entirely broken, BTTV wise. It would be nice to have name colors as well as the BTTV emotes back for the VOD chat 🥇

**Comment by night** [comment] 2017-09-22 06:09
duplicate of #2683

**Closed by night** 2017-09-22 06:09 UTC
Labels: duplicate
