### ISSUE TITLE
Left side chat also shows followers in theater mode

### ISSUE THREAD

**Issue by Tobbax** [night/betterttv#4035] opened 2020-07-11 08:16 UTC
Use left side chat and theater mode your followers will also show besides chat
![image](https://user-images.githubusercontent.com/44871092/87219830-e3897500-c35e-11ea-8d0e-da928a49d49d.png)

using default (right side) no followers is show in theater mode
![image](https://user-images.githubusercontent.com/44871092/87219878-4b3fc000-c35f-11ea-93a8-899348cdced1.png)

pls help🙆‍♂️

**Comment by night** [comment] 2020-07-12 19:22
duplicate of #4029

**Closed by night** 2020-07-12 19:22 UTC
Labels: duplicate
