### ISSUE TITLE
Emotes lot loading when navigating though Twitch

### ISSUE THREAD

**Issue by kineese** [night/BetterTTV#2089] opened 2017-02-25 10:42 UTC
I just noticed that when I join a channel via direct URL, the emotes are loading fine.. The moment I navigate into a channel through the twitch-menu the emotes arent loading/showing up. Thats for twitch and bttv emotes.

**Comment by night** [comment] 2017-02-25 19:54
duplicate of #2022

**Closed by night** 2017-02-25 19:54 UTC
Labels: duplicate
