### ISSUE TITLE
Left Side Chat hides part of "Subscribe" popup when chat is in "Subscribers-Only Chat"

### ISSUE THREAD

**Issue by ethanharlig** [night/BetterTTV#3287] opened 2018-10-02 02:21 UTC
In a recent Twitch update, the chat will now display "Subscribers-Only Chat" if the chat is set to that for the streamer. By clicking the info icon next to that, a message pops up allowing users to click "Subscribe" which then opens a popup to the left about how to subscribe to that channel.

If you are using the Left Side Chat option in BetterTTV, the popup detailing how to subscribe to a channel is hidden off to the left of the window as can be seen here:![left side chat](https://user-images.githubusercontent.com/11605206/46325764-b830fe00-c5ae-11e8-8bf1-94cb669d2d61.PNG)

For reference, here is how the popup should look when the chat is on the right side: 
![right side chat](https://user-images.githubusercontent.com/11605206/46325790-db5bad80-c5ae-11e8-8acd-c135dd16bc94.png)

I'll start working on this but if someone has more free time, they're also welcome to!

**Comment by Nareese** [comment] 2018-10-02 02:40
A similar issue related to the subscribe popup in left side chat mode has been brought up previously (duplicate of #3198 and #3228) and night marked that original issue as "can't fix", with the comment "this is not something we can fix due to how twitch designed their popouts".  I would expect this issue would be the same.  Of course, if you can actually fix it, feel free to submit a PR. :)

**Closed** 2018-11-19 02:55 UTC
Labels: bug
