### ISSUE TITLE
Empity bar above chat

### ISSUE THREAD

**Issue by expllosao** [night/BetterTTV#728] opened 2015-09-26 00:20 UTC
So, there is an empity bar above the chat since I begun using the bttv. Idk if it is supposed to be there, if I have a config wrong or what, but I cant see the delay and that bothers me.. :(

Sorry for coming with such a little problem that must come from my own dumbness.

An image, if it is needed:
![capturar](https://cloud.githubusercontent.com/assets/13670489/10114658/1d0e8fd4-63cb-11e5-8449-78ba21c47953.PNG)

Edit: I forgot to mention that it sometimes becames normal, showing rk9 mode and chat delay. That is why I came here, I am not sure if a misconfiguration can make this random behavior...

Edit 2: I deactivated darkenTTV in the configs and the bar showed properly. But I like darkenTTV T^T

Edit 3(last one, I hope): I've been playing around this and I noticed that the bar appears as normal when I open a stream. It's only after a few seconds that it bugs out.

**Comment by night** [comment] 2015-09-27 05:31
What other browser extensions are you using? Have you tried disabling those?

**Comment by expllosao** [comment] 2015-09-30 02:04
im travelling right now. as soon as i get to my computer i answer you :P

**Comment by night** [comment] 2015-09-30 21:13
I'm closing this since it cannot be reproduced. Feel free to respond if you're still having issues.

**Closed by night** 2015-09-30 21:13 UTC
Labels: invalid
