### ISSUE TITLE
Ability to change highlight colour.

### ISSUE THREAD

**Issue by Gigabyte5671** [night/BetterTTV#1655] opened 2016-10-14 07:48 UTC
It would be nice to have the ability to change the highlight colour to something a bit less harsh than red.

**Comment by EhsanKia** [comment] 2016-10-14 08:05
In the future it'd maybe nice to have a much more advanced highlight feature with multiple custom colors and such, but I doubt this will come anytime soon, so in the meantime, I recommend using an extension like Stylish to customize the color on your end for yourself.

If you need help with the css, I'd be happy to help.

**Comment by night** [comment] 2016-10-14 08:24
duplicate of #237

**Closed by night** 2016-10-14 08:24 UTC
Labels: duplicate
