### ISSUE TITLE
Channel view - offline notification / past broadcast.

### ISSUE THREAD

**Issue by Rushreflex** [night/BetterTTV#420] opened 2015-05-15 13:32 UTC
Can you please add a feature to BTTV that removes this annoying notification:

![header](https://cloud.githubusercontent.com/assets/11164475/7653638/86b55796-fb17-11e4-90ca-47565ee988ca.PNG)

I don't need this, I'm already able to realize that the channel I opened is offline! And it pushes the content down and takes too much space! display: none; FTW

Thanks

**Comment by Powersource** [comment] 2015-05-15 22:34
There was a while when it was there while the channel was online, but I believe that is fixed. What "content" is it in the way of when the channel is offline? If it doesn't end up in bttv and you still want it I'd suggest making a style for stylish or something similar that hides it. https://chrome.google.com/webstore/detail/stylish/fjnbnpbmkenffdnngjfgmeleoegfcffe?hl=en

**Comment by night** [comment] 2015-05-16 20:08
Duplicate of #366

**Closed by night** 2015-05-16 20:08 UTC
Labels: duplicate
