### ISSUE TITLE
Channel list is broken when "Left Side chat is enabled" in Theatre mode

### ISSUE THREAD

**Issue by Chromerian** [night/betterttv#4033] opened 2020-07-10 22:02 UTC
My usual set up is left side chat, theatre mode. Then if I am running more than one stream I have the stream window at it's thinnest so chat appears below the stream.
A few weeks ago, the channel list started messing with the chat, overlapping it. It wasn't a big issue but now it is even more broken all of a sudden. With left chat activated, when I go into minimised view, the channel list still appears and pushes the chat to the side so I can't access the emote menu or see the right edge of the chat. Please can you fix this and maybe even have a option to remove the channel list bar entirely as I never use it. There are options to remove offline and friends from it but not the whole bar.

Supplied are screenshots of:
Right side chat, large theatre mode, all working: https://i.imgur.com/2EtjjHL.jpg
Right side chat, small theatre mode, all working: https://i.imgur.com/XdPffmk.png
Left side chat, large theatre mode, Channel list showing (it used to stay hidden in theatre): https://i.imgur.com/x101Uh7.jpg
Left side chat, small theatre mode, chat completely broken and shifted due to channel list: https://i.imgur.com/c7fhnEQ.png

**Comment by night** [comment] 2020-07-12 19:22
duplicate of #4029

**Closed by night** 2020-07-12 19:22 UTC
Labels: duplicate
