### ISSUE TITLE
Left Side Chat malfunctioning

### ISSUE THREAD

**Issue by Riderpride639** [night/betterttv#3856] opened 2020-05-11 20:46 UTC
Just started noticing today (May 11, 2020) after a couple of hours of watching Twitch (started noticing the issue at about 2:30pm CST (UTC-6) that left-side chat with the BTTV extension (in both Chrome and Edge, verified both are currently up to date.  Chrome Version 81.0.4044.138, Edge Version 44.18362.449.0) that the chat box would disappear entirely.  Clicking the |-> arrow on the stream would move the stream window accordingly but chat would not appear.  Clearing cookies and cache would reset BTTV settings to default and chat would work again, but as soon as left-side chat was enabled again, chat disappeared.  Disabling the extension or turning off left-side chat would make the chat box reappear as normal, but would like to be able to have the left-side working again.

**Comment by Nareese** [comment] 2020-05-11 21:51
duplicate of #3852

**Closed** 2020-05-13 07:08 UTC
Labels: duplicate
