### ISSUE TITLE
Multiple lists of highlighted messages in chat

### ISSUE THREAD

**Issue by Orciument** [night/betterttv#4018] opened 2020-07-02 19:32 UTC
It would be nice if it were possible to have multiple "Set Highlight Keywords" lists so that you can highlight words in different colors so you can immediately see what the message is about. It would also be very useful to moderate that one could differentiate whether it is a critical word or, for example, a different spelling of your name

**Comment by night** [comment] 2020-07-05 21:03
duplicate of #237

**Closed by night** 2020-07-05 21:03 UTC
Labels: duplicate
