### ISSUE TITLE
<deleted link> , "friend has joined" and emote menu

### ISSUE THREAD

**Issue by Monkey151546** [night/BetterTTV#2877] opened 2017-12-16 23:57 UTC
is it possible to show links instead of seeing <deleted links> ? some streamer set their stream that way so nobody can post links,

 also in old twitch we could see "you friend x has started watching HeyGuys" or something like that , is it possible to bring it back? 

also the emote menu doesnt load half the time, in change log it says it was fixed but for me it doesnt load all the time, just sometimes

thank you!

**Comment by night** [comment] 2017-12-18 03:38
duplicate of #2605 and #2787

**Closed by night** 2017-12-18 03:38 UTC
Labels: duplicate
