### ISSUE TITLE
After exiting the hidden chat mode, bttv emotes are not displayed

### ISSUE THREAD

**Issue by Xambey** [night/BetterTTV#3454] opened 2019-05-04 15:00 UTC
After exiting the hidden chat mode, bttv emotes are not displayed

**Playback steps:**
1. Open a stream
2. Type something in chat with bttv emotes
3. Open settings and push "Hide chat"
4. Push "Show chat"

**Result:**
BTTV emotes aren't displayed
Google Chrome Version 74.0.3729.108 (Official Build) (64-bit)

**Comment by Nareese** [comment] 2019-05-04 17:40
This is essentially the same underlying issue as #3184 (because popping out the chat hides the main chat, and closing the popout re-opens the main chat, with the same results you are seeing).  This is probably a low priority to fix, as the problem is trivially resolved by just refreshing the page.

**Comment by Xambey** [comment] 2019-05-04 17:44
> This is essentially the same underlying issue as #3184 (because popping out the chat hides the main chat, and closing the popout re-opens the main chat, with the same results you are seeing). This is probably a low priority to fix, as the problem is trivially resolved by just refreshing the page.

Yes, I know that this is solved by reloading the page, but this is not very convenient. For example, you communicate with someone, suddenly the chat freezes and you need to quickly update the chat (only). Conveniently quickly hide and show chat, so as not to miss the answer of the interlocutor. When reloading the page, everything loads slowly...

**Comment by night** [comment] 2019-05-06 08:55
None of the react re-rendering issues are easy to fix. If they were it'd be fixed already. lol

**Closed** 2019-05-06 08:55 UTC
Labels: duplicate
