### ISSUE TITLE
Automatic theater mode not working suddenly.

### ISSUE THREAD

**Issue by PancakeAstr0naut** [night/BetterTTV#3685] opened 2019-12-09 05:07 UTC
My twitch has been acting up recently after the last update. My followed channels list doesnt appear automatically and starting yesterday my automatic theater mode stopped working. The only other addon i use is FrankerFaceZ I tried disabling it but that didn't fix it.

**Comment by whitecrownclown** [comment] 2019-12-09 07:25
There is a general issue right now that breaks some features, including `Automatic Theater Mode`. This is fixed in https://github.com/night/BetterTTV/pull/3680.

**Comment by night** [comment] 2019-12-09 08:24
duplicate of #3675

**Closed by night** 2019-12-09 08:24 UTC
Labels: duplicate
