### ISSUE TITLE
Enable/Disable red highlight

### ISSUE THREAD

**Issue by ScottieS** [night/BetterTTV#1041] opened 2016-03-24 06:13 UTC
I have been talking to a few people in quite a few popular chats and a lot of people talked about how they liked how clean twitch chat looked when twitch just highlights your name in black. It would be cool if you made an option to disable the way that BTTV highlights the whole message in red!

**Comment by saaitv** [comment] 2016-03-25 08:04
You can do this by removing your name from the "Set Highlight Keywords" list.

It's as simple as a toggle switch for it but it works.

**Comment by vendethiel** [comment] 2016-03-25 08:17
if you do remove your name, it won't even highlight your name

**Comment by night** [comment] 2016-04-01 03:18
duplicate of #237

**Closed by night** 2016-04-01 03:18 UTC
Labels: duplicate
