### ISSUE TITLE
No options

### ISSUE THREAD

**Issue by erteb** [night/BetterTTV#2471] opened 2017-05-21 20:03 UTC
There are no options
![schermafbeelding 2017-05-21 om 22 03 10](https://cloud.githubusercontent.com/assets/28846401/26286965/54145ee6-3e71-11e7-858b-28b47178b401.png)

**Comment by night** [comment] 2017-05-21 20:21
duplicate of #2464

**Closed by night** 2017-05-21 20:21 UTC
Labels: duplicate
