### ISSUE TITLE
In chat commands do not produce a response + Tab emote completion still not working.

### ISSUE THREAD

**Issue by Xyaint** [night/betterttv#7058] opened 2024-09-29 18:46 UTC
### Describe the bug

Whenever you use an in chat command, it does not show up within the chat.

The tab emote completion is still not working either, even though it has been moved to completed

### Steps to reproduce

1. Go to any channel.
2. Type any commands that would reproduce in chat (like /followed, /follows, /uptime, /viewers)
3. See nothing appear.

1. Also only BTTV emotes are still being autofilled when pressing tab.

### Expected behavior

Whenever you type any BTTV commands, they should give their corresponding results. I would like to easily see how long I have followed or how long the streamer has been live for.

Also, even though the TAB completion report has been deemed as fixed, it still is not fixed.

### Screenshots

![image](https://github.com/user-attachments/assets/bf7b7d0b-c8f4-4a22-b5c5-8516552c30f7)
![image](https://github.com/user-attachments/assets/9913a319-f9ad-45bd-8a12-2e11075a026a)

### Device information

- Device : PC, Chrome

### BetterTTV Version

7.6.6

### Version Check

- [X] I have checked that I'm using the newest version of BetterTTV available.

**Comment by dclstn** [comment] 2024-09-30 11:07
Duplicate of #7053 

This comment is relevant: https://github.com/night/betterttv/issues/7052#issuecomment-2380739165

**Closed by dclstn** 2024-09-30 11:07 UTC
Labels: bug, duplicate
