### ISSUE TITLE
[Bug] Chat on left removes followed channel tool-tips

### ISSUE THREAD

**Issue by Quitch** [night/BetterTTV#3731] opened 2020-01-25 12:46 UTC
**Technical**

OS: Windows 10 Pro x64 1909
Browser: Microsoft Edge (Chromium) Version 79.0.309.71 (Official build) (64-bit)

**Description**

When the chat is on the left-hand side of the screen the tool-tips for followed channels are no longer displayed on mouseover.

**Steps to reproduce**

1. Switch on option to move chat to left-side
2. Shrink followed channels window
3. Mouse-over a channel

**Expected outcome**

A tool-tip will be displayed with the name of the channel, the current stream title and the number of views.

**Current outcome**

No tool-tip is displayed. Presumably it is still being displayed to the right of the icon, which means it is projected off-screen.

**Comment by night** [comment] 2020-02-07 07:53
this can't be fixed due to absolute positioning without any unique identifiers for us to detect. duplicate of #3165

**Closed by night** 2020-02-07 07:53 UTC
Labels: duplicate
