### ISSUE TITLE
[Feature Request] Hide "Based on your Viewing History"

### ISSUE THREAD

**Issue by LinkUK** [night/BetterTTV#2879] opened 2017-12-18 02:09 UTC
Could this be added as an option to remove this from the "Following" page?

It just adds a lot of clutter and always recommends channels I would never watch. On the old Twitch site we used to have an option on each video to remove the recommendation but that has dissapeared since they overhauled the site.

**Comment by night** [comment] 2017-12-18 03:12
duplicate of #1311

**Closed by night** 2017-12-18 03:12 UTC
Labels: duplicate
