### ISSUE TITLE
Feature suggestion; emote attribution

### ISSUE THREAD

**Issue by IZeeRocks** [night/betterttv#5588] opened 2022-08-20 22:07 UTC
Could be cool if there was a way to do emote attribution like on native twitch emotes. For example of how it could be useful, that way u can upload emotes from ffz that arent on bttv, and attribute it to the original creator, so you can have the emote on bttv, and if the creator accepts the attribution, then it says they created the emote rather than the person who uploaded it.

**Comment by dclstn** [comment] 2022-08-20 22:38
duplicate of #5482

**Closed by dclstn** 2022-08-20 22:38 UTC
