### ISSUE TITLE
Turn japanese/chinese/korean letters into normal names

### ISSUE THREAD

**Issue by ultimate1337** [night/BetterTTV#1500] opened 2016-09-03 15:48 UTC
there should be a setting that turns japanese/chinese/korean letters in names into the normal name

**Comment by night** [comment] 2016-09-06 00:12
Duplicate of #1472

**Closed by night** 2016-09-06 00:12 UTC
Labels: duplicate

**Comment by kekos91** [comment] 2016-10-07 16:35
This is a feature we NEED that replace the nicknames in the chat window. This is a _feature_ that many people would use for sure.
