### ISSUE TITLE
Auto remove Raid referrer from URL

### ISSUE THREAD

**Issue by yrk06** [night/betterttv#4458] opened 2021-04-14 18:29 UTC
When someone Raids another channel, `referrer=raid` is added to the URL query. Having a viewer watching through a URL with that parameter causes those views to not be counted in the Average views for the channel, thus making raids inefective for channel growth.

Since so many users have the BTTV extension, the idea is for a new Raid Module. When the new module detects the `referrer` parameter, it redirects the user to the raided channel. This feature could be toggled on and off by a new setting, and it can be enabled by default, that way most users won't have the trouble to enable it

**Comment by Nareese** [comment] 2021-04-15 17:16
Duplicate of #3648

**Comment by yrk06** [comment] 2021-04-15 19:32
The issue linked was closed, I wonder if the new inclusions proposed (having a setting so users could opt out and having a working Branch) can make the proposal be reconsidered. Since users can already remove the `referrer=raid` from the URL manually, this only automates that process, in that way users won't have to manually switch everytime, but they can select the extension to do so. This wouldn't interfere with twitch way of calculating viewership numbers because it's something users can do on their own already.

**Comment by Nareese** [comment] 2021-04-15 20:09
> The issue linked was closed.

The issue linked was closed and tagged *wontfix*.   It would probably be safe to assume that is because night agreed with xgerhard's reasoning for why this is not a feature we will implement.  We will not implement features into our application whose sole purpose is sabotaging Twitch's analytics.  The fact that you can "on your own" is irrelevant.  Automating it in BTTV would put our entire application at risk of being banned by Twitch, especially since your PR defaults the setting to on.  At minimum, Twitch would come to night and tell him to remove it, and he almost certainly would.

You are welcome to leave your issue and PR open until night closes this one, but I would estimate your chances of a merge on this issue at somewhere near zero.

**Closed** 2021-04-16 00:50 UTC
