### ISSUE TITLE
[Feature Request] The option to see stream uptime under the video and in directory

### ISSUE THREAD

**Issue by Jd-19** [night/BetterTTV#3468] opened 2019-05-24 16:18 UTC

**Comment by Nareese** [comment] 2019-05-24 19:05
The directory suggestion has been suggested before, and is still open as a request (duplicate of #2196), but it's been open for more than 2 years now, and as such, I wouldn't hold my breath for it to be implemented soon.  The uptime under the video has been suggested multiple times and rejected each time as UI clutter (see #628 #1014 #1088 #1698 #1975 #1989 etc).

**Closed** 2019-06-07 04:44 UTC
Labels: duplicate
