### ISSUE TITLE
Suggestion: More personal emotes for subs on BTTV!

### ISSUE THREAD

**Issue by pumpkinpieman** [night/BetterTTV#2642] opened 2017-08-25 23:34 UTC
I feels as though an increase from 5 to 10, or 15 emotes would be wonderful for subs.

**Comment by Stoupedog** [comment] 2017-09-01 23:47
Duplicate of #2080

**Closed** 2017-09-02 17:41 UTC
Labels: duplicate

**Comment by casthekiller** [comment] 2018-02-06 19:23
I 100% agree more personal emotes would be amazing
