### ISSUE TITLE
Settings Request

### ISSUE THREAD

**Issue by morkhork** [night/BetterTTV#1009] opened 2016-03-11 09:35 UTC
I think a good setting feature to add to BTTV would be to have chat on the left if that is possible. Idk if it's possible to do it myself. I use 2 monitors and it's hard to see the chat sometimes. :^) Thanks for reading.

**Comment by voloshink** [comment] 2016-03-11 10:15
dupe of #202

**Closed by voloshink** 2016-03-11 10:15 UTC
