### ISSUE TITLE
Menu/Chat Flip

### ISSUE THREAD

**Issue by acejig** [night/BetterTTV#627] opened 2015-08-05 04:50 UTC
Swap the positions of the Chat Menu and the User Menu, which use the IDs "right_col" and "left_col"

![image](https://cloud.githubusercontent.com/assets/13654038/9078401/839905b8-3b03-11e5-93e4-57c648f52500.png)

This is useful for me because I use dual monitors and it allows me to read the chat more easily without having to snap my neck to turn my head all the way to the far right of the right monitor

**Comment by voloshink** [comment] 2015-08-06 16:31
I'd use this feature too, unfortunately it's a bit more work than just swapping some ids, but i'll see if i can make it happen.

**Comment by night** [comment] 2015-08-06 21:04
Duplicate of #202 

If @voloshink wants to add this, he can. I'll reopen the first issue.

**Closed by night** 2015-08-06 21:04 UTC
Labels: duplicate
