### ISSUE TITLE
[Feature Request] Change text entry options to not freeze stream

### ISSUE THREAD

**Issue by Dragoonseal** [night/betterttv#3793] opened 2020-03-22 11:58 UTC
On Chrome, pressing any settings button that requires text entry will freeze the stream. This includes the rename button on mod cards, and the "Set Blacklist keywords," "Set Highlight Keywords," "Set Font," and "Set Font Size" buttons in the chat cogwheel options.

Pressing any of them brings up a centered text input panel, and the stream stops buffering once they do. Once the buffer runs out (which can happen within 0.5 of a second) the stream freezes and won't continue until the text input panel is closed. And once the panel is closed the stream starts playing again with delay equal to how long you had the text panel open. If you had the panel open a minute, now you have 1 minute stream delay, so you need to pause/play to catch up. Additionally, often once you close the panel the stream glitches and hangs indefinitely, again forcing a pause/play.

**Comment by Scrxtchy** [comment] 2020-04-18 09:48
I am getting this issue on Firefox too

**Comment by night** [comment] 2020-08-30 05:58
duplicate of #494

**Closed by night** 2020-08-30 05:58 UTC
Labels: duplicate
