### ISSUE TITLE
[feature idea] Add configuration option to remove/hide the very broken "based on your viewing history" suggested streams

### ISSUE THREAD

**Issue by benpurdy** [night/BetterTTV#2273] opened 2017-04-17 04:28 UTC
There's a random list of streams that sometimes appears on the twitch home page claiming to be a list of videos suggested based on user viewing history. This list is basically 100% the opposite of what I watch, or want to watch. Googling this "feature" turns up a lot of angry users describing the same frustration. I would love to have a config option to just delete the content from the page so we don't have to see it any more. I've been manually removing each stream whenever they appear but I can't find a way to simply disable this annoying feature completely.

**Comment by night** [comment] 2017-04-24 00:13
I don't see that on the home page. If you mean the following page, that's a duplicate of #1311

**Closed by night** 2017-04-24 00:13 UTC
Labels: duplicate
