### ISSUE TITLE
[Bug] Hide Recommended Channels

### ISSUE THREAD

**Issue by SaiyanOfDarkness** [night/BetterTTV#2434] opened 2017-05-10 07:27 UTC
So I have Hide Recommended Channels turned on, and it works for both Recommended Channels and Channels Your Friends Like.

However sometimes when refreshing they still appear despite having the option enabled.

**Comment by KTScientist** [comment] 2017-05-11 13:18
I have the same problem ,every time i open a stream i have to check and uncheck Recommended Channels

**Comment by night** [comment] 2017-05-13 20:01
duplicate of #2399

**Closed by night** 2017-05-13 20:01 UTC
Labels: duplicate
