### ISSUE TITLE
Hosted Streams Still Playing

### ISSUE THREAD

**Issue by SirWeltschmerz** [night/BetterTTV#3118] opened 2018-05-22 15:59 UTC
Despite enabling "Disable Host Mode", hosted channels still play on the channel page I am watching which is currently offline.

I never had this problem until about last week or the week before. Hopefully it's just something small on Twitch's API.

**Comment by Nareese** [comment] 2018-05-22 17:45
duplicate of #3116

**Closed** 2018-05-29 01:50 UTC
Labels: duplicate
