### ISSUE TITLE
their is a bug with darken mode

### ISSUE THREAD

**Issue by gamernation89** [night/BetterTTV#2366] opened 2017-04-28 21:14 UTC
their is a bug with darken mode that it will not darken the title only.. i cleared all my cache my third party app settings, anything that i could clear and it still there... please fix this 
![screenshot 21](https://cloud.githubusercontent.com/assets/19208617/25547608/253c900e-2c36-11e7-9920-5b8f8809cc39.png)

**Comment by Slikrick** [comment] 2017-04-28 23:31
Duplicate of #2365

**Closed** 2017-04-28 23:38 UTC
