### ISSUE TITLE
Hide "Watch $Streamer's Last Broadcast!"

### ISSUE THREAD

**Issue by sjspero** [night/BetterTTV#889] opened 2016-01-05 22:54 UTC
Could you add an option that hides the dialog, or add a button that allows users to close it without refreshing the page?

If a stream drops momentarily, Twitch displays this box ![image](https://cloud.githubusercontent.com/assets/3386280/12129974/1b3998ac-b3d5-11e5-9aa1-a48a82f5368e.png) and the only way to get rid of it is to refresh the page.

Imgur mirror i.imgur.com/yyXwB20.png

**Comment by night** [comment] 2016-01-05 23:08
Duplicate of #366

**Closed by night** 2016-01-05 23:08 UTC
Labels: duplicate
