### ISSUE TITLE
Add option to turn off new spam-filtering

### ISSUE THREAD

**Issue by Imalayan** [night/BetterTTV#685] opened 2015-08-31 03:59 UTC
self explanatory, some people want to judge by themselfes if something is spam (and in case of moderators, which specific spam)

**Comment by thinkpad4** [comment] 2015-08-31 05:37
It is in the works, the next major code push will include it

**Comment by voloshink** [comment] 2015-08-31 18:27
Duplicate of #653

**Closed** 2015-08-31 18:27 UTC
Labels: duplicate
