### ISSUE TITLE
BTTV - opting out offline channels broken

### ISSUE THREAD

**Issue by IAnon9** [night/betterttv#3897] opened 2020-05-16 21:13 UTC
![bugreport bttv](https://user-images.githubusercontent.com/65468386/82130357-fe11f880-97ca-11ea-9316-c176f0d8720d.JPG)

using current version of google chrome.
bug noticed approximately since 16.04.2020
not sure what else info you would need. hit me up if you need anything else. cheers.

**Comment by night** [comment] 2020-05-18 22:48
duplicate of #3868

**Closed by night** 2020-05-18 22:48 UTC
Labels: duplicate
