### ISSUE TITLE
[Feature Request] Filter repeat messages/Personal r9k

### ISSUE THREAD

**Issue by kingl4d** [night/BetterTTV#2035] opened 2017-02-05 21:46 UTC
Not sure if this is possible but I figure there's no harm is asking.

One thing I find most obnoxious about Twitch is how often chat gets flooded with spam.
I would absolutely love it if I could have a personal r9k feature to just auto-hide spam. Seeing it once is fine, but having the whole chat get spammed every 3 seconds is very annoying when you don't care to circlejerk with thousands of kids. I'm sure I'm not the only one who would love to have this.
Thanks.

**Comment by night** [comment] 2017-02-06 10:01
duplicate of #78

**Closed by night** 2017-02-06 10:01 UTC
Labels: duplicate
