### ISSUE TITLE
Disable host mode broken on chrome

### ISSUE THREAD

**Issue by Rainami** [night/BetterTTV#2656] opened 2017-08-30 14:05 UTC
For the last couple months the function hasn't been working and it driving me crazy.
I've tried with no other extensions enabled and its still busted.
I'm using, Version 60.0.3112.101 (Official Build) (64-bit)

**Comment by Nareese** [comment] 2017-08-30 16:55
duplicate of #2601

**Closed** 2017-09-02 17:42 UTC
Labels: duplicate
