### ISSUE TITLE
Channels Issue

### ISSUE THREAD

**Issue by deathofrats0808** [night/betterttv#6841] opened 2024-06-01 13:31 UTC
### Describe the bug

BTTV no longer hides recommended channels or offlien followed channels despite those settigns being activated.
<img width="227" alt="Screenshot 2024-06-01 at 14 27 48" src="https://github.com/night/betterttv/assets/67862576/87f728d2-a64a-4d22-a877-09905fd62dc5">
<img width="606" alt="Screenshot 2024-06-01 at 14 27 52" src="https://github.com/night/betterttv/assets/67862576/f3379ff0-d9f7-414c-af6a-dea5958775b2">

Reinstalling has not fixed the issue.

### Steps to reproduce

Unsure. Do not know what triggered in the first place.

### Expected behavior

The offline followed channels and recommended channels shoudl have been absent.

### Screenshots

Screenshots are in description

### Device information

Macbook Pro, Sonoma 14.5, Chrome, Version 125.0.6422.141 (Official Build) (arm64)

**Comment by frostcone** [comment] 2024-06-02 13:09
Same issue on Brave

**Comment by night** [comment] 2024-06-03 14:07
duplicate of #6837

**Closed by night** 2024-06-03 14:07 UTC
Labels: bug
