### ISSUE TITLE
Left-Aligned Chat / Horizontally flip page arrangement

### ISSUE THREAD

**Issue by Twistedlink07** [night/BetterTTV#306] opened 2015-03-28 07:39 UTC
Using a second monitor placed to the right of my primary, I noticed a want for chat to be closer to the primary monitor instead of off at the far edge of my display setup.

**Comment by Twistedlink07** [comment] 2015-03-28 08:03
I will be sifting through the project in attempts to implement this myself.

**Comment by night** [comment] 2015-03-28 17:46
Duplicate of #202

**Closed by night** 2015-03-28 17:46 UTC
Labels: duplicate
