### ISSUE TITLE
Emotes

### ISSUE THREAD

**Issue by GoddessGamer** [night/BetterTTV#1185] opened 2016-05-19 03:30 UTC
I've been having problems with BTTV emotes not showing up at all in the BTTV emote list. I turned the settings on and off, I enable and disable, I'v uninstalled and reinstalled BTTV and the emotes still wont show up. The only emotes that will show up are the global Twitch emotes. I don't know how to fix it or what caused this.

**Comment by voloshink** [comment] 2016-05-19 03:32
Are you using the twitch emote menu or betterttv emote menu?

**Comment by GoddessGamer** [comment] 2016-05-19 03:35
betterTTV emotes menu.

**Comment by voloshink** [comment] 2016-05-19 03:38
oh now i remember, i think cletus broke the emote menu

**Comment by GoddessGamer** [comment] 2016-05-19 03:41
uh? care to explain?

**Comment by voloshink** [comment] 2016-05-19 03:42
something that needs to be fixed on our end. nothing you can do for now, i don't think

**Comment by GoddessGamer** [comment] 2016-05-19 03:43
odd, it seems like i'm the only one that this is happening to.

**Comment by cletusc** [comment] 2016-05-19 04:21
Gonna need some debugging if possible. Are there any browser console errors? Can you provide a screenshot of your BTTV Settings?

If you can, enable debugging on the emote menu.
1. Open your console
2. Enter `emoteMenu.toggleDebug();`
3. Refresh and open the menu after a few seconds
4. Provide console output

**Comment by GoddessGamer** [comment] 2016-05-19 05:08
I'm sorry, but where exactly do i put the toggleDebug? I don't have any options to put anything anywhere. And I'm not getting any errors. I don't think I can provide i screenshot

**Comment by cletusc** [comment] 2016-05-19 05:14
At the very least, tell me what you have for the `BetterTTV Emotes` and `Emote Menu` settings.

**Comment by GoddessGamer** [comment] 2016-05-19 05:58
i have them both on, and yet I still don't get the emotes. I've tried refreshing the page and a whole bunch of things and they still don't show up at all

**Comment by cletusc** [comment] 2016-05-19 07:38
Unable to reproduce. Without debugging, I can't help.

If both options are on, then press `Ctrl+Shift+I`, and on the `Console` tab, type `emoteMenu.toggleDebug();` then refresh. The console should start spitting out messages prefixed with `[Emote Menu]`--take a screenshot of all the messages. Specifically, I am looking for a `Getter registered: BetterTTV` message.

For clarity, this is _not_ an emote-menu-code-specific problem, this would be a problem with how BTTV interacts with the emote menu API. Possibly related to #1182 somehow.

Works for me on Firefox
![](http://i.imgur.com/EBkefak.png)

and Chrome
![](http://i.imgur.com/M04d7oN.png)

**Closed** 2016-05-20 00:08 UTC
Labels: invalid
