### ISSUE TITLE
Option to block autoplay video when opening a channel.

### ISSUE THREAD

**Issue by Bogdanov89** [night/betterttv#4818] opened 2021-09-14 03:05 UTC
**Currently none of the options in BetterTTV prevent this specific autoplay (Firefox 92 64bit, Windows 10).**
When you click on a twitch channel in the left panel it takes you to that channels page.
It also auto-plays whatever it wants when it opens that channels page (when channel is offline it plays either a vod or autohost).
This can be extremely aggravating since it can be of various volume, content and even other "check out" streams, screeching at peaking volume.
Please implement an option that prevents this specific autoplay.
Thank you for all the work you do.
![auto play](https://user-images.githubusercontent.com/55892027/133188778-4c58ebbb-3a52-4784-8918-06429c59dd3d.jpg)

**Comment by Nareese** [comment] 2021-09-14 03:28
duplicate of #4405

**Closed** 2021-09-16 20:34 UTC
Labels: duplicate
