### ISSUE TITLE
Hide Recommended Channels is not working

### ISSUE THREAD

**Issue by BlackIceFIN** [night/betterttv#4111] opened 2020-08-25 18:11 UTC
Hi! I'm using Chrome browser and notice that I still see recommended channels, even in settings I have that what makes those disapear. So, some reason is not working anymore. All other settings are working really well. :/

**Comment by Nareese** [comment] 2020-08-25 19:02
duplicate of #4023

**Closed** 2020-08-30 02:09 UTC
Labels: duplicate
