### ISSUE TITLE
Can't fullscreen properly

### ISSUE THREAD

**Issue by 1WaywardSon1** [night/BetterTTV#1810] opened 2016-12-02 09:42 UTC
So there was nothing wrong yesterday night but when I fullscreen any stream this morning video doesnt stretch for the whole screen. Tried restarting everything. Disabling the BetterTTV solves the problem. If you guys updated the extension there is something wrong with it.
![asfasf](https://cloud.githubusercontent.com/assets/24313663/20829326/adb4b16e-b88c-11e6-99bd-dee2aa54df09.jpg)

**Comment by 1WaywardSon1** [comment] 2016-12-02 09:42
Oh and found multiple people with the same issue.

**Comment by n8goody** [comment] 2016-12-02 17:41
I have this problem as well

**Comment by clarkycal** [comment] 2016-12-02 20:20
I can confirm this is an issue with Chrome as well, I have disabled the Extension temporarily

**Comment by Leifman27** [comment] 2016-12-03 04:18
Yesterday i managed to somehow close/open the stream tabs and end up with it working properly... no go today. 
No matte what i do the fullscreen is fucked up. :'(

**Comment by 1WaywardSon1** [comment] 2016-12-03 09:25
Mini Update: One of the twitch staff said yesterday night that they're working wwith betterttv guys but problem is a little bit tricky.

**Comment by stanel3ss** [comment] 2016-12-03 15:14
same in opera 41, never happened in chrome
doesn't happen in popout window

**Comment by cAyou66** [comment] 2016-12-03 18:02
If you go in Studio mode and then double click on the stream, you will get correct full-screen. That's the only way I found to get proper full-screen so far since the last twitch update.

**Comment by Leifman27** [comment] 2016-12-03 18:54
holy shit, thanks cAyou66! i was actually in "theater mode" (you called it studio mode?) and never thought to even try and click fullscreen while in it LOL.
i just did now and noticed it indeed shows correct full-screen
so thanks! had no idea.

**Comment by cAyou66** [comment] 2016-12-03 18:56
Oh yes my bad, I'm in french language, I thought Studio was the same in English :D But yeah, Theater makes more sense. So yes, Switch to Theater and then double click on the stream :)

I'm sure they will fix it very soon anyway (hopefully !)

**Comment by EhsanKia** [comment] 2016-12-03 20:25
Should be fixed now.

**Closed by EhsanKia** 2016-12-03 20:25 UTC

**Comment by stanel3ss** [comment] 2016-12-04 01:43
holy shit, I noticed it worked again and thought maybe a lucky glitch
daaamn you guys work fast

**Comment by 1WaywardSon1** [comment] 2016-12-04 02:18
It's indeed fixed. Good job guys.
