### ISSUE TITLE
Theatre Mode Chat background white

### ISSUE THREAD

**Issue by ItIsKotov** [night/BetterTTV#2423] opened 2017-05-06 09:14 UTC
Hi,

as of this morning the chat background in theatre mode keeps getting white. turning off BTTV fixes the issues, but what is life without BTTV.

BibleThump
![unbenannt2](https://cloud.githubusercontent.com/assets/28479520/25771266/350f62a0-324d-11e7-92b3-79512653c838.PNG)

**Comment by EhsanKia** [comment] 2017-05-06 18:32
This happen with automatic theatre mode. Short term fix is either leave/reenter theatre mode, or just manually enter it for now. It will be fixed soon.

**Comment by night** [comment] 2017-05-13 19:52
duplicate of #2406

**Closed by night** 2017-05-13 19:52 UTC
Labels: duplicate
