### ISSUE TITLE
TwitchTV does not show deleted messages on firefox

### ISSUE THREAD

**Issue by brunoaquino99** [night/betterttv#7057] opened 2024-09-29 06:53 UTC
### Describe the bug

Deleted twitch chat messages are no longer being revealed in my browser (Firefox), the settings are to reveal and highlight these messages. 

### Steps to reproduce

I tested the extension on Microsoft Edge and it shows normally. I have already reinstalled Firefox and the Extension, but without success.

### Expected behavior

Deleted messages are highlighted in red.

### Screenshots

The first image in Microsoft Edge
![image](https://github.com/user-attachments/assets/1003a1d0-52ee-49da-af64-a2bef488f141)
The second image in Microsoft Edge
![image](https://github.com/user-attachments/assets/0d3f8519-17bd-4cf5-9aad-a24e5c0502f6)
Setting up both on bettertv
![image](https://github.com/user-attachments/assets/1fbd0df1-7422-4d3a-a05f-d00a95c36bec)

### Device information

Windows 10: Mozilla Firefox - Version 130.0.1 (64 bits); Microsoft Edge - Version 129.0.2792.65 (64 bits)

### BetterTTV Version

7.6.6 (Firefox); 7.6.7 (Edge)

### Version Check

- [X] I have checked that I'm using the newest version of BetterTTV available.

**Comment by dclstn** [comment] 2024-09-29 11:57
Duplicate of #7051

**Closed by dclstn** 2024-09-29 11:57 UTC
Labels: bug, duplicate
