### ISSUE TITLE
Error on claiming channel points

### ISSUE THREAD

**Issue by jlntrt** [night/betterttv#4457] opened 2021-04-13 17:25 UTC
Hey there,

since a few days I notice problems with claiming channel points. The button for the channel points is getting red and the tool tip shows "Error claiming bonus":
![image](https://user-images.githubusercontent.com/1820777/114594563-ae170c80-9c8d-11eb-9b66-cce396a2155c.png)

I guess the extension to to eager claiming the bonus points. Is it possible to add a delay? 

Anyone else getting this error?

**Comment by Nareese** [comment] 2021-04-13 20:15
I have 2 questions:

1/ Does this happen every time, or only some times?  Have you tested on multiple channels, or is it channel specific?
2/ Turn off auto-claim.  Claim the chest manually.  Does it work?

I am unable to reproduce anything like this.  2 channels that I've been watching for hours today are both auto-claiming correctly every time.  It's extremely unlikely that this has anything to do with BTTV, and is more likely a problem with Twitch itself, or with your account on Twitch, but I'll be interested to hear your answers to the above questions.

**Comment by jlntrt** [comment] 2021-04-13 20:27
Hi @Nareese 

thanks for your response. 
1/ I see this happening just some times. The button getting red and in about 2 minutes it's working again for the next 30 minutes I guess.
2/ Yes, the manual claim is always working fine.

There is a similar feature for [Alternate Player for Twitch.tv](https://addons.mozilla.org/en-US/firefox/addon/twitch_5/) which seems to have a short delay on claiming channel points when the animated button appears and there where never a problem. That's why I proposed to add a delay too. But when it is not reproducible for anyone it seems the reason lies elsewhere as you mentioned.

Should we close the issue here?

**Comment by Nareese** [comment] 2021-04-13 20:50
Ya, regardless of the cause (and I do think it's unlikely it's timing related, but it is possible, I suppose), it will be impossible for us to diagnose if it's not reproducible.  You can close the issue if you wish, or leave it open if you'd like to see if night has any additional comments.

**Closed** 2021-04-14 13:53 UTC
