### ISSUE TITLE
Feature: Chat Scroll

### ISSUE THREAD

**Issue by GormanE** [night/BetterTTV#1457] opened 2016-08-18 11:01 UTC
Adding an option to stop the chat scrolling when the mouse moves over the chat text, to allow easier copying of text and clicking of links. Then, when the user moves their mouse back off the chat, it resumes the movement of chat and where it would have been had the chat not been paused.

Should be a feature which is toggled and set as false by default, otherwise people would be confused about what was happening.

**Comment by night** [comment] 2016-08-20 03:55
Duplicate of #1299

**Closed by night** 2016-08-20 03:55 UTC
Labels: duplicate
