### ISSUE TITLE
Names Overlapping colon

### ISSUE THREAD

**Issue by Vafarien** [night/BetterTTV#2451] opened 2017-05-14 14:56 UTC
![text errors](https://cloud.githubusercontent.com/assets/2349950/26034988/4d08bea0-387a-11e7-9ebd-28ef8857bf2e.PNG)

Browser: Chrome (Version 58.0.3029.110 (64-bit))
OS: Windows 7 64-bit Home Premium
Version: (BetterTTV v7.0.3)
[BetterTTV error Doc.txt](https://github.com/night/BetterTTV/files/999484/BetterTTV.error.Doc.txt)
Console Errors attached.

**Comment by MitchellSlavik** [comment] 2017-05-14 15:22
I am having the same issue and from what I have been playing around with the css removing this style fixes the issue:
.chat-line .colon, .conversation-chat-line .colon {
    margin-left: -3px;
}

**Comment by night** [comment] 2017-05-14 20:18
duplicate of #2442

**Closed by night** 2017-05-14 20:18 UTC
Labels: duplicate
