### ISSUE TITLE
Hide Recommended Friends/Channels not working

### ISSUE THREAD

**Issue by RobertW1892** [night/betterttv#4368] opened 2021-02-20 08:02 UTC
Two hide options are on, but I can still see those channels being displayed on the side bar.
I'm using Google Chrome.

I've attached a sample screenshot with sections of it highlighted. Please fix this. I'm not interested in seeing recommended channels from Twitch. If I'm looking for new people to watch, I'll find them myself.

[https://imgur.com/8g9mdOE](url)

**Comment by Nareese** [comment] 2021-02-20 12:17
duplicate of #4183 

This issue applies only when the left bar is collapsed.  Unfortunately, in that view, there is no trivial way to safely and reliably identify that section to hide it, so this is hard to fix.

**Closed** 2021-03-15 01:54 UTC
Labels: duplicate
