### ISSUE TITLE
Disable Host Mode not working

### ISSUE THREAD

**Issue by domaspiragas** [night/BetterTTV#2669] opened 2017-09-07 05:56 UTC
I'm on chrome, and I've really enjoyed the disable host mode for when I go to sleep with a stream on. It used to work perfectly, when the streamer I left on overnight was finished, my computer went to sleep since host mode was disabled. Recently it's stopped working. It's definitely enabled, but hosted channels begin to play when a stream has ended. I've tried clearing cache.

Not sure if it's just on my end. Not sure what could cause it to stop working. I noticed it stop working a few weeks ago.

**Comment by Raccok** [comment] 2017-09-07 07:09
Duplicate of #2601

**Closed** 2017-09-09 18:18 UTC
Labels: duplicate
