### ISSUE TITLE
Reruns

### ISSUE THREAD

**Issue by Nyztan0** [night/betterttv#5112] opened 2022-01-01 20:49 UTC
Hey!

I made an account on Github just to sumbit this idea as a option on BTTV on Twitch.
Please make an option that enables Reruns not being able to be showed on your followers list,
Thanks!

/NyZtan0

**Comment by Nareese** [comment] 2022-01-02 13:56
duplicate of #2496

**Closed** 2022-01-08 17:23 UTC
Labels: duplicate
