### ISSUE TITLE
Why do I still see "Recommended Channels" when I have the option turned off?

### ISSUE THREAD

**Issue by Boolyman** [night/betterttv#4938] opened 2021-10-17 00:40 UTC
Yes, this it a duplicate to the many other people that have asked for this to be fixed.  Why have the option if you won't actually make it work?

**Comment by apbrimah** [comment] 2021-10-30 11:57
I can attest that this feature does not work. Auto-Expand Channels also does not work as intended.

**Comment by night** [comment] 2021-11-27 19:46
duplicate of #4183

**Closed by night** 2021-11-27 19:46 UTC
Labels: duplicate
