### ISSUE TITLE
Option To Filter A Certain Amount Of Text Lines On Twitch

### ISSUE THREAD

**Issue by STEALTH1X** [night/betterttv#4322] opened 2021-01-15 18:50 UTC
I know it's a Twitch Culture thing but I don't care for the dumb juvenile spam and copy/paste nonsense while watching esport tournaments.  Most of them go well over three lines. It'd be nice if there was an option to filter out messages that went over so many lines (e.g hide all comments that go over three lines).

Not sure if this is possible but it'd instantly eradicate seeing all the dumb 5+ line spam comments people leave and then worse copy/paste all day long during the tournaments.

**Comment by night** [comment] 2021-03-15 00:05
duplicate of #1922

**Closed by night** 2021-03-15 00:05 UTC
Labels: duplicate
