### ISSUE TITLE
Remove modifiable list of games from browse game page

### ISSUE THREAD

**Issue by christopherlogel** [night/BetterTTV#1205] opened 2016-05-24 15:36 UTC
####  Feature Request:

I like browsing the game directory https://www.twitch.tv/directory

Right now there are so many games that I see constantly in which I have no interest and never will.  It would be nice to have a mode where I could hide games that I don't want to see anymore from the directory.

**Comment by night** [comment] 2016-05-24 15:59
Duplicate of #70

**Closed by night** 2016-05-24 15:59 UTC
Labels: duplicate
