### ISSUE TITLE
Anonymous Chat Bugged 

### ISSUE THREAD

**Issue by JamMonsters** [night/BetterTTV#2437] opened 2017-05-11 03:21 UTC
Anon Chat is super bugged for me, I've tried clear all my history deleting and reinstalling bttv and restarting my computer. but nothing seems to help and i still show up in  chat rooms, any suggestions?

**Comment by Nareese** [comment] 2017-05-11 07:47
duplicate of #2402 

It is a known issue and is in the queue to be investigated and worked on.  As mentioned in that issue, you can work around it by turning anon mode off and on again while in the chat you wish to be anonymous in.  Note that because of caching, it may take up to 2 minutes before you disappear off the user list.

**Closed** 2017-05-13 19:56 UTC
Labels: duplicate
