### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Sleekness** [night/BetterTTV#194] opened 2015-01-22 16:52 UTC
When you go to someones profile and then click on either highlights or vods, the info section panels is pushed to the left side and dont have boxes or corners around them. (http://i.imgur.com/40sMS55.png) 
The info section panels should look like in the channel page, centered and with corners around them (http://i.imgur.com/0drAnsG.png). And BTW, I noticed that sometimes when you watch somebody's vod or highlight the follower count is showing '0'. 

In profile page the right sidebar isn't closing correctly. It just removes sidebar itself but doesnt shrink (http://i.imgur.com/tZHdfxs.png). 

twitch.tv/turbo the header's words color is pink (http://i.imgur.com/tSWV7CA.png) It should be black like on homepage. And the button 'Complete Purchase' is pink even though I have Blue Buttons turned on

In settings page left sidebar 'Play Now' should be removed. It's the only place where it appears (http://i.imgur.com/oVbPyHX.png)

When you press emoticon button, I think that brighter box where it says 'Subscribe to unlock emoticons' should be extended to fill whole emoticon box or removed. It would look nicer (http://imgur.com/5030CO6)

And frankerfacez box has useless corners, I think they should be removed? (http://imgur.com/ltY7nNL)

'Dismiss' word should be white instead of pink (http://imgur.com/3WR13Eb)

**Comment by night** [comment] 2015-01-22 18:49
> And BTW, I noticed that sometimes when you watch somebody's vod or highlight the follower count is showing '0'.

Not our problem, so we cannot fix it.

> In profile page the right sidebar isn't closing correctly. It just removes sidebar itself but doesnt shrink (http://i.imgur.com/tZHdfxs.png).

Cannot reproduce.

> twitch.tv/turbo the header's words color is pink (http://i.imgur.com/tSWV7CA.png) It should be black like on homepage. And the button 'Complete Purchase' is pink even though I have Blue Buttons turned on

Won't fix. We do not modify payment pages.

> In settings page left sidebar 'Play Now' should be removed. It's the only place where it appears (http://i.imgur.com/oVbPyHX.png)

Won't fix. Turn off the "Featured Channels" option in the BetterTTV settings.

> When you press emoticon button, I think that brighter box where it says 'Subscribe to unlock emoticons' should be extended to fill whole emoticon box or removed. It would look nicer (http://imgur.com/5030CO6)

Won't fix. "Nicer" is subjective.

> And frankerfacez box has useless corners, I think they should be removed? (http://imgur.com/ltY7nNL)

Won't fix. You can request FrankerFaceZ to fix this, but it's not our concern.

Everything else can be fixed.

**Comment by Sleekness** [comment] 2015-01-22 20:25
What I meant about 'Play Now'..- I actually have turned off 'Featured Channels' which should mean that by default 'clutter' is removed from sidebar and 'Play Now' should not be in there, which is not there except at settings page. 

And about other issues - that's totally cool if you won't fix them, I think I'm just being too pedantic, sorry. Hope im not too rude ;_;

**Comment by night** [comment] 2015-01-23 19:35
> What I meant about 'Play Now'..- I actually have turned off 'Featured Channels' which should mean that by default 'clutter' is removed from sidebar and 'Play Now' should not be in there, which is not there except at settings page.

It appears this is hidden for Turbo users, which is why I couldn't reproduce it.

> Hope im not too rude ;_;

You're not, so don't worry about it.

I've started work to resolve these bugs.

**Comment by night** [comment] 2015-01-23 21:15
> When you go to someones profile and then click on either highlights or vods, the info section panels is pushed to the left side and dont have boxes or corners around them. (http://i.imgur.com/40sMS55.png) 
The info section panels should look like in the channel page, centered and with corners around them (http://i.imgur.com/0drAnsG.png).

This turned out to be a Twitch bug. Going to a VoD from the profile causes this to happen, but going to it directly does not.

**Comment by Sleekness** [comment] 2015-01-23 21:26
Thankss. I'm wondering if there is bug submit form or something so that you can maybe report it this bug and '0' follower count?

**Closed** 2015-01-23 21:29 UTC
Labels: bug

**Comment by Sleekness** [comment] 2015-01-23 21:32
And one more thing, I don't know if it just for me but subscribers only and slow mode notifications on channel join doesn't show up. I have /linehistory on

**Comment by night** [comment] 2015-01-23 21:41
>And one more thing, I don't know if it just for me but subscribers only and slow mode notifications on whichever channel join doesn't show up. I have /linehistory on

Line history is on by default, and I cannot reproduce this issue
