### ISSUE TITLE
BTTV issue

### ISSUE THREAD

**Issue by RightfulSin** [night/BetterTTV#2470] opened 2017-05-21 06:58 UTC
Hello, I have recently been experiencing some odd bug or something. It started Thursday night PST. I have it installed from the chrome store and I have tried what I can think of to fix it. The probelm is that I am logged into twitch using BBTV and I cannot change any of the BTTV settings, I cannot even see the set ones that are on. I log in, go to the upper right under the user name, get the drop down menu, select BTTV settings, and the page is basically empty. All that is there is a message saying "Here you can manage the various BetterTTV options. Click On or OFF to toggle settings." but nothing else. I have uninstalled and reinstalled it several times, closed browser, and even restart computer, all with no change. I like the extension a lot, and I mainly watch twitch in place of tv nowadays, but I cannot fully utilize the chat function or anything because I cannot access the settings. I would thank you for any assistance given, and once again thank you for making this extension for me and several others who use twitch to use.

**Comment by night** [comment] 2017-05-21 19:58
duplicate of #2464

**Closed by night** 2017-05-21 19:58 UTC
Labels: duplicate
