### ISSUE TITLE
Emotes not showing in chat

### ISSUE THREAD

**Issue by KrypticStar0** [night/BetterTTV#3556] opened 2019-08-27 02:27 UTC
I have refreshed tons of time, Re installed it. and everything I think I can do and i don't know what to do.
also I am on - Mozilla Firefox

**Comment by mihazt** [comment] 2019-08-29 15:50
I have also came across this problem and do not know how to fix it

**Comment by night** [comment] 2019-09-09 02:00
Unfortunately without reproducible steps I will have to close this issue since I cannot reproduce any issues with emotes loading.

**Closed by night** 2019-09-09 02:00 UTC
Labels: invalid
