### ISSUE TITLE
disable host mode and homepage autoplay options are not working

### ISSUE THREAD

**Issue by Harlecorn** [night/betterttv#3966] opened 2020-06-14 21:40 UTC
I know twitch keeps changing their ui,  but I cant find mention of the host issue being mentioned anywhere recently. The option to Disable Host mode isn't being honoured, however and as someone who frequently will watch streamers before going to bed, it's jarring to have the stream switch to a host and be awoken by the talking/gameplay. Really hope this gets fixed soon cuz it's very inconvenient that twitch has no option on it's own.

**Comment by night** [comment] 2020-06-15 09:05
duplicate of #3933 and #3954

**Closed by night** 2020-06-15 09:05 UTC
Labels: duplicate
