### ISSUE TITLE
Twitch chat settings are either delayed or open instantly based on number of chatters 

### ISSUE THREAD

**Issue by TheLucky007** [night/betterttv#6861] opened 2024-06-06 03:42 UTC
### Describe the bug

Whenever I'm trying to open up chat settings on a high volume active chats, I'm unable to interact with the page for about 10 seconds

### Steps to reproduce

1. Go to any live broadcast with at least 10k viewers or a high volume active chats
2. Click on the chat settings cogwheel, and page becomes uninteractive for about 10 seconds
3. May get chrome "page is unresponsive" dropdown thing

### Expected behavior

Settings to be instant or very slight delay due to lag (~1s)

### Screenshots

I would, but the gifs add in some addt'l delay defeating the purpose for this bug

### Device information

Windows 10 Pro 19045.4412
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36

### BetterTTV Version

7.6.3

### Additional information

I made sure that this was only a betterttv issue and not a general twitch issue, Started incognito mode with only betterttv and ublock origin and the response is instant as if with low to no active chat, slowly added all my active extensions for incognito and they're about the same instant response. I even cleared all cache and the response is still 10 seconds on normal/instant in incognito mode

### Version Check

- [X] I have checked that I'm using the newest version of BetterTTV available.

**Comment by night** [comment] 2024-06-10 16:14
I am not able to reproduce 10 second delays, but I do see from performance metrics that Twitch's on scroll handler seems to cause usage in fast chats. BetterTTV doesn't seem to be bottlenecking from what I can gather.

From your write-up alone it isn't clear this is a BetterTTV issue.

> Started incognito mode with only betterttv and ublock origin and the response is instant

You state that you used BetterTTV in incognito mode and it appeared instant.

> I even cleared all cache and the response is still 10 seconds on normal/instant in incognito mode

You then state conflicting information that the response is 10 seconds in incognito mode.

Please retest your findings by disabling BetterTTV and testing both with and without incognito mode. If your problem persists, it may not be BetterTTV.

It's worth pointing out also that it could be a Twitch extension built into the Twitch video player or about section on a specific stream just on your machine.

**Comment by night** [comment] 2024-06-11 15:28
Closing this for now, but if you're still having issues let us know.

**Closed by night** 2024-06-11 15:28 UTC
Labels: bug
