### ISSUE TITLE
HOST button isn't working

### ISSUE THREAD

**Issue by RoseiiNaytool** [night/betterttv#4541] opened 2021-05-19 13:12 UTC
The host button is no longer coming up, I have already tried readding better ttv and it's not working still. Suggestions on getting it working?

**Comment by PXAbstraction** [comment] 2021-05-19 13:32
Same issue. The host button just seems to have disappeared. I assume Twitch changed something that broke it. :(

**Comment by VENOMISS** [comment] 2021-05-19 14:15
yeah i am trying to host my friend and it wouldn't let me host their channel by the button with betterttv.

**Comment by bennismaximus** [comment] 2021-05-19 14:40
Still not working after fix.

**Comment by Nareese** [comment] 2021-05-19 18:19
There has not been a new version released with the fix yet.  night probably wants to get fixes for all of the issues caused by Twitch's update into one big release.  He has indicated that he hopes to have that out by the end of the week.

**Comment by night** [comment] 2021-05-20 00:33
duplicate of #4537

**Closed by night** 2021-05-20 00:33 UTC
Labels: duplicate
