### ISSUE TITLE
Better Viewer List Auto Scroll

### ISSUE THREAD

**Issue by xblade13** [night/BetterTTV#2445] opened 2017-05-13 07:56 UTC
When I scroll down the viewer list, it will automatically scroll itself to the bottom or top without me doing anything

What it looks like:
https://gyazo.com/37f79ddf99e028681d90b858b36b4244

**Comment by Nareese** [comment] 2017-05-13 15:02
duplicate of #2269

**Closed** 2017-05-13 19:47 UTC
Labels: duplicate
