### ISSUE TITLE
Issues with dark theme and chat

### ISSUE THREAD

**Issue by LandriAker** [night/BetterTTV#3227] opened 2018-08-23 01:50 UTC
Not sure when exactly it started but I took notice of it today. I use opera with BTTV but the issue seems to also effect my chrome. 
Both have dark theme on, it seems when the color is suppose to be light it makes the whole chat section of someone's message completely white.
![ea4f695cea639e43428141164ab3ab1f](https://user-images.githubusercontent.com/42628388/44500103-ed177000-a654-11e8-84fb-1a9815090ad4.png)

If I turn off dark theme the problem goes away, of course.

**Comment by Nareese** [comment] 2018-08-23 02:05
duplicate of #3216

**Closed** 2018-08-23 03:01 UTC
Labels: duplicate
