### ISSUE TITLE
Hide offline followed channels and hide offline recommended channels not working 

### ISSUE THREAD

**Issue by uxsparkyxu** [night/betterttv#4100] opened 2020-08-19 23:58 UTC
"Hide offline followed channels" and "hide offline recommended channels" not working on firefox extension. same with "disable host mode" none of these have worked since the last update, maybe the last two updates, i'm not sure but it used to all work just fine and now these features don't work

**Comment by Nareese** [comment] 2020-08-20 00:15
duplicate of #3868 #4023 and #3933

**Comment by Jiansarys** [comment] 2020-08-21 02:23
For some reason my settings were changed, and now when I enable them, the Hide Recommended Channels doesn't work. I've tried reinstalling, and my browser is up to date.

**Closed** 2020-08-30 10:27 UTC
Labels: duplicate
