### ISSUE TITLE
Chat Notification Sound

### ISSUE THREAD

**Issue by BreezyBrain12** [night/BetterTTV#1039] opened 2016-03-23 23:23 UTC
Though I may be the only one suggesting this, but hey, same reason for the BetterTTV GIF Emotes. I'm not a popular streamer, maybe 10 viewers when I play Division, 30 when I play other games, but I realize I'm 5 minutes late to almost every chat message. Having the notification would be spectacular for any streamer like me. Also, a great idea would be to put in a cooldown function for it so that if the streamer is on the thin line between too many chat messages but still misses them and doesn't want o enable it because of the constant ping, they can set it to where the ping only goes off every , 5, 10, 20, 30, 45, or 60 seconds or not.

**Comment by night** [comment] 2016-03-26 05:58
Duplicate of #808

**Closed by night** 2016-03-26 05:58 UTC
Labels: duplicate
