### ISSUE TITLE
Turn off the Re-sub highlight?

### ISSUE THREAD

**Issue by totofeo** [night/BetterTTV#1337] opened 2016-07-01 21:38 UTC
Sorry if this is do-able somehow but i haven't figured it out, wasn't like this before, but these re-sub highlights are pretty distracting and would like an option to turn them off. Thanks for your work btw.

**Comment by whywhy87** [comment] 2016-07-01 23:00
1337!

**Comment by Slikrick** [comment] 2016-07-02 00:09
Duplicate of #1335

**Closed** 2016-07-02 09:15 UTC
Labels: duplicate
