### ISSUE TITLE
twitch emotes not showing in rechat

### ISSUE THREAD

**Issue by src7G** [night/BetterTTV#1434] opened 2016-08-05 19:37 UTC
BTTV emotes showing in chat replay (VODS) twitch emotes not(live stream working only vod chat doesnt).
See pic: http://imgur.com/a/hYjLW

Hover the twitch emotes point e.g. to https://static-cdn.jtvnw.net/emoticons/v1/null/1.0

**Comment by voloshink** [comment] 2016-08-05 20:16
can't reproduce the bug, but i do see some errors on the page, will look into it once im home

**Comment by voloshink** [comment] 2016-08-10 03:51
should be fixed now

**Closed by voloshink** 2016-08-10 03:51 UTC
