### ISSUE TITLE
whispers 

### ISSUE THREAD

**Issue by gamernation89** [night/BetterTTV#2512] opened 2017-06-10 14:46 UTC
i realized that a couple days ago the whispers got a little messed up with the text coloring in dark mode it will all be dark 
![screenshot 122](https://user-images.githubusercontent.com/19208617/27003730-08c5e230-4dca-11e7-9675-4e68b472ae76.png)

**Comment by Nareese** [comment] 2017-06-10 15:27
duplicate of #2508

**Closed** 2017-06-10 22:34 UTC
Labels: duplicate
