### ISSUE TITLE
Feature request: complete blacklist streams and make it invisible

### ISSUE THREAD

**Issue by Daisenki** [night/BetterTTV#3279] opened 2018-09-25 23:03 UTC
Here is currently no way at Twitch to block or hide any streams, there are tools for YouTube to hide channels complete and make it invisible for you. Maybe it would be a lot of work to get such a feature, but I think many users and especially me would find that awesome to have.

I can block a user/streamer to hide the messages and block the conversations, but I already see the live streams from that streamer online. I see people on my follow list that host this channel that I don't want to see anymore. Why can a Streamer ban a viewer and now I need to see that stream every time going on IRL oder every other category an look at that face again and again. It triggers at some point.

It would be awesome to complete hide a channel with a extra blacklist like the language filters on Twitch.

**Comment by night** [comment] 2018-09-29 20:48
duplicate of #70

**Closed by night** 2018-09-29 20:48 UTC
Labels: duplicate
