### ISSUE TITLE
Font and Font Size Not Working

### ISSUE THREAD

**Issue by nolyd3** [night/betterttv#3859] opened 2020-05-12 13:31 UTC
Attempting to change the font or font size within the chat menu is not working atm.

**Comment by Nareese** [comment] 2020-05-12 13:32
duplicate of #3855

**Comment by AlbrechtProud** [comment] 2020-05-12 14:10
I have the same issue. MacOS Catalina and Firefox

**Comment by mseals1** [comment] 2020-05-12 20:41
I have the same issue, using Chrome.

**Comment by dragonpixies** [comment] 2020-05-12 21:25
Same issue on Chrome and Firefox on Win8. Uninstalling/reinstalling didn't work :(

**Closed** 2020-05-13 07:08 UTC
Labels: duplicate
