### ISSUE TITLE
Dis/Enable auto play for User/Streamer-Channel video player

### ISSUE THREAD

**Issue by zedd-0** [night/betterttv#5564] opened 2022-08-06 11:06 UTC
hallo,
it would be nice, if i could disable the auto-play feature on the streamer-channels,
if they were offline & do no hosting.

exp.:
https://www.twitch.tv/deke64

maybe a "Disable all auto play features", as a gereral-switch sounds nice, too.

thanks.

**Comment by night** [comment] 2022-10-01 02:37
duplicate of #4405

**Closed by night** 2022-10-01 02:37 UTC
Labels: duplicate
