### ISSUE TITLE
[Request] Get streamer's follower count back on main page as option?

### ISSUE THREAD

**Issue by GARBAGEPLAY** [night/BetterTTV#3626] opened 2019-10-25 21:36 UTC
Shouldn't be too difficult. It's been moved 2 clicks deep now and I would like to see it next to the streamer's name. 

I could probably write a chrome extension to do this, I don't know how to add it to this project though.

**Comment by Nareese** [comment] 2019-10-25 22:57
duplicate of #3602

**Closed** 2019-10-28 08:32 UTC
Labels: duplicate
