### ISSUE TITLE
fontsize changing w/ BTT

### ISSUE THREAD

**Issue by Schippi** [night/BetterTTV#1028] opened 2016-03-20 10:35 UTC
immidiately when i installed BTT i noticed the chatfont size was increased. i would like an option to keep it as it is
![image](https://cloud.githubusercontent.com/assets/924899/13903943/b5ad47fe-ee8f-11e5-8f5f-e3802d048aca.png) (top is with BTT)

**Comment by night** [comment] 2016-03-22 04:45
Duplicate of #57

**Closed by night** 2016-03-22 04:45 UTC
Labels: duplicate
