### ISSUE TITLE
mod purge/timeout commands missing

### ISSUE THREAD

**Issue by missbeazus** [night/BetterTTV#2858] opened 2017-12-11 14:19 UTC
Hi there. I'm a mod for a couple of channels and I've had an issue with the left click pop-up menu only having either timeout or ban instead of the purge, 1s, 60s, 10m, etc options it used to have.

I know things have been weird since Twitch started making changes to their site, but I originally managed to fix it by selecting the "Legacy site" option. Now that I no longer have that "Legacy site" option to check off on my drop down menu, is there a way to get the multiple purge/timeout options back? Or is it just me having this issue? 

I tried disabling and then re-enabling bttv, I tried removing it and reinstalling it, I even switched browsers to see if it was a Firefox issue. Had the same problem on Chrome.

Thanks!

**Comment by DayBr3ak** [comment] 2017-12-11 17:29
#2859 it's in dev

**Comment by DayBr3ak** [comment] 2017-12-12 01:20
And you also can right click a name. It opens a widget to choose the timeout/ban

**Comment by missbeazus** [comment] 2017-12-12 11:12
I tried that and did not get the widget. Thanks, though.

**Comment by night** [comment] 2017-12-18 03:38
duplicate of #2605

**Closed by night** 2017-12-18 03:38 UTC
Labels: duplicate
