### ISSUE TITLE
Fullscreen issue

### ISSUE THREAD

**Issue by faatipuskevit** [night/BetterTTV#1825] opened 2016-12-03 19:21 UTC
While the bttv is enabled i cant watch streams at fullscreen. It doesnt go bigger than as I show in the screenshot. If you need any other information i can give it. Just tell me how to do it. Have a nice day.
![screenshot taken with print screen](https://cloud.githubusercontent.com/assets/7822906/20861669/b7ca2baa-b9a6-11e6-9126-91e872a567bc.png)

**Comment by EhsanKia** [comment] 2016-12-03 20:23
Should be fixed now.

**Closed by EhsanKia** 2016-12-03 20:23 UTC

**Comment by night** [comment] 2016-12-03 23:28
duplicate of #1810

**Comment by faatipuskevit** [comment] 2016-12-04 16:05
Thanks!
