### ISSUE TITLE
Moderation icons

### ISSUE THREAD

**Issue by LoveTristana** [night/BetterTTV#2965] opened 2018-02-09 23:23 UTC
![report](https://user-images.githubusercontent.com/36316006/36054781-7eecca8e-0df8-11e8-9d64-0aac94876756.PNG)
they seems to disapear for me and tryed to uninstall and instal again and still not working

**Comment by Zagibok44** [comment] 2018-02-10 02:23
нет

**Comment by Khurune** [comment] 2018-02-10 03:00
This maybe down to twitch removing all legacy aspects of the site now. Only leaving us with the Legacy popout chat option which all chat features 'should' still work from. (All legacy chat extensions I've tried today are also broken and won't revert the chat back to legacy.) Hopefully BTTV will have this fully working soon, as I came over here hoping someone had found a fix, for now just use the Legacy popout.

**Comment by night** [comment] 2018-02-10 04:13
duplicate of #2963

**Closed by night** 2018-02-10 04:13 UTC
Labels: duplicate
