### ISSUE TITLE
Feature Request: Disable Twitch video downscale

### ISSUE THREAD

**Issue by Feky** [night/betterttv#4264] opened 2020-12-06 07:08 UTC
So far I love how Better TV has all cool stuff for twitch for a better experience and I thank you devs for this great extension. I wish if you could implant this feature in BetterTV. To disable Twitch downscaling video when you switch tabs. So far I'm using a script for Tampermonkey but implantation in better TV would be better to have all in one spot.

**Comment by Nareese** [comment] 2020-12-06 12:28
duplicate of #3513

**Closed** 2020-12-18 02:38 UTC
Labels: duplicate
