### ISSUE TITLE
Emote Menu not showing

### ISSUE THREAD

**Issue by randomcitizen49** [night/BetterTTV#1109] opened 2016-05-04 06:14 UTC
![image](https://cloud.githubusercontent.com/assets/19181882/15006288/b9cfa03e-1194-11e6-910d-add3a1c67af5.png)
![image](https://cloud.githubusercontent.com/assets/19181882/15006293/d036c8c0-1194-11e6-9c4d-d8d9efc3a132.png)
![image](https://cloud.githubusercontent.com/assets/19181882/15006306/053e19e2-1195-11e6-9c1a-990d156c96b1.png)
It's as the title says. Images show the error codes and proves that I have the setting on. I've tried everything from re downloading BTTV to deleting my cache and cookies in chrome. Hopefully this can help me resolve it. It is happening on all channels not just this one channel as well.

**Comment by night** [comment] 2016-05-04 06:23
Duplicate of #1108

**Closed by night** 2016-05-04 06:23 UTC
Labels: duplicate
