### ISSUE TITLE
Auto expand followed channels on sidebar not working

### ISSUE THREAD

**Issue by SonicTHI** [night/BetterTTV#3301] opened 2018-10-31 17:19 UTC
If this is the "Auto expand followed channels list" option it doesnt work for me.
Left sidebar only shows all online + 1 offline channel.
Latest Chromium with only bttv, ublock origin, https everywhere and vanilla cookie manager.

Settings:
{"bttv_autoExpandChannels":true,"bttv_clickTwitchEmotes":true,"bttv_darkenedMode":true,"bttv_disableFPVideo":true,"bttv_disableVodRecommendationAutoplay":true,"bttv_hideBits":true,"bttv_hideFriends":true,"bttv_hideNewViewerGreeting":true,"bttv_hideOfflineFollowedChannels":false,"bttv_hidePlayerExtensions":true,"bttv_hidePrimePromotion":true,"bttv_hideRecommendedFriends":true,"bttv_hideSubscriptionNotices":true,"bttv_importedV6":true,"bttv_showDeletedMessages":true,"bttv_splitChat":false}

**Comment by night** [comment] 2018-11-19 02:58
duplicate of #3277

**Closed by night** 2018-11-19 02:58 UTC
Labels: duplicate
