### ISSUE TITLE
[feature request] Clicking on hosted channel leads you to that channel and not the host

### ISSUE THREAD

**Issue by Kwantuum** [night/BetterTTV#2227] opened 2017-04-04 11:17 UTC
Would it be possible to make clicking on a "hosted channel" in your followings lead you directly to that channel? I think it's pretty clear when you're clicking on a hosted channel you want to watch them and not land into a dead chat. Thank you very much for your consideration :)

**Comment by night** [comment] 2017-04-10 22:40
duplicate of #206

**Closed by night** 2017-04-10 22:40 UTC
Labels: duplicate
