### ISSUE TITLE
Betterttv Settings not showing.

### ISSUE THREAD

**Issue by BigChief190** [night/BetterTTV#2467] opened 2017-05-19 17:30 UTC
As of last night the settings won't show up for betterttv. There was an issue with HTML5 player that i didn't know and cleared all cookies to fix it. I reinstalled betterttv to try fixing it but no luck. I'm using windows vista. it all worked until last night.

**Comment by night** [comment] 2017-05-19 18:08
duplicate of #2464

**Closed by night** 2017-05-19 18:08 UTC
Labels: duplicate
