### ISSUE TITLE
Some things not working

### ISSUE THREAD

**Issue by derpyderpaderp** [night/BetterTTV#3235] opened 2018-08-28 04:56 UTC
So far host channel isn't working, twitch's emotes are not included in tab completion. I have cleared cache and reset chrome, not fixed. reinstalled betterttv and still same exact issues. Happening in the latest version of chrome. I am unaware if this is happening in firefox.

**Comment by SaiyanOfDarkness** [comment] 2018-08-28 06:05
I'm pretty sure this is related to a recent update they made.  I had to change my custom css style in the past few days.

**Comment by zewm** [comment] 2018-08-29 04:52
Getting the same problem on my end. No custom emotes and no tab completion.

**Comment by night** [comment] 2018-08-29 09:41
duplicate of #3233

**Closed by night** 2018-08-29 09:41 UTC
Labels: duplicate
