### ISSUE TITLE
Disable Host Mode not working

### ISSUE THREAD

**Issue by Grayanotoxin** [night/BetterTTV#2637] opened 2017-08-21 03:00 UTC
I am using the latest version of BTTV on Chrome, but cannot get the disable host mode feature to work. It is switched to "on" but has no effect at all on hosts. I've tried toggling it on and off to no effect. I've attached an image for clarity. 
<img width="1207" alt="screen shot 2017-08-20 at 9 58 48 pm" src="https://user-images.githubusercontent.com/31197338/29502066-ea3d50da-85f2-11e7-82e0-f0fb61c85f04.png">

**Comment by Nareese** [comment] 2017-08-21 17:13
duplicate of #2601

**Closed** 2017-08-23 04:28 UTC
Labels: duplicate
