### ISSUE TITLE
Feature Request: Show chat even if a user is banned

### ISSUE THREAD

**Issue by regmibijay** [night/betterttv#5269] opened 2022-03-19 21:57 UTC
Basically the idea is to be able to read chat even if you are not logged in or have been banned. I have noticed the missing chat or "you have been banned so you can not see all of the chat anymore" kind of ruins the whole stream experience.

**Comment by dclstn** [comment] 2022-03-19 22:18
dupe of #3803

**Closed** 2022-03-19 22:19 UTC
Labels: duplicate

**Comment by regmibijay** [comment] 2022-03-19 23:20
that issue is  locked and the solution mentioned there to use Anon Chat does not work (tested with v7.4.22)
