### ISSUE TITLE
[Feature Request] Opt-In Channel Raids

### ISSUE THREAD

**Issue by Rms2000** [night/BetterTTV#3019] opened 2018-03-04 20:51 UTC
Twitch has recently revamped their channel raid system, including a feature that causes viewers to be automatically pulled along with raids if they do not press a button to opt out. This disrupts the viewing experience of many viewers and requests have already been made by users for Twitch to implement a setting for disabling Opt-Out Raids, to which Twitch has not responded. But when Twitch tv is insufficient, there is BTTV. I would like to request that a feature be implemented to optionally either block the Opt-Out Raid system's redirect attempt, or modify the system to be Opt-In, or remove the system entirely, based on settings.

**Comment by night** [comment] 2018-03-05 06:12
duplicate of #2936

**Closed by night** 2018-03-05 06:12 UTC
Labels: duplicate
