### ISSUE TITLE
BTTV randomly stops the stream

### ISSUE THREAD

**Issue by noahfrag** [night/BetterTTV#3592] opened 2019-09-24 14:11 UTC
With BTTV enabled streams just randomly stops and I have to reload the page again.
I tried to reinstall BTTV, clear my cookies and disable all BTTV features. Nothing worked. Couldn't find any solutions. I'm on Windows 10 & Chrome.

**Comment by koitsu** [comment] 2019-09-28 08:51
For what it's worth, I've been having this exact same problem. Disabling BTTV solved it. Windows 7 SP1 x64 + Chrome 77.

This is anecdotal, but what I suspect is happening is that BTTV is doing some asynchronous back-end fetch which blocks/stalls the video playback thread.  There are a couple places where this is doable already -- example: load a stream + pick Set Font in BTTV, then waiting several seconds after the dialog box pops up: the stream will completely lock and will not resume even after closing the dialog (the entire tab must be reloaded).

**Comment by night** [comment] 2019-09-28 20:11
> This is anecdotal, but what I suspect is happening is that BTTV is doing some asynchronous back-end fetch which blocks/stalls the video playback thread.

We don't do "backend fetches." BetterTTV is built on browser mutation observers, which does come at some cost to CPU usage. But generally there is no action that occurs which can cause your main thread to lockup long enough to freeze your player. Unfortunately since I cannot reproduce this issue it's likely not something that can be fixed. You can try running the CPU profiler in the developer console and posting it here so I can inspect it, but otherwise it would be like shooting in the dark to try and figure out why it freezes for you.

> There are a couple places where this is doable already -- example: load a stream + pick Set Font in BTTV, then waiting several seconds after the dialog box pops up: the stream will completely lock and will not resume even after closing the dialog (the entire tab must be reloaded).

When you open native dialog boxes, the thread becomes blocked waiting on input from the dialog. That is the behavior of native dialogs and cannot be fixed without us building our own dialog.

**Comment by night** [comment] 2019-10-07 06:40
closing this since there isn't repro steps.

**Closed by night** 2019-10-07 06:40 UTC
Labels: cantfix
