### ISSUE TITLE
Feature request: Automatically decline to join a raid.

### ISSUE THREAD

**Issue by Anoneeemous** [night/betterttv#5371] opened 2022-05-12 02:28 UTC
Please can you add a feature that prevents me from be added to a raid.
There are a number of issues I have with this, but I'll just go over some of them really briefly,
1) I don't have to spend all of my time watching Twitch streams.
2) I don't like appearing in the viewer list of unfamiliar channels and then feeling pressured into following
3) Very often, when it coming towards the end of a stream I am watching, it's not just the streamer that is tired, but I am also tired. I start winding down with the streamer, very often staying awake an extra hour just to watch them to the end, but then when the end comes, it just feels awkward, like, oh, damn, they're going to raid, I'd better make sure I time my exit just right since I don't have unlimited time or energy.
This raid thing is actually just a nuisance to me as a viewer. Streamers do it because they're waiting for that day they get a big raid themself, and get loads of followers, but all those people that join a raid, already follow like 200 people. Are they really subscribing to every single one of those? no, not a chance, in the majority of cases anyway.
Anyway, I just don't don't like fdeeling pressured, and since Twitch is the only one truly benefitting from its raid trap, the only one left to be able to do anything is BTTV.  so, please make this a feature, because it's getting really really old abd awkward, and I feel pressured, and resentful of Twitch for taking HALF of my money,m but excluding basic features like not being dragged into another stream after the stream I'm watching ends, and then snitched on by being in their viewer list automaticfally. This whole thing just stinks to high heaven and something has to be done. As a viewer, I have had enougfh of it.

**Comment by night** [comment] 2022-05-16 04:09
duplicate of #2936

**Closed by night** 2022-05-16 04:09 UTC
Labels: duplicate
