### ISSUE TITLE
Offline Followed Channels not Hidden

### ISSUE THREAD

**Issue by Seintian** [night/betterttv#3984] opened 2020-06-22 13:11 UTC
Hi, I'm using the extension 'BetterTTV' and I turned On in the Options the string "Hide Offline Followed Channels — Removes offline followed channels in the sidebar" but I still see my offline followed channels. How can I fix it?
![Bug Reported Offline Channels not Hidden BetterTTV](https://user-images.githubusercontent.com/67272261/85291188-7fc80680-b49a-11ea-99b7-da11f825009e.png)

**Comment by Nareese** [comment] 2020-06-22 15:26
duplicate of #3868

**Closed** 2020-06-22 19:18 UTC
Labels: duplicate
