### ISSUE TITLE
Emotes

### ISSUE THREAD

**Issue by Kopaka3344** [night/BetterTTV#171] opened 2015-01-16 22:17 UTC
the emote box on my BTTV extention is gone and wont return even if i reload a screen how do i fix it to get it back?

**Comment by night** [comment] 2015-01-16 22:21
Duplicate of https://github.com/night/BetterTTV/issues/160

**Closed by night** 2015-01-16 22:21 UTC
Labels: duplicate

**Comment by xMuneco** [comment] 2019-03-29 19:06
I'm having the same issue.
