### ISSUE TITLE
Add an option to see original username color

### ISSUE THREAD

**Issue by pavelicii** [night/betterttv#4357] opened 2021-02-12 21:51 UTC
Currently, BTTV changes username colors and there is no option to disable it. I think unconfigurable modifications to the user experience are not a good thing.  

You can see on the screenshots my original username in the settings (bottom one) and how it is shown in the chat.

Suggestion: Add an option to prevent BTTV from changing original color names. Personally, I think this option should be enabled by default but it would be nice to at least have it.
![Screenshot_1](https://user-images.githubusercontent.com/26544034/107826135-66f7c280-6d95-11eb-9cd4-102e59b0ea13.png) ![Screenshot_2](https://user-images.githubusercontent.com/26544034/107826141-695a1c80-6d95-11eb-8792-124028c40864.png)

**Comment by night** [comment] 2021-03-15 01:39
duplicate of #3320

**Closed by night** 2021-03-15 01:39 UTC
Labels: duplicate
