### ISSUE TITLE
7tv emotes no longer work on YouTube

### ISSUE THREAD

**Issue by jingofett** [night/betterttv#7129] opened 2024-10-24 23:18 UTC
### Describe the bug

As of a couple of days ago, 7tv emotes do not show up using the BTTV extension. This may be an issue related to their site update.

### Steps to reproduce

1. Install BTTV
2. Enable 7tv emotes
3. Enable YouTube support
4. Go into a chat with 7tv emotes enabled (ludwig's)

### Expected behavior

7tv emotes to work

### Screenshots

![image](https://github.com/user-attachments/assets/52f55167-3d4b-4f24-a817-462414c06c7c)

### Device information

- PC
- Windows 10
- Firefox/Chrome
- 131.0.3/129.0.6668.104

### BetterTTV Version

7.6.8

### Version Check

- [X] I have checked that I'm using the newest version of BetterTTV available.

**Comment by vilapupu** [comment] 2024-10-28 00:09
Came here to say that I'm also having this issue and it's a bit annoying as I would always use the Clap emote from 7TV. As dobypeti said, global emotes does NOT show up in chat, and on the emote picker on Twitch. I only see channel-specific 7TV emotes on twitch.

Please resolve this. 

running Windows 10 on the latest version of Chrome, betterttv Version 7.6.8

**Comment by night** [comment] 2024-10-28 01:46
duplicate of #7117

**Closed** 2024-10-28 01:46 UTC
Labels: bug

**Comment by jingofett** [comment] 2024-10-30 22:16
> duplicate of #7117

This is not just global emotes on YouTube, all emotes from 7tv weren't working. After the update to 7.6.9 on Chrome, however, global emotes show up, still missing channel emotes however!
![image](https://github.com/user-attachments/assets/4694656a-d317-4079-9fd0-f54734e98973)

**Comment by jingofett** [comment] 2024-11-11 06:54
Hey, sorry to bump this again, but my issue was not resolved. I was reporting on an issue with user channel 7tv emotes not working on YouTube. The global ones have always worked for me.

**Comment by night** [comment] 2024-11-12 16:31
If you're still seeing issues, it's because the streamer hasn't linked their YouTube channel to their Twitch account at https://betterttv.com

**Comment by jingofett** [comment] 2024-11-15 05:44
Yeah, but I think 7tv just completely changed how they did it, I am able to get around it thanks to this setup: https://github.com/Rydann/temp-fix-7tv-youtube/

Would be very useful if you could plug in these values in the BTTV extension, but probably not worth it for you guys, I'll be honest lol.
