### ISSUE TITLE
Option to hide player controls

### ISSUE THREAD

**Issue by jfgoncalves** [night/BetterTTV#1112] opened 2016-05-05 10:01 UTC
Hi, is it possible to add a button to hide the Twitch player controls? I'm using BetterTTV on Safari, and I'd like to use the built-in safari controls (that supports Airplay) instead of the one made by Twitch, without having to right click and open the video in a new tab.

**Comment by night** [comment] 2016-05-07 01:33
duplicate of #741

**Closed by night** 2016-05-07 01:33 UTC
Labels: duplicate
