### ISSUE TITLE
Edit button on twitch failing

### ISSUE THREAD

**Issue by Simplykrystalttv** [night/betterttv#4401] opened 2021-03-12 05:09 UTC
Hi there, I was told by Nareese on Discord I should post an issue! The edit button on twitch is no longer available to edit usernames. I use it to add peoples names/pronouns daily in my streams and the edit button is no longer there. 

Halllp

**Comment by night** [comment] 2021-03-15 02:47
duplicate of #4400

**Closed by night** 2021-03-15 02:47 UTC
Labels: duplicate
