### ISSUE TITLE
Cant Change usernames on twitch chat.

### ISSUE THREAD

**Issue by DerekJustis** [night/BetterTTV#3785] opened 2020-03-13 03:12 UTC
On my channel not able to change peoples twitch names. I can only click on the pop-out icon or Close (X). I cant click the pencil one to change peoples names cause the icon are too close together. I suggest you move the pencil icon below the X imo. Here is Pic. 
![image](https://user-images.githubusercontent.com/62126397/76586266-c7f88580-64b6-11ea-8cc7-149d8eb2b01e.png)

Quote that I can change usernames in other channels cause the pop-out icon is not there.

**Comment by Nareese** [comment] 2020-03-13 10:59
duplicate of #3782

**Closed** 2020-03-22 03:42 UTC
Labels: duplicate
