### ISSUE TITLE
Click to Insert Emote not working

### ISSUE THREAD

**Issue by Gorillabot3000** [night/BetterTTV#174] opened 2015-01-17 03:47 UTC
The icon isn't on the bottom of the chat anymore for me, so I can't open the Emote menu. I attempted turning the option on and off, and attempted refreshing the page. Neither worked.

**Comment by night** [comment] 2015-01-17 03:56
Duplicate of https://github.com/night/BetterTTV/issues/160

**Closed by night** 2015-01-17 03:56 UTC
Labels: duplicate
