### ISSUE TITLE
Left side chat not working

### ISSUE THREAD

**Issue by justhereforvs** [night/betterttv#3858] opened 2020-05-11 23:48 UTC
When enabled, left side chat setting breaks chat. Entire chat window disappears, and no messages are displayed. Restarting, clearing cache, etc. had no effect. Firefox 76.0.1 (64-bit) on KDE Manjaro Linux.

**Comment by Nareese** [comment] 2020-05-12 00:03
duplicate of #3852

**Closed** 2020-05-13 07:08 UTC
Labels: duplicate
