### ISSUE TITLE
Readable Colors not working in Mod View chat

### ISSUE THREAD

**Issue by KamasamaK** [night/betterttv#6964] opened 2024-07-28 16:30 UTC
### Describe the bug

The "Readable Colors" option doesn't seem to work correctly in Mod View chat. Although it seems fine in the Mod View viewer card.

### Steps to reproduce

1. Enter Mod View for a channel
2. View the chat

### Expected behavior

To see the same readable colors from normal chat

### Screenshots

![image](https://github.com/user-attachments/assets/003ab983-3f85-437a-9958-54ae69b5947d)

### Device information

Firefox 128.0.2

### BetterTTV Version

7.6.5

### Additional information

- I have no other Twitch extensions installed
- Performing a force reload does not help

### Version Check

- [X] I have checked that I'm using the newest version of BetterTTV available.

**Comment by KamasamaK** [comment] 2024-07-28 17:00
I should note it doesn't seem to do this all the time. But it is most of the time in my experience.

**Comment by dclstn** [comment] 2024-08-27 11:41
Hi, I'm unable to reproduce this behaviour you're seeing. Are there any error-logs related to BetterTTV when loading the page/chat? Do you still see BetterTTV related badges?

**Comment by night** [comment] 2024-09-01 19:07
I also can't seem to reproduce this, so I'm guessing it may have been a temporary issue? Closing this for now, but if issues persist please let us know!

**Closed by night** 2024-09-01 19:07 UTC
Labels: bug

**Comment by KamasamaK** [comment] 2024-09-01 19:43
I'm not sure where I am expected to find the error-logs related to BetterTTV. I checked the browser console and the only thing I see are warnings from `betterttv.css` but I don't figure those warnings are unique to me. I can post them if you think that would be helpful, but I'm not sure of a good format to do so as there are so many. Everything else from BetterTTV seems to be working on the page. It's just the name colors in mod chat. And the issue does persist for me.

I'm on the same version of BetterTTV as when this issue was opened, but Firefox has since been updated to 129.0.2

**Comment by night** [comment] 2024-09-01 20:43
can you show us a video demoing the issue? and can you confirm if you have twitch's readable setting on/off and betterttv's setting on/off?

**Comment by KamasamaK** [comment] 2024-09-05 19:55
@night I'd rather not take a video of the chat. I'll just disable BetterTTV's. Twitch's seems to work well enough for me. For what it's worth, it seems to occur inconsistently regardless of whether Twitch's is also enabled. But I am curious, is it intended for Twitch's to be on or off for BetterTTV's to work properly?
