### ISSUE TITLE
Chat - New Feature

### ISSUE THREAD

**Issue by bunnibon** [night/BetterTTV#1370] opened 2016-07-12 20:46 UTC
Hey there,

So as a fellow BTTV and Twitch user, I noticed that while having 2 monitors, it can be a hassle looking over to the other side of the monitor to read the chat. And so for this reason, maybe have the option to switch the chat from the right side to the left side? It would be really helpful for those with 2 monitors and it would save a lot of time.

Thank you!

**Comment by MattiSony** [comment] 2016-07-15 01:37
Duplicate of #202

**Closed** 2016-07-15 09:00 UTC
Labels: duplicate
