### ISSUE TITLE
Compact emotes/gifEmotes

### ISSUE THREAD

**Issue by Preloom** [night/BetterTTV#3619] opened 2019-10-19 21:01 UTC
Have an option to turn on compacting emotes for either static or gif emotes.  A single message with multiple emotes would only show the emote then "xN"

Example:  

> preloom: pepeD pepeD pepeD pepeD pepeD pepeD pepeD

 
would become: 

> preloom: pepeD x7

This would prevent potential latency issues caused by loading a ton of emotes at once.

**Comment by Vagmer** [comment] 2019-10-24 01:16
Dunno about helping with latency (or more like possible transient slowdowns on weak computers), but that could actually be pretty cool for reducing spam footprint, essentially a form of filtering. A pretty damn good idea for that.

**Comment by night** [comment] 2019-10-28 09:12
duplicate of #1922

this is an interesting idea we've toyed with. i do fear it would be expensive computation wise in practice

**Closed by night** 2019-10-28 09:12 UTC
Labels: duplicate

**Comment by Vagmer** [comment] 2019-11-22 18:27
> this is an interesting idea we've toyed with. i do fear it would be expensive computation wise in practice

Yes, as said, it probably wouldn't reduce resources used, but instead increase them for the sake of a better user experience, just like other BTTV features. Might have been different a good few years back, but that isn't a very relevant fear in modern times. In the end, the equation we have still involves modern computers and CPUs operating a web browser/JavaScript/text parsing. In this case, a higher percentage than normal of users is even guaranteed to have stronger than average/gaming PCs. Considering this would be an optional feature up to the user to turn on, this worry itself can't be a good reason to flat out disregard this idea. Of course, it's already commonplace today for people to use browser extensions to do sometimes tons of extra work on every loaded page or even on every web request. uBlock Origin processing literally tens of thousands of filters per web request, anyone? 😃 

I don't know how well they currently work if they are even up-to-date with current Twitch, but this very same cleaned-up/filtered chat functionality has [apparently already been done by some UserScripts](https://greasyfork.org/en/scripts?utf8=%E2%9C%93&q=twitch+chat) in the past. Could be a good first (maybe even last) place to look.
