### ISSUE TITLE
BetterTTV for the Twitch Desktop App

### ISSUE THREAD

**Issue by F-Lambda** [night/BetterTTV#3407] opened 2019-03-13 04:03 UTC
This past week, Twitch released a full revamp of the Twitch Desktop App, bringing all the features of the web app to the desktop. This includes things like Extensions Connections, which previously were incompatible with the desktop app.

With this full revamp, is it now possible to bring BetterTTV to the desktop app?

**Comment by night** [comment] 2019-04-22 08:04
duplicate of #2613

**Closed by night** 2019-04-22 08:04 UTC
Labels: duplicate
