### ISSUE TITLE
Whitelist certain Extensions?

### ISSUE THREAD

**Issue by privacyguy123** [night/betterttv#5470] opened 2022-07-04 17:41 UTC
I like the idea of blocking this extra eye offending crap but when watching Hearthstone streams the Hearthstone Deck Tracker and Firestone overlays are actually useful - perhaps adding a whitelist to allow certain extensions might be possible?

**Comment by night** [comment] 2022-10-01 02:27
duplicate of #3511

**Closed by night** 2022-10-01 02:27 UTC
Labels: duplicate
