### ISSUE TITLE
Hide Soundtrack Extension

### ISSUE THREAD

**Issue by nakomaru** [night/betterttv#4208] opened 2020-10-21 15:29 UTC
When a stream is using the Twitch [Soundtrack](https://www.twitch.tv/soundtrack) feature, an overlay will be shown over the stream upon mouseover similar to ordinary twitch extensions.

![image](https://user-images.githubusercontent.com/6320401/96741326-a2443f00-13fc-11eb-9ece-372a78a9ee6b.png)

This can be hidden via the stream settings window. However, the setting is not saved in any way.

![image](https://user-images.githubusercontent.com/6320401/96741668-02d37c00-13fd-11eb-9888-1a3bde73510e.png)

Similar to the "Hide Twitch Extensions" setting, this is a feature request for a "Hide Twitch Soundtrack" setting to be added or included within the "Hide Twitch Extensions" setting itself.

![image](https://user-images.githubusercontent.com/6320401/96741806-34e4de00-13fd-11eb-92cf-31ba046f569f.png)

Kind regards.

**Comment by night** [comment] 2022-10-01 02:27
duplicate of #3511

**Closed by night** 2022-10-01 02:27 UTC
Labels: duplicate
