### ISSUE TITLE
Full screen theather mode.

### ISSUE THREAD

**Issue by MaerkStrongrock** [night/BetterTTV#862] opened 2015-12-17 01:50 UTC
Having a full screen with chat has been something I would really enjoy! And I think alot would!

**Comment by voloshink** [comment] 2015-12-17 01:51
Don't think that's somethign we can do

**Comment by night** [comment] 2015-12-19 03:26
Duplicate of #342.

**Closed by night** 2015-12-19 03:26 UTC
Labels: duplicate

**Comment by MaerkStrongrock** [comment] 2015-12-23 07:36
aww :(
