### ISSUE TITLE
Emote glitch

### ISSUE THREAD

**Issue by SoggyWenis** [night/BetterTTV#2047] opened 2017-02-09 02:21 UTC
This has been happening since the day that the servers went down

https://i.gyazo.com/ab56da8218d864cb9293f8ebc21ad8fb.png

If I refresh the page *sometimes* that fixes it and sometimes it doesn't. This is happening very often

**Comment by night** [comment] 2017-02-09 09:17
duplicate of #2022

**Closed by night** 2017-02-09 09:17 UTC
Labels: duplicate
