### ISSUE TITLE
Chrome Browser's Side Scroll Bar appearing and disappearing

### ISSUE THREAD

**Issue by BOSSHOGG94** [night/BetterTTV#2268] opened 2017-04-14 02:34 UTC
With Left Side Chat mode On the side scroll bar for the chrome browser shows when i mouse over the center of the right sidebar during a live stream. It happens on a smaller window size(not maximized). It gets annoying when the right sidebar moves back and forth when im trying to change between followed channels that are live. Its better if you are to completely hide chrome's scroll bar. Please Fix.

**Comment by Aaron128l** [comment] 2017-04-15 05:51
I for one can't reproduce this behavior. I see no native sidebars with left chat enabled on a smaller window while watching a live stream (in the new layout). You might need to provide an image or video of it happening.

**Comment by night** [comment] 2017-04-16 21:29
Please provide a gif of this happening as well as steps to reproduce. I cannot reproduce this issue either.

**Comment by night** [comment] 2017-04-21 06:53
Closing due to non-response.

**Closed by night** 2017-04-21 06:53 UTC
Labels: invalid
