### ISSUE TITLE
Feature Request for Emote Spam

### ISSUE THREAD

**Issue by Dan-Y89** [night/BetterTTV#3699] opened 2019-12-19 21:09 UTC
Hello, I wanted to request a function that might be very useful for many.
A young developer had written an addon 3 years ago, which curbs the emote spam a little bit, so that users no longer get browser problems or even worse things like crashes.
Maybe you take a look at this:

https://www.youtube.com/watch?v=RWK4uH3_Ddo&feature=emb_title

The problem is that if the emote spam is too strong, the stream may be stuck or the browser may crash. To prevent this, the addon is really great, but unfortunately it no longer works and the developer can no longer be reached, so I hope that you might be able to incorporate such a function? According to the files, this will probably be a bit of work.
But it would be very nice for users who want to protect their PC and browser and don't want to overload it, and it also makes it much easier to read the chat. So I hope this feature will be added. 

The same could be done at a giveaway where the same word is spoken all the time. (often happens in large channels where you then have browser problems.)
But the most important thing is for the emotes.
Thank you and wish you a nice week.

His Github Project where I got the idea:
https://github.com/nhatbui/compakt

Thanks and nice Greetz from Germany
<3

**Comment by night** [comment] 2019-12-23 19:43
duplicate of #1922

**Closed by night** 2019-12-23 19:43 UTC
Labels: duplicate
