### ISSUE TITLE
Disable Host Mode stopped working

### ISSUE THREAD

**Issue by Trunkscool** [night/BetterTTV#2615] opened 2017-08-12 18:10 UTC
Hello,
I've been using BTTV for a while now and when they added the Autohost option I was glad to know that BTTV had an option to turn this off.
However, since yesterday 11 August, this option stopped working altogether.
Please roll a fix as soon as possible, this is frustrating when I listen to streams just before going to sleep, some of the streamers I watch have a very different sound level than the ones they host, and that does wake me up from time to time.
Thanks
![bttv](https://user-images.githubusercontent.com/30960314/29243216-549103fa-7f9a-11e7-9650-54683cc456fc.jpg)

**Comment by Nareese** [comment] 2017-08-12 19:06
duplicate of #2601

**Closed** 2017-08-13 01:53 UTC
Labels: duplicate
