### ISSUE TITLE
Sidebar for BTTV on Youtube returning 300x300 icon for Profile Image Causing UI Display issues.

### ISSUE THREAD

**Issue by Anglee6994** [night/betterttv#5307] opened 2022-04-01 23:55 UTC
class="bttv-Icons-module__icon-cCRBV" returning 300x300 image on Youtube BTTV Extension instead of 28x28 (not sure on the default size) image.
This is causing entire display to be obfuscated by User Profile image.

Unable to replicate issue on other channels except my own.
Viewers are indicating the same issue when using the extension via Desktop Extensions for Chrome.

BTTV Profile:
https://betterttv.com/users/5ef24e1f79645a0dec34ffda
Youtube:
https://www.youtube.com/channel/UCtWG1eeG7BIMSk_Ks8Xew6w

![ApplicationFrameHost_gCix22qh2U](https://user-images.githubusercontent.com/102836419/161355275-6936a470-7b30-408a-8f6d-b8b24aaf99d2.png)

**Comment by dclstn** [comment] 2022-04-02 00:03
duplicate of #5305, fix is already underway

**Closed by dclstn** 2022-04-02 00:03 UTC
Labels: duplicate
