### ISSUE TITLE
Feature Request: Change chat font size

### ISSUE THREAD

**Issue by craighton** [night/BetterTTV#428] opened 2015-05-19 03:36 UTC
I like to throw Twitch up on to a TV from across the room, it'd be cool if there was an option to increase the font size so that I could read it from far away.

**Comment by Powersource** [comment] 2015-05-19 11:17
Doesn't the regular browser zoom work?

**Comment by craighton** [comment] 2015-05-19 14:13
Yes and no. 

Yes it works. 

But not really because it breaks some of the page elements.

**Comment by night** [comment] 2015-05-20 08:55
Duplicate of #57

**Closed by night** 2015-05-20 08:55 UTC
Labels: duplicate
