### ISSUE TITLE
Option to automatically set the quality of all newly opened streams to Source

### ISSUE THREAD

**Issue by Rickeitje** [night/betterttv#4174] opened 2020-10-05 19:35 UTC
I dislike that the twitch default is auto and it lowers the quality when the tab is not focused so I would like an option that automatically sets newly opened streams to source quality.

**Comment by Nareese** [comment] 2020-10-05 20:19
duplicate of #3513 

Note that Twitch automatically lowers stream quality when the tab is not focused regardless of what quality you have it set on.  Setting to source, manually, or hypothetically, automatically, will not prevent this behavior.  So your requested feature would not achieve your desired result.  What you are really asking for is the functionality contained in the referenced request.  I wouldn't expect to see it any time soon, if it is even possible at all.

**Closed** 2020-10-05 20:23 UTC
Labels: duplicate
