### ISSUE TITLE
BTTV not working with chat on Firefox

### ISSUE THREAD

**Issue by QPDangerous** [night/BetterTTV#2112] opened 2017-03-07 23:50 UTC
BTTV is not loading while using the chat popout in FF, it will load for chat if watching a stream normally though. I tried clearing cache/cookies but it still wouldn't load for me. Some features will still load for chat popout (blue buttons, emote menu) but BTTV emotes/gifs, dark mode, and hide bits not working.

I tried google chrome and it is working there. I did not have this issue until today.

**Comment by CoolCmd** [comment] 2017-03-10 16:06
Confirmed
Firefox 52: BTTV fail
Chrome 57: BTTV OK

**Comment by night** [comment] 2017-03-14 07:32
Apologies for the delay. I have not had time to look into this yet, but will try to later today.

**Comment by CaelThunderwing** [comment] 2017-03-16 03:55
i just started having the issue but in reverse (Working in FF pop out chat but not in normal view.)

**Comment by Arastir** [comment] 2017-03-16 20:25
Having the same issue, pop out chat works but normal chat does not or will work eventually after MULTIPLE refreshes.  This was happening before the update as well.

**Comment by xsonarx** [comment] 2017-03-18 17:00
Any fix on the way for this? popout chat works but firefox normal chat for twitch has been broken for nearly 2 weeks now :(

**Comment by mountnstream** [comment] 2017-03-18 17:04
I also find that the popout chat works, but it doesn't have BTTV loaded onto it.

**Comment by romano** [comment] 2017-03-19 18:18
Same here, but on Chrome, and only initially. After refreshing it a couple of times it loads fully.

**Comment by night** [comment] 2017-03-20 05:45
If you're still having issues, we released a beta version of BetterTTV v7, which is a complete rewrite. It should address these race issues plaguing the extension for so long.

To try it out, enable the beta from the BetterTTV settings. Note: Currently when you turn on the beta, there's no way back. If you want to go back, you need to clear your cookies (thus losing your settings). If you want to save your settings just in case, make a backup before turning on the beta.

**Comment by mountnstream** [comment] 2017-03-20 05:50
The beta now makes it so that BTTV shows up when I popout chat. I'll have to see if it guarantees loading the chat regularly from now on.

**Comment by night** [comment] 2017-03-20 07:16
> I did find that @'ing someone in chat doesn't bring up a list when typing in letters.

This is very much in progress still, hence the beta.. we don't have a visual completion list.. but tab completion works, just press tab

**Comment by CoolCmd** [comment] 2017-03-20 11:41
Version 7 settings are compatible with version 6 settings? For example, if I will start v6 => v7 => v6 (by deleting bttv_beta) => v7, some of the settings for version 6 will be changed?

**Comment by EhsanKia** [comment] 2017-03-20 17:37
Yes, we recommend you backup your settings using the backup feature before switching to the beta.

**Comment by Bullet25fxbx** [comment] 2017-03-31 03:30
I can not get the beta to enable. I have to manually navigate to the settings page, https://www.twitch.tv/directory?bttvSettings=true since none of the BTTV options show up for me on Twitch anymore. Toggling the beta button does nothing and refreshing that page untoggles it.

**Comment by night** [comment] 2017-03-31 03:48
If you're unable to set the setting, in the console type `localStorage.bttv_beta = "true"` and press enter. Then, refresh the page.

**Comment by Bullet25fxbx** [comment] 2017-03-31 12:02
@night @SW1FT I got it over to the beta by exporting the settings from that link I posted. Opening them in Notepad++ and the spot that said "Beta="False"" changed it to true and importing those setting again.

**Comment by SW1FT** [comment] 2017-03-31 14:33
@Bullet25fxbx That settings page you linked doesn't even open on my end. It's weird, some other addon might be conflicting with BTTV, but it wasn't before...

**Comment by night** [comment] 2017-04-03 09:42
Closing this as the beta fixes Firefox issues.

**Closed by night** 2017-04-03 09:42 UTC
