### ISSUE TITLE
BTTV settings not applied to VODs

### ISSUE THREAD

**Issue by Teleshot** [night/BetterTTV#2689] opened 2017-09-24 12:50 UTC
Twitch recently changed VODs so they work similarly to uploaded videos, with the chat now displaying "Chat on Videos". When Twitch implemented this change it caused some of the functionality of BTTV to stop working on VODs such as Split Chat and BTTV emotes. Name colors are also no longer appearing in the VOD chat.

Would it be possible to re-add these features to the new VOD chat system?

**Comment by ryubean** [comment] 2017-09-25 16:48
I would love to know the same thing, i mostly watch VODs on twitch, and it would be wonderful to actually see the emotes

**Comment by night** [comment] 2017-09-26 07:03
duplicate of #2683

**Closed by night** 2017-09-26 07:03 UTC
Labels: duplicate
