### ISSUE TITLE
The ability to pause chat when the curser is over it

### ISSUE THREAD

**Issue by dannyinwonderland** [night/BetterTTV#1406] opened 2016-07-28 16:24 UTC
I will say BTTV makes Twitch so much better. However, recently I've been using Chatty and it has some features that I like and it makes being a moderator better. Unless I am missing it, I don't see it in the BTTV settings. So, let me know if I am just skipping over this option. 

In Chatty, if I put the curser over the chat, it will pause the chat while the curser is there. Even the option of pushing a key to pause chat while a key is pressed could be helpful. That makes clicking a username, the timeout or ban option a lot easier. Sometimes when there is a few hundred viewers, chat is going pretty quick and it can be difficult to click the right username or option for a specific user. I know I can just type commands out, but I feel like this would be a nice feature to add if it's not already.

**Comment by night** [comment] 2016-07-28 17:32
duplicate of #1391

**Closed by night** 2016-07-28 17:32 UTC
Labels: duplicate
