### ISSUE TITLE
Smile menu is not working

### ISSUE THREAD

**Issue by SilentNewbee** [night/BetterTTV#2993] opened 2018-02-24 15:19 UTC
When I select a smile from the menu in the message sending field, it is automatically removed from the field. Also, when you open the menu, only those smiles that were favorites are shown. What should I do to solve this problem?
https://gyazo.com/fa28f73768de578906e2b84e1b848e3b - screenshot of the second problem

**Comment by night** [comment] 2018-02-25 06:06
duplicate of #2987

**Closed by night** 2018-02-25 06:06 UTC
Labels: duplicate

**Comment by SilentNewbee** [comment] 2018-02-25 16:43
When you open the menu, only those smiles that were favorites are shown. What should I do to solve this problem? https://gyazo.com/fa28f73768de578906e2b84e1b848e3b - This problem is not duplicate.
