### ISSUE TITLE
"Hide Recommended Channels" not working - Chrome Browser, Macbook Pro

### ISSUE THREAD

**Issue by BDaggerhart** [night/betterttv#4284] opened 2020-12-16 14:20 UTC
Title.  All the other features I like to use work just fine, but for some reason, clicking the "Hide Recommended Channels" doesn't work.  It used to work just fine, I don't recall when it stopped working, maybe in the last month or so.  Image included.

Chrome/Brave brower (up to date);
BTTV extension (up to date);
Macbook Pro 10.15.6 Catalina

![bttv-hide-recommended-friends-not-working](https://user-images.githubusercontent.com/2512570/102360389-f2b0c680-3f7f-11eb-88a6-ea71b127dae0.jpg)

**Comment by night** [comment] 2020-12-18 02:12
duplicate of #4183

**Closed by night** 2020-12-18 02:12 UTC
Labels: duplicate
