### ISSUE TITLE
Left Side Chat function shrinks video smaller

### ISSUE THREAD

**Issue by s3lbie** [night/betterttv#4249] opened 2020-11-29 07:34 UTC
When the Left Side Chat function is turned on, the video becomes shrunk as though it still recognises the right side chat panel.
![image](https://user-images.githubusercontent.com/69639355/100535952-13330e00-3269-11eb-814f-d2dd25716fa0.png)

**Comment by night** [comment] 2020-11-29 08:05
duplicate of #4243

**Closed by night** 2020-11-29 08:05 UTC
Labels: duplicate
