### ISSUE TITLE
Pressing Enter to Send Messages in Chat is not Working for Me.

### ISSUE THREAD

**Issue by Kyzachable** [night/BetterTTV#2490] opened 2017-05-29 00:15 UTC
Today I got on Twitch and was gonna send something in a streamer's chat, but when I pressed the enter key it did not send. Instead it when down a text row like if I pressed enter in Microsoft Word. I know this has something to do with Better Twitch TV because when I disabled it in my Chrome Extensions to see if it was the cause of this issue, it did not happen and pressing enter to send a message in a streamer's chat worked. This is very irritating because I am used to pressing enter to send something in a streamer's chat, now I have to press the "Chat" button. I will not be using BTTV until this is fixed. I would appreciate the help if it has to do with something on my end, but if not I hope this "bug" gets fixed asap. I would appreciate a response. Thanks.

**Comment by Kyzachable** [comment] 2017-05-29 00:20
I saw that someone else made a ticket for this issue about an hour ago. So I know I am not the only one having this issue.

**Comment by night** [comment] 2017-05-29 00:31
duplicate of https://github.com/night/BetterTTV/issues/2489

**Closed by night** 2017-05-29 00:31 UTC
Labels: duplicate
