### ISSUE TITLE
Feature request: Highlight messages mentioning streamer

### ISSUE THREAD

**Issue by Iwasawafag** [night/BetterTTV#847] opened 2015-12-04 23:08 UTC
Hello. 

Subj. Would be nice to have messages, mentioning streamer, highlighted (as an option). Would make sense to highlight them with a different color from the one used on messages mentioning you.

**Why this might be needed:**
Often on popular streams, where a lot is going on in the chat, streamers tend to pay more attention to the messages mentioning them. And some of them responding to chat messages without reading the message itself. 
I think it's going to improve viewer experience, since it will be easier to find out what message streamer just replied to.

**Comment by night** [comment] 2015-12-06 09:58
Assuming you follow the broadcaster, it would be a duplicate of #94

**Closed by night** 2015-12-06 09:58 UTC
Labels: duplicate
