### ISSUE TITLE
Sidebar - Followed Channels - Hide Reruns

### ISSUE THREAD

**Issue by makoshells** [night/betterttv#4337] opened 2021-01-30 16:08 UTC
Hi, 

thank you for the great extension, the quality of life settings are great. 

In my sidebar (left for me), in the top section of this sidebar are my followed channels which displays currently live streamers who I follow. However, if somebody I follow does a rerun, it is also shown in this list but I think Twitch changed this at some point so that the rerun's at least appear at the bottom of the "Following" list, irregardless of viewer count. 

It would be great to be able to hide these rerun's in my sidebar. Personally, I only want to see the icon of a streamer in my sidebar, if they are actually live. 

I'd really appreciate this feature. Cheers and have a good one.

**Comment by night** [comment] 2021-03-15 01:32
duplicate of #2496

**Closed by night** 2021-03-15 01:32 UTC
Labels: duplicate
