### ISSUE TITLE
Left Side Chat

### ISSUE THREAD

**Issue by Zepatt** [night/betterttv#4036] opened 2020-07-11 11:29 UTC
I noticed today that the Left Side Chat setting is a bit broken, this is what twitch currently looks like with it enabled: https://gyazo.com/1723dbea8cf2f5b99be2c682641f8091
But before today the "Followed Channels" tab was moved to the right side if you had Left Side Chat enabled, meaning that the stream video player was nicely placed in the middle between the chat and the "Followed Channels" tab, and it looked like this but the chat and "Followed Channels" tab switched places: https://gyazo.com/3652e6f9490ffc7f094775887ade7136

I hope this is indeed a bug because everything was fine before and hopefully this can be fixed

**Comment by night** [comment] 2020-07-12 19:23
duplicate of #4029

**Closed by night** 2020-07-12 19:23 UTC
Labels: duplicate
