### ISSUE TITLE
BTTV not working

### ISSUE THREAD

**Issue by xzPr** [night/BetterTTV#2982] opened 2018-02-22 21:54 UTC
Hello
I am having issues with my betterTTV. Followed steps listed in: https://community.nightdev.com/t/betterttv-debugging/3685
And I ended up here :) Here's screen from my JavaScript console: 

![error](https://user-images.githubusercontent.com/36747004/36566033-9e6cc984-1822-11e8-8d87-e885d0183fed.png)
 
I hope to receive any help. Thanks in advance :)

**Comment by ElectronicWar** [comment] 2018-02-22 22:15
I am getting "Stalled within buffer". It worked till yesterday.

![image](https://user-images.githubusercontent.com/1890874/36567305-47cbe49e-1826-11e8-9c08-c07246f29d75.png)

**Comment by Nareese** [comment] 2018-02-22 22:50
Twitch has changed the internals of their site this afternoon and that has affected BTTV.  It will take some time to figure out what they've changed and figure out workarounds.  The developers are aware of the issue.  No ETA at present.

**Comment by mysticentity** [comment] 2018-02-23 03:08
[http://prntscr.com/iikmyk](url) Have this issue too and seem to have a some what different response in the console. However I do notice that if I pop out the chat in legacy mode it shows BetterTTV settings under the gear icon (You cannot select it though) and has retained from what it looks like the settings I had with it before.

**Comment by night** [comment] 2018-02-23 07:52
fixed in master

**Closed by night** 2018-02-23 07:52 UTC
Labels: bug

**Comment by designboxcom** [comment] 2019-03-14 20:43
Confirmed. Same here, nothing work anymore today...
