### ISSUE TITLE
Use new Safari extension converter to get a native MacOS extension in Big Sur

### ISSUE THREAD

**Issue by tytusplanck** [night/betterttv#4110] opened 2020-08-25 13:45 UTC
Announced at WWDC this year Apple is allowing developers to create/produce Safari extensions in an easier manner by providing tools for converting existing Chrome/Firefox extensions. Should BTTV look into this to provide a solution for Safari users?

**Comment by night** [comment] 2020-08-30 05:55
duplicate of #3158

**Closed by night** 2020-08-30 05:55 UTC
Labels: duplicate
