### ISSUE TITLE
Word filter that doesn't remove the messages completely

### ISSUE THREAD

**Issue by RandomTwitchUserThatWantsSomeFeatures** [night/BetterTTV#1668] opened 2016-10-18 16:04 UTC
Would it be possible? Some words / emotes are just ugly or annoying, same goes for some words. I don't like how the blacklist words delete the messages completely, I'd rather see the blacklisted word turned into *** instead, so I can read the messages anyway.

**Comment by night** [comment] 2016-10-21 03:01
duplicate of #581

**Closed by night** 2016-10-21 03:01 UTC
Labels: duplicate
