### ISSUE TITLE
Better TTV does not show chat

### ISSUE THREAD

**Issue by AreEdw** [night/BetterTTV#2056] opened 2017-02-10 16:23 UTC
Better TTV loads everything on firefox but does sometimes not show chat. If I refresh the page sometimes it loads correctly.
It shows chat for 0.5 seconds then disappear.
I can write in chat and it shows on stream chat.
I can be on the channel and other chat groups work but not the one for the stream. Subscribe messages and timeout calls show.

I have refreshed Firefox, reinstalled TTV

This is before page is fully loaded.
![2017-02-11 1](https://cloud.githubusercontent.com/assets/905463/22851670/e8e8e942-f029-11e6-8d80-7b263886a179.png)

This is after it Loads fully.
![2017-02-10](https://cloud.githubusercontent.com/assets/905463/22834383/36690f6e-efb5-11e6-99fa-f2cc965910f4.png)

(Update)
If I select another chat group messages for that group are shown but I can see that new messages are available in the channel group. If I switch back it still is blank.

It is as if the data is received but TTV does most of the time not know where to put it.

**Comment by animorph127** [comment] 2017-02-11 00:15
same as my post and i have the exact problem, i've had it for like 2 months now and i've brought it up here before but the first time they just completly ignored me

**Comment by night** [comment] 2017-02-19 11:13
duplicate of #1898

**Closed by night** 2017-02-19 11:13 UTC
Labels: duplicate
