### ISSUE TITLE
Suggestion: Editors of channel can buy subscription

### ISSUE THREAD

**Issue by NewbieHackerman** [night/betterttv#4143] opened 2020-09-14 12:29 UTC
Hello,
Nothing complicated, i just suggest to make possibility for BTTV channel editors to buy subcription for that channel.
I watch a streamer who is old prick and he is not so responislbe but i want to provide very good time for chat and emotes help to do that.
Thx

**Comment by Nareese** [comment] 2020-09-14 14:42
duplicate of #3295

**Closed** 2020-09-14 18:09 UTC
Labels: duplicate
