### ISSUE TITLE
bttv/chrome not working

### ISSUE THREAD

**Issue by Nokanah** [night/BetterTTV#2466] opened 2017-05-19 08:58 UTC
WHen I go to bttv settings there are no options to select anymore?  Cant turn on/off or anything.

**Comment by BigChief190** [comment] 2017-05-19 16:44
I am also having the same problem with bttv. none of the options show up to where i can turn them on and off.

**Comment by night** [comment] 2017-05-19 16:58
duplicate of https://github.com/night/BetterTTV/issues/2464

**Closed by night** 2017-05-19 16:58 UTC
Labels: duplicate
