### ISSUE TITLE
[Feature Request] Right-click options for highlighted chat messages

### ISSUE THREAD

**Issue by y2mq37** [night/BetterTTV#2087] opened 2017-02-23 11:20 UTC
Highlighted keywords could be improved if BTTV users had the option to blacklist users directly from the pinned highlighted messages. This could be accomplished by allowing users to right click the highlighted/pinned message to open up a context menu with the option to blacklist the username. 

This kind of a system would help in situations where streams with >30,000 viewers have chat users abusing keywords to create spam. This behavior forces users to open the BTTV settings and manually add names to the blacklist. Being able to right click the highlight and blacklist would be a welcome alternative method for the whitelist/blacklist keyword feature.

**Comment by night** [comment] 2017-02-25 19:55
duplicate of #1945

**Closed by night** 2017-02-25 19:55 UTC
Labels: duplicate
