### ISSUE TITLE
BTTV Extension for iPadOS 15

### ISSUE THREAD

**Issue by michael-gram** [night/betterttv#4874] opened 2021-09-23 18:23 UTC
iPadOS 15 recently introduced browser extension support in Safari. Does this make it possible to bring BTTV to iPad?

https://www.macrumors.com/guide/ios-15-safari-extensions/?Bibblio_source=true
https://developer.apple.com/safari/extensions/

**Comment by Nareese** [comment] 2021-09-23 21:15
BetterTTV does not even support Safari on desktop natively.  The only way we support Safari on iOS is through the use of the (paid, $2) Tampermonkey extension, which allows Safari to use the userscript version of BetterTTV.  If Tampermonkey is supported on iPad iOS 15, and assuming the Twitch website operates the same in iPad Safari as it does on desktop, then it is possible it will work.  Initial investigation, however, shows that Tampermonkey is not yet supported in that environment, and hence, for the moment, neither is BetterTTV.

**Comment by ianvatega** [comment] 2022-03-29 05:37
use extensión safari ios 15.4  [makeover](https://apps.apple.com/es/app/makeover-custom-css/id1602361167)

![BC6C96D8-3296-4731-891E-778EF615F23B](https://user-images.githubusercontent.com/8468215/160540671-be43af1a-a4a1-42cc-b19f-5edec5d5c2ff.jpeg)

[link js](https://nightdev.com/betterttv/other/betterttv.user.js)

```
// ==UserScript==
// @name            BetterTTV
// @namespace       BTTV
// @description     Enhances Twitch with new features, emotes, and more.
// @copyright       NightDev, LLC
// @icon            https://cdn.betterttv.net/assets/logos/bttv_logo.png
//
// @grant           none
//
// @match           https://*.twitch.tv/*
// @match           https://*.youtube.com/*
//
// @version         0.0.2
// ==/UserScript==

(function betterttv() {
    var script = document.createElement('script');
    script.type = 'text/javascript';
    script.src = 'https://cdn.betterttv.net/betterttv.js';
    var head = document.getElementsByTagName('head')[0];
    if (!head) return;
    head.appendChild(script);
})()
```


![B7737E4C-D048-46ED-B523-0496E40DEB22](https://user-images.githubusercontent.com/8468215/160540324-f038c2f0-9176-4c95-ad8a-b8f8c06624d9.jpeg)

![50988EC5-7CA8-443E-AFC1-CBBF58ACB362](https://user-images.githubusercontent.com/8468215/160540349-484b2631-0e3f-4e43-a6e6-c812a598d280.jpeg)

**Comment by night** [comment] 2022-12-31 04:13
closing this as a duplicate of #3158, which would resolve these both.

**Closed by night** 2022-12-31 04:13 UTC
Labels: duplicate
