### ISSUE TITLE
BTTV emotes have disappeared and my ENTER key will not send messages anymore

### ISSUE THREAD

**Issue by korean2na** [night/BetterTTV#2510] opened 2017-06-10 04:28 UTC
This started happening earlier this week for me. Just as the title states, my problem is twofold:
1) My BTTV emotes have all disappeared from the emote menus AND in the chat itself. For example, the "LUL"s in chat are text and not the emote, so on and so forth.
2) When I hit the ENTER key after typing out my message, it no longer sends the message. The message stays in the text field until I use the mouse to click the purple "Chat" button.

Actually, I just remembered there is a third issue that started happening when the other two started. When I start watching a stream and the chat is opened (automatically or manually), it will take much longer for chat to connect and it gives me a series of reconnect messages. (I've attached a screen clip of the messages)

![bttv bug](https://user-images.githubusercontent.com/29323947/26999965-419f5636-4d6b-11e7-9af6-549bf8a3b6b5.JPG)
(NOTE: for the screenshot, I had the advanced emotes menu disabled temporarily)

I suspect the problem may reside with BTTV because when I disable it or remove it from Firefox or Chrome, the ENTER key sends messages. Unfortunately, the delayed connection due to multiple connection attempts does not fix when disabling/uninstalling BTTV.

Here are my settings:
![bttv settings 1](https://user-images.githubusercontent.com/29323947/26999966-4e4dfe78-4d6b-11e7-9056-db2fef30a6d9.JPG)
![bttv settings 2](https://user-images.githubusercontent.com/29323947/26999967-504407b8-4d6b-11e7-995a-612cf04d17e0.JPG)
![bttv settings 2](https://user-images.githubusercontent.com/29323947/26999968-52adceee-4d6b-11e7-9888-bcfb9dcbb32d.JPG)
![bttv settings 4](https://user-images.githubusercontent.com/29323947/26999969-58a3aa12-4d6b-11e7-926f-75ba08e57283.JPG)

**Comment by Nareese** [comment] 2017-06-10 05:39
Updating Chrome to the latest version (59.0.3071.86) has resolved this issue for everyone who has reported it so far.  Go to Menu->Help->About Google Chrome to force an update check.  I am not aware of anyone else reporting this issue with Firefox (and one person reported that Firefox worked fine while Chrome was broken).  Please note that nothing has changed in BTTV since May 30th, so if BTTV worked for you after that date, and just stopped working earlier this week, it is not BTTV that is directly responsible.  Most likely Twitch changed something on their end or is running one of their numerous "experiments" that interacts badly with BTTV in some cases.

duplicate of #2504

**Comment by korean2na** [comment] 2017-06-10 06:03
Thanks, I'll try that out. I may just have to start using Chrome all the
time again haha.

**Closed** 2017-06-10 23:13 UTC
Labels: invalid
