### ISSUE TITLE
Better Twitch TV Emote setting aint working...

### ISSUE THREAD

**Issue by Cootee** [night/BetterTTV#170] opened 2015-01-16 21:51 UTC
I keep trying to turn off that god damn BTTV Monkey Emote Setting and its off but the stupid ugly monkey keeps showing up im getting pissed, i dont want to uninstall BTTV but I may have to if I cant get this fixed.

**Comment by night** [comment] 2015-01-16 22:21
Duplicate of https://github.com/night/BetterTTV/issues/160

**Closed by night** 2015-01-16 22:21 UTC
Labels: duplicate
