### ISSUE TITLE
Some colors in chat don't work

### ISSUE THREAD

**Issue by migdantas99** [night/betterttv#4451] opened 2021-04-09 17:19 UTC
I usually use red as my primary color on twitch, but ever since i installed bttv some colors don't seem to work too right and i don't really understand why. Red doesn't really work for instance, being that the reason as to why i noticed it in the first place. I would like to know if i'm the one doing something wrong or if this happens for a reason.
What i have noticed dough is that when i toggle in - Chat Appearance > Readable Colors - on and off the colors on screen seem to correct themselves until new messages pop up, like so:

![image](https://user-images.githubusercontent.com/71816678/114216604-0765ff80-995f-11eb-81b1-1c78db9bf0ef.png)

when i turn it on:

![image](https://user-images.githubusercontent.com/71816678/114216723-30869000-995f-11eb-806f-a940ba927e1e.png)

and then i turn it back off again:

![image](https://user-images.githubusercontent.com/71816678/114216804-4d22c800-995f-11eb-89a4-d8703ab6120e.png)

working as intended. Again, i don't know if i'm doing something wrong, but i can't seem to find anyone else with this problem online.
Thank you so much for the help in advance, this is an amazing extension and everything works as it should otherwise, so sorry for the nitpick.

P.S. - I don't think that the problem has to do with me trying out Opera GX, because i also tried it on Google Chrome and the problem still stood.

**Comment by night** [comment] 2021-04-19 02:47
duplicate of #3320

**Closed by night** 2021-04-19 02:47 UTC
Labels: duplicate
