### ISSUE TITLE
My BTTV emotes are not working when I manually type them in

### ISSUE THREAD

**Issue by K3x707x** [night/BetterTTV#1870] opened 2016-12-13 03:02 UTC
As the title says. I type in BTTV emotes and they dont work. I uninstalled BTTV and re-installed it, which is what a friend suggested. But it still wont work. Pls look into this because I dont have time to open up the menu and search for the emote while trying to moderate and keep up with chat. Thx

**Comment by thinkpad4** [comment] 2016-12-13 03:08
Turn off Disable Channel Header temporally. That seems to fix it

**Comment by K3x707x** [comment] 2016-12-13 03:21
Ok ill try that. thx

**Comment by thinkpad4** [comment] 2016-12-13 03:32
Np

**Comment by EhsanKia** [comment] 2016-12-13 03:41
Duplicate of #1866

**Closed by EhsanKia** 2016-12-13 03:41 UTC
