### ISSUE TITLE
Problems with Left Side Chat setting on Theatre Mode

### ISSUE THREAD

**Issue by Poxulan** [night/BetterTTV#3035] opened 2018-03-17 19:15 UTC
When Left Side Chat is enabled and you enter Theatre Mode, you can't see chat. Only white or dark gray rectangle (Depending on the Dark Theme is enabled or not). I hope You'll fix it, because I really like using Left Side Chat, but I can't watch streams without bigger screen then.

**Comment by night** [comment] 2018-03-17 21:04
duplicate of #2971

**Closed by night** 2018-03-17 21:04 UTC
Labels: duplicate
