### ISSUE TITLE
New Twitch layout LEFT SIDE CHAT issues

### ISSUE THREAD

**Issue by Suntop-Kinseeker** [night/betterttv#3878] opened 2020-05-13 14:32 UTC
Due to the change twitch as made, BTTV Left Side chat is broken, I have to put in theater mode in order to see chat. May have to do with some padding or something. I have to turn it off in order to see things properly outside theater mode. Can you please look into fixing this. Thank you

**Comment by night** [comment] 2020-05-18 22:41
duplicate of #3873

**Closed by night** 2020-05-18 22:41 UTC
Labels: duplicate
