### ISSUE TITLE
Split chat unreadable

### ISSUE THREAD

**Issue by whiteev** [night/BetterTTV#3226] opened 2018-08-23 00:41 UTC
Split chat is setting the background colour of every second message to the same as the text colour, making the content of the message unreadable.
![bttv split chat](https://user-images.githubusercontent.com/14939200/44498309-9d956c00-a675-11e8-8da7-ef61462dc981.png)

**Comment by Nareese** [comment] 2018-08-23 01:09
duplicate of #3216

**Closed** 2018-08-23 03:01 UTC
Labels: duplicate
