### ISSUE TITLE
Suggestion: Curb Emote Spam

### ISSUE THREAD

**Issue by n0va13** [night/betterttv#4137] opened 2020-09-08 14:19 UTC
Could there possibly be an option to limit the emotes from each user in chat to 1 each person? I don't have the best computer and for some reason when chat spams emotes (for subs etc) it cripples my browser, sometimes the stream lags, and the browser can crash. It's just too much for my laptop when 200 people spam the same emote 20 times each. It's not just BTTV emotes it's even the stock sub emotes on Twitch.

**Comment by night** [comment] 2020-09-29 10:34
duplicate of #1922

**Closed by night** 2020-09-29 10:34 UTC
Labels: duplicate
