### ISSUE TITLE
Minor chat issue when joining streams 

### ISSUE THREAD

**Issue by trulloch** [night/BetterTTV#2580] opened 2017-07-18 17:11 UTC
I get a this black box over the chat window when joining streams. Doesn't matter what stream I join it will still be there, I can click on the name of the streamer under "channel chat" to make it go away, but if I leave the stream and come back, it pops up again. I only have dark mode enabled for BTTV settings and if I disable the BTTV extension the issue goes away. (using Chrome browser Version 59.0.3071.115 (64-bit) and BTTV 7.2
 
![cha](https://user-images.githubusercontent.com/30268822/28329866-7a3aaf2e-6bb9-11e7-8101-8069ee566640.png)

**Comment by night** [comment] 2017-07-19 04:35
duplicate of #2559

**Closed by night** 2017-07-19 04:35 UTC
Labels: duplicate
