### ISSUE TITLE
Disable specific BetterTTV emotes.

### ISSUE THREAD

**Issue by Bonkuraazu** [night/BetterTTV#325] opened 2015-04-05 16:59 UTC
It'd be nice to have a window that opens from settings where you can disable certain emotes. Personally i'd disable the emotes for "D:", ":'(", and maybe the animated ones too. I'd rather not blacklist them either because i'd like to see the original text.

**Comment by night** [comment] 2015-04-30 13:43
This would be a duplicate of https://github.com/night/BetterTTV/issues/67 when implemented

**Closed by night** 2015-04-30 13:43 UTC
Labels: duplicate
