### ISSUE TITLE
Stream buffers when setting highlight keywords

### ISSUE THREAD

**Issue by MattUnderscore** [night/BetterTTV#576] opened 2015-07-20 03:26 UTC
After a few seconds of having the window open, the stream buffers. Immediately resumes after closing it.

**Comment by vendethiel** [comment] 2015-07-20 06:49
That's most probably because of the browser itself, though(?). I don't think we're doing anything that does this.

**Comment by night** [comment] 2015-07-20 07:26
Duplicate of #494

**Closed by night** 2015-07-20 07:26 UTC
Labels: duplicate
