### ISSUE TITLE
mention from double clicking username disappears

### ISSUE THREAD

**Issue by mroseman95** [night/BetterTTV#3087] opened 2018-04-29 23:31 UTC
Steps to reproduce:
1. start a twitch stream
2. double click on username to mention them in the chat textarea
3. wait for more chat messages (don't type anything in chat textarea)
4. the mention text in chat textarea disappears

If you inspect the textarea, the value never changes, even though you can visually see the mention text.

If you manually edit any text in chat textarea before more chat messages come through then it will register the mention text, but for chats that are moving fast this could be difficult.

**Comment by NewHayer** [comment] 2018-05-18 13:48
Duplicate of #3113

**Closed** 2018-05-29 03:10 UTC
Labels: bug, chat
