### ISSUE TITLE
[Feature Request] Highlighting of certain roles

### ISSUE THREAD

**Issue by RandomRocker** [night/BetterTTV#3127] opened 2018-05-29 19:37 UTC
I think it would be good to have the ability to highlight certain roles, much in the way you do for keywords at the moment. For example staff, global admins or moderators, and maybe instead of having the highlight in red, maybe have staff in blue, global admins orange and mods green.

Sometimes in fast chat it would be nice to have the ability to highlight people who are staff.

Just a thought.

**Comment by night** [comment] 2018-06-01 06:02
duplicate of #237

**Closed by night** 2018-06-01 06:02 UTC
Labels: duplicate
