### ISSUE TITLE
issue with a full screen

### ISSUE THREAD

**Issue by spell09** [night/BetterTTV#1745] opened 2016-11-10 13:52 UTC
http://i.imgur.com/iHVgz84.png when i'm trying to watch in a full screen mode, some part of the screen was staying like a black bar. Instead of the place where is chat must be. Its only causes when i switch from theatre mod to full screen mode.

**Comment by EhsanKia** [comment] 2016-11-10 16:34
Duplicate of #1721, though maybe we should fix it for Twitch since that's always what we end up doing... fixing their broken site for them.

**Comment by spell09** [comment] 2016-11-10 16:42
sorry, didn't saw a closed topic

**Comment by night** [comment] 2016-11-11 07:53
This was already fixed...

**Closed by night** 2016-11-11 07:53 UTC
Labels: invalid
